package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();
        listaPokemon.add(new Planta("Venusau",
                3,
                80,
                82,
                83,
                100,
                100,
                80,
                "Planta/Veneno",
                "2,0",
                "Semilla",
                "100,0",
                "Espesura",
                "Después de un día de lluvia, el aroma de la flor que tiene en el lomo se intensifica y atrae a otros Pokémon.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\venusaur.jpg"));
        listaPokemon.add(new Fuego("Charizard",
                6,
                78,
                84,
                78,
                109,
                85,
                100,
                "Fuego/Volador",
                "1,7",
                "Llama",
                "90.5",
                "Mar Llamas",
                "Sus potentes alas le permiten volar a una altura de 1,400 m. Escupe llamaradas que alcanzan temperaturas muy elevadas.",
                "♀/♂",
                "Fuego,Volador",
                "Agua,Electrico,Roca X",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\charizard.jpg"));
        listaPokemon.add(new Agua("Blastoise",
                9,
                79,
                83,
                100,
                85,
                105,
                78,
                "Agua",
                "1,6",
                "Armazon",
                "85,5",
                "Torrente",
                "Para vencer a su enemigo, lo aplasta con el peso de su cuerpo. En momentos de apuro, se esconde en el caparazón.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\blastoise.jpg"));
        listaPokemon.add(new Bicho("Butterfree",
                12,
                60,
                45,
                50,
                90,
                80,
                70,
                "Bicho/Volador",
                "1,1",
                "Mariposa",
                "32,0",
                "Ojo Compuesto",
                "Adora el néctar de las flores. Una pequeña cantidad de polen le basta para localizar prados floridos.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Electrico,Volador,Roca X,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\12.jpg"));
        listaPokemon.add(new Bicho("Beedrill",
                15,
                65,
                90,
                40,
                45,
                80,
                75,
                "Bicho/Veneno",
                "1,0",
                "Abeja Veneno",
                "29.5",
                "Enjambre",
                "Tiene tres aguijones venenosos, dos en las patas anteriores y uno en la parte baja del abdomen, con los que ataca a sus enemigos una y otra vez.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\15.jpg"));
        listaPokemon.add(new Volador("Pidgeot",
                18,
                83,
                80,
                75,
                70,
                70,
                101,
                "Normal/Volador",
                "1,5",
                "Pajaro",
                "39,5",
                "Vista Lince, Tumbos",
                "Este Pokémon vuela a una velocidad de 2 mach en busca de presas. Sus grandes garras son armas muy peligrosas.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Roca,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\18.jpg"));
        listaPokemon.add(new Normal("Raticate",
                20,
                55,
                81,
                60,
                50,
                70,
                97,
                "Normal",
                "0,7",
                "Raton",
                "18,5",
                "Fuga, Agallas",
                "Gracias a las pequeñas membranas de las patas traseras, puede nadar por los ríos para capturar presas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\20.jpg"));
        listaPokemon.add(new Volador("Fearow",
                22,
                65,
                90,
                65,
                61,
                61,
                100,
                "Normal/Volador",
                "1,2",
                "Pico",
                "38,0",
                "Vista Lince, Francotirador",
                "Puede volar a gran velocidad y recorrer grandes distancias sin descansar.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\22.jpg"));
        listaPokemon.add(new Veneno("Arbok",
                24,
                60,
                95,
                69,
                65,
                79,
                80,
                "Veneno",
                "3,5",
                "Cobra",
                "65,0",
                "Mudar, Intimidacion, Nerviosismo",
                "El dibujo de su pecho puede cambiar y se cree que tiene un efecto intimidante sobre sus enemigos.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\24.jpg"));
        listaPokemon.add(new Electrico("Raichu",
                26,
                60,
                90,
                55,
                90,
                80,
                110,
                "Electrico",
                "0,8",
                "Raton",
                "30,0",
                "Electricidad Estatica, Pararrayos",
                "Puede acumular una enorme cantidad de electricidad y descargarla a traves de su cola.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\26.jpg"));
        listaPokemon.add(new Tierra("Sandslash",
                28,
                75,
                100,
                110,
                45,
                55,
                65,
                "Tierra",
                "1,0",
                "Raton",
                "29,5",
                "Velo Arena",
                "Sus garras y espinas le permiten excavar rapidamente y defenderse de sus enemigos.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\28.jpg"));
        listaPokemon.add(new Veneno("Nidoqueen",
                31,
                90,
                92,
                87,
                75,
                85,
                76,
                "Veneno/Tierra",
                "1,3",
                "Taladro",
                "60,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Su cuerpo esta cubierto por escamas resistentes que le permiten proteger a sus crias de los peligros.",
                "♀",
                "Veneno, Tierra",
                "Agua, Hielo, Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\31.jpg"));
        listaPokemon.add(new Veneno("Nidoking",
                34,
                81,
                102,
                77,
                85,
                75,
                85,
                "Veneno/Tierra",
                "1,4",
                "Taladro",
                "62,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Su poderoso cuerno puede atravesar incluso materiales resistentes y lo utiliza para atacar a sus enemigos.",
                "♂",
                "Veneno, Tierra",
                "Agua, Hielo, Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\34.jpg"));
        listaPokemon.add(new Normal("Clefable",
                36,
                95,
                70,
                73,
                95,
                90,
                60,
                "Hada",
                "1,3",
                "Hada",
                "40,0",
                "Gran Encanto, Muro Magico, Amortiguador",
                "Tiene un oido extremadamente sensible y puede escuchar sonidos muy lejanos.",
                "♀/♂",
                "Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\36.jpg"));
        listaPokemon.add(new Fuego("Ninetales",
                38,
                73,
                76,
                75,
                81,
                100,
                100,
                "Fuego",
                "1,1",
                "Zorro",
                "19,9",
                "Absorbe Fuego, Sequedad",
                "Cuenta la leyenda que cada una de sus nueve colas posee poderes misteriosos.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\38.jpg"));
        listaPokemon.add(new Normal("Wigglytuff",
                40,
                140,
                70,
                45,
                85,
                50,
                45,
                "Normal/Hada",
                "1,0",
                "Globo",
                "12,0",
                "Gran Encanto, Tenacidad, Competitivo",
                "Su cuerpo suave y elastico puede inflarse hasta alcanzar un tamaño enorme.",
                "♀/♂",
                "Normal, Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\40.jpg"));
        listaPokemon.add(new Volador("Golbat",
                42,
                75,
                80,
                70,
                65,
                75,
                90,
                "Veneno/Volador",
                "1,6",
                "Murcielago",
                "55,0",
                "Fuerza Mental, Infiltrador",
                "Cuando muerde a su presa, no la suelta hasta haber absorbido una gran cantidad de sangre.",
                "♀/♂",
                "Veneno, Volador",
                "Electrico, Hielo, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\42.jpg"));
        listaPokemon.add(new Planta("Vileplume",
                45,
                75,
                80,
                85,
                110,
                90,
                50,
                "Planta/Veneno",
                "1,2",
                "Flor",
                "18,6",
                "Clorofila",
                "Cuanto mas grande es el polen de su flor, mas potente es el veneno que contiene.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\45.jpg"));
        listaPokemon.add(new Bicho("Parasect",
                47,
                60,
                95,
                80,
                60,
                80,
                30,
                "Bicho/Planta",
                "1,0",
                "Hongo",
                "29,5",
                "Efecto Espora, Piel Seca, Humedad",
                "El hongo ha tomado completamente el control de su cuerpo y libera esporas toxicas.",
                "♀/♂",
                "Bicho, Planta",
                "Fuego, Hielo, Veneno, Volador, Bicho, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\47.jpg"));
        listaPokemon.add(new Bicho("Venomoth",
                49,
                70,
                65,
                60,
                90,
                75,
                90,
                "Bicho/Veneno",
                "1,5",
                "Polilla",
                "12,5",
                "Ojo Compuesto, Polvo Escudo, Cromolente",
                "Sus alas liberan escamas venenosas que pueden causar distintos efectos a sus enemigos.",
                "♀/♂",
                "Bicho, Veneno",
                "Fuego, Volador, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\49.jpg"));
        listaPokemon.add(new Tierra("Dugtrio",
                51,
                35,
                100,
                50,
                50,
                70,
                120,
                "Tierra",
                "0,7",
                "Topo",
                "33,3",
                "Velo Arena, Trampa Arena, Poder Arena",
                "Tres Diglett viven juntos y trabajan en equipo para excavar enormes tuneles.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\51.jpg"));
        listaPokemon.add(new Normal("Persian",
                53,
                65,
                70,
                60,
                65,
                65,
                115,
                "Normal",
                "1,0",
                "Gato Fino",
                "32,0",
                "Flexibilidad, Experto, Nerviosismo",
                "Su aspecto elegante oculta un temperamento agresivo y sus garras son extremadamente afiladas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\53.jpg"));
        listaPokemon.add(new Agua("Golduck",
                55,
                80,
                82,
                78,
                95,
                80,
                85,
                "Agua",
                "1,7",
                "Pato",
                "76,6",
                "Humedad, Nublado, Aclimatacion",
                "Es un excelente nadador y puede alcanzar velocidades impresionantes en el agua.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\55.jpg"));
        listaPokemon.add(new Lucha("Primeape",
                57,
                65,
                105,
                60,
                60,
                70,
                95,
                "Lucha",
                "1,0",
                "Mono Cerdo",
                "32,0",
                "Espiritu Vital, Ira Vital, Competitivo",
                "Su furia aumenta hasta tal punto que puede perseguir a su objetivo sin descanso.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\57.jpg"));
        listaPokemon.add(new Fuego("Arcanine",
                59,
                90,
                110,
                80,
                100,
                80,
                95,
                "Fuego",
                "1,9",
                "Legendario",
                "155,0",
                "Intimidacion, Absorbe Fuego, Justiciero",
                "Es admirado por su belleza y majestuosidad. Puede recorrer grandes distancias a gran velocidad.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\59.jpg"));
        listaPokemon.add(new Agua("Poliwrath",
                62,
                90,
                95,
                95,
                70,
                90,
                70,
                "Agua/Lucha",
                "1,3",
                "Renacuajo",
                "54,0",
                "Absorbe Agua, Humedad, Nado Rapido",
                "Sus poderosos musculos le permiten nadar largas distancias sin cansarse.",
                "♀/♂",
                "Agua, Lucha",
                "Electrico, Planta, Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\62.jpg"));
        listaPokemon.add(new Psiquico("Alakazam",
                65,
                55,
                50,
                45,
                135,
                95,
                120,
                "Psiquico",
                "1,5",
                "Psiquico",
                "48,0",
                "Sincronía, Foco Interno, Muro Magico",
                "Posee una inteligencia extraordinaria y se dice que tiene un coeficiente intelectual de 5000.",
                "♀/♂",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\65.jpg"));
        listaPokemon.add(new Lucha("Machamp",
                68,
                90,
                130,
                80,
                65,
                85,
                55,
                "Lucha",
                "1,6",
                "Superpoder",
                "130,0",
                "Agallas, Indefenso, Impasible",
                "Sus cuatro brazos pueden lanzar una gran cantidad de golpes en pocos segundos.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\68.jpg"));
        listaPokemon.add(new Normal("Dodrio",
                85,
                60,
                110,
                70,
                60,
                60,
                110,
                "Normal/Volador",
                "1,8",
                "Ave Gemela",
                "85,2",
                "Fuga, Madrugar, Intrépido",
                "Sus tres cabezas representan diferentes personalidades y pueden trabajar de forma coordinada.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\85.jpg"));
        listaPokemon.add(new Agua("Dewgong",
                87,
                90,
                70,
                80,
                70,
                95,
                70,
                "Agua/Hielo",
                "1,7",
                "Leon Marino",
                "120,0",
                "Sebo, Hidratacion, Gélido",
                "Su cuerpo esta cubierto por una gruesa capa de grasa que le permite vivir en aguas heladas.",
                "♀/♂",
                "Agua, Hielo",
                "Electrico, Planta, Lucha, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\87.jpg"));
        listaPokemon.add(new Veneno("Muk",
                89,
                105,
                105,
                75,
                65,
                100,
                50,
                "Veneno",
                "1,2",
                "Lodo",
                "30,0",
                "Velo Liquido, Viscosidad, Toque Toxico",
                "Su cuerpo esta formado por sustancias toxicas y puede contaminar todo lo que toca.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\89.jpg"));
        listaPokemon.add(new Agua("Cloyster",
                91,
                50,
                95,
                180,
                85,
                45,
                70,
                "Agua/Hielo",
                "1,5",
                "Bivalvo",
                "132,5",
                "Caparazon, Encadenado, Funda",
                "Su caparazon puede soportar una fuerza enorme y sus numerosas espinas sirven para atacar.",
                "♀/♂",
                "Agua, Hielo",
                "Electrico, Planta, Lucha, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\91.jpg"));
        listaPokemon.add(new Fantasma("Gengar",
                94,
                60,
                65,
                60,
                130,
                75,
                110,
                "Fantasma/Veneno",
                "1,5",
                "Sombra",
                "40,5",
                "Cuerpo Maldito",
                "Se esconde en las sombras de las personas y disfruta asustando a quienes encuentra.",
                "♀/♂",
                "Fantasma, Veneno",
                "Tierra, Psiquico, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\94.jpg"));
        listaPokemon.add(new Agua("Kingler",
                99,
                55,
                130,
                115,
                50,
                50,
                75,
                "Agua",
                "1,3",
                "Tenaza",
                "60,0",
                "Corte Fuerte, Caparazon, Potencia Bruta",
                "Una de sus pinzas es mucho mas grande que la otra y puede ejercer una fuerza enorme.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\99.jpg"));
        listaPokemon.add(new Lucha("Hitmonlee",
                106,
                50,
                120,
                53,
                35,
                110,
                87,
                "Lucha",
                "1,5",
                "Patada",
                "49,8",
                "Flexibilidad, Audaz, Impasible",
                "Sus piernas pueden estirarse y sus patadas son extremadamente potentes.",
                "♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\106.jpg"));
        listaPokemon.add(new Lucha("Hitmonchan",
                107,
                50,
                105,
                79,
                35,
                110,
                76,
                "Lucha",
                "1,4",
                "Puñetazo",
                "50,2",
                "Vista Lince, Puño Ferreo, Impasible",
                "Sus puños se mueven tan rapidamente que pueden parecer una rafaga continua de golpes.",
                "♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\107.jpg"));
        listaPokemon.add(new Normal("Lickitung",
                108,
                90,
                55,
                75,
                60,
                75,
                30,
                "Normal",
                "1,2",
                "Lametazo",
                "65,5",
                "Despiste, Ritmo Propio, Nube de Humo",
                "Su lengua es tan larga que puede extenderla hasta casi dos metros y utilizarla como una mano.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\108.jpg"));
        listaPokemon.add(new Veneno("Weezing",
                110,
                65,
                90,
                120,
                85,
                70,
                60,
                "Veneno",
                "1,2",
                "Gas Venenoso",
                "9,5",
                "Levitacion",
                "Dos Koffing se unen y mezclan sus gases toxicos para producir una sustancia aun mas peligrosa.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\110.jpg"));
        listaPokemon.add(new Normal("Chansey",
                113,
                250,
                5,
                5,
                35,
                105,
                50,
                "Normal",
                "1,1",
                "Huevo",
                "34,6",
                "Cura Natural, Dicha, Alma Cura",
                "Pone huevos muy nutritivos y suele compartirlos con personas o Pokemon heridos.",
                "♀",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\113.jpg"));
        listaPokemon.add(new Psiquico("Mr. Mime",
                122,
                40,
                45,
                65,
                100,
                120,
                90,
                "Psiquico/Hada",
                "1,3",
                "Barrera",
                "54,5",
                "Filtro, Tecnico, Insonorizar",
                "Es experto en crear barreras invisibles mediante movimientos de mimo y puede bloquear ataques.",
                "♀/♂",
                "Psiquico, Hada",
                "Veneno, Acero, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\122.jpg"));
        listaPokemon.add(new Bicho("Scyther",
                123,
                70,
                110,
                80,
                55,
                80,
                105,
                "Bicho/Volador",
                "1,5",
                "Mantis",
                "56,0",
                "Enjambre, Experto, Impasible",
                "Sus guadañas son tan afiladas que puede cortar troncos gruesos con facilidad.",
                "♀/♂",
                "Bicho, Volador",
                "Fuego, Electrico, Hielo, Volador, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\123.jpg"));
        listaPokemon.add(new Psiquico("Jynx",
                124,
                65,
                50,
                35,
                115,
                95,
                95,
                "Hielo/Psiquico",
                "1,4",
                "Humanoide",
                "40,6",
                "Despiste, Alerta, Ritmo Propio",
                "Se comunica mediante una especie de lenguaje propio basado principalmente en movimientos y sonidos.",
                "♀",
                "Hielo, Psiquico",
                "Fuego, Acero, Bicho, Roca, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\124.jpg"));
        listaPokemon.add(new Electrico("Electabuzz",
                125,
                65,
                83,
                57,
                95,
                85,
                105,
                "Electrico",
                "1,1",
                "Electrico",
                "30,0",
                "Electricidad Estatica, Espiritu Vital",
                "Absorbe electricidad de los generadores y puede provocar apagones cuando hay tormentas.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\125.jpg"));
        listaPokemon.add(new Fuego("Magmar",
                126,
                65,
                95,
                57,
                100,
                85,
                93,
                "Fuego",
                "1,3",
                "Escupefuego",
                "44,5",
                "Cuerpo Llama, Espiritu Vital",
                "Su cuerpo esta tan caliente que puede incendiar accidentalmente los lugares por donde pasa.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\126.jpg"));
        listaPokemon.add(new Agua("Vaporeon",
                134,
                130,
                65,
                60,
                110,
                95,
                65,
                "Agua",
                "1,0",
                "Burbuja",
                "29,0",
                "Absorbe Agua, Hidratacion",
                "Su cuerpo esta adaptado para vivir en el agua y puede disolverse parcialmente en ella.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\134.jpg"));
        listaPokemon.add(new Electrico("Jolteon",
                135,
                65,
                65,
                60,
                110,
                95,
                130,
                "Electrico",
                "0,8",
                "Relampago",
                "24,5",
                "Absorbe Electricidad, Volt Absorb",
                "Tiene el pelo lleno de electricidad estatica y puede disparar miles de rayos por segundo.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\135.jpg"));
        listaPokemon.add(new Fuego("Flareon",
                136,
                65,
                130,
                60,
                95,
                110,
                65,
                "Fuego",
                "0,9",
                "Llama",
                "25,0",
                "Absorbe Fuego, Agallas",
                "Almacena aire en una bolsa interna y lo calienta hasta producir llamas extremadamente intensas.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\136.jpg"));
        listaPokemon.add(new Hielo("Articuno",
                144,
                90,
                85,
                100,
                95,
                125,
                85,
                "Hielo/Volador",
                "1,7",
                "Congelar",
                "55,4",
                "Presion, Manto Niveo",
                "Es un Pokemon legendario que puede congelar la humedad del aire y crear nieve y hielo.",
                "Sin genero",
                "Hielo, Volador",
                "Fuego, Electrico, Acero, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\144.jpg"));
        listaPokemon.add(new Electrico("Zapdos",
                145,
                90,
                90,
                85,
                125,
                90,
                100,
                "Electrico/Volador",
                "1,6",
                "Electrico",
                "52,6",
                "Presion, Electricidad Estatica",
                "Un Pokemon legendario que aparece durante tormentas y puede generar enormes cantidades de electricidad.",
                "Sin genero",
                "Electrico, Volador",
                "Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\145.jpg"));
        listaPokemon.add(new Fuego("Moltres",
                146,
                90,
                100,
                90,
                125,
                85,
                90,
                "Fuego/Volador",
                "2,0",
                "Llama",
                "60,0",
                "Presion, Cuerpo Llama",
                "Un Pokemon legendario cubierto de llamas que aparece en lugares donde se producen grandes cambios de clima.",
                "Sin genero",
                "Fuego, Volador",
                "Agua, Electrico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\146.jpg"));
        listaPokemon.add(new Dragon("Dragonite",
                149,
                91,
                134,
                95,
                100,
                100,
                80,
                "Dragon/Volador",
                "2,2",
                "Dragon",
                "210,0",
                "Foco Interno, Multiescamas",
                "Es extremadamente inteligente y puede volar alrededor del mundo en aproximadamente dieciseis horas.",
                "♀/♂",
                "Dragon, Volador",
                "Hielo, Roca, Dragon, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\149.jpg"));
        listaPokemon.add(new Psiquico("Mewtwo",
                150,
                106,
                110,
                90,
                154,
                90,
                130,
                "Psiquico",
                "2,0",
                "Genetico",
                "122,0",
                "Presion, Nerviosismo",
                "Fue creado mediante manipulacion genetica y posee un poder psiquico extraordinario.",
                "Sin genero",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\150.jpg"));
        listaPokemon.add(new Psiquico("Mew",
                151,
                100,
                100,
                100,
                100,
                100,
                100,
                "Psiquico",
                "0,4",
                "Nueva Especie",
                "4,0",
                "Sincronía",
                "Posee el ADN de todos los Pokemon y puede aprender cualquier movimiento.",
                "Sin genero",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\151.jpg"));

        return listaPokemon;
    }
}