package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexTeseliaRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();
        listaPokemon.add(new Psiquico("Victini",
                494,
                100,
                100,
                100,
                100,
                100,
                100,
                "Psiquico/Fuego",
                "",
                "",
                "",
                "",
                "Victini es un Pokemon originario de Teselia de tipo Psiquico/Fuego.",
                "",
                "Psiquico,Fuego",
                "Bicho,Fantasma,Siniestro,Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Planta("Serperior",
                497,
                75,
                75,
                95,
                75,
                95,
                113,
                "Planta",
                "",
                "",
                "",
                "",
                "Serperior es un Pokemon originario de Teselia de tipo Planta.",
                "",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Fuego("Emboar",
                500,
                110,
                123,
                65,
                100,
                65,
                65,
                "Fuego/Lucha",
                "",
                "",
                "",
                "",
                "Emboar es un Pokemon originario de Teselia de tipo Fuego/Lucha.",
                "",
                "Fuego,Lucha",
                "Agua,Tierra,Roca,Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Agua("Samurott",
                503,
                95,
                100,
                85,
                108,
                70,
                70,
                "Agua",
                "",
                "",
                "",
                "",
                "Samurott es un Pokemon originario de Teselia de tipo Agua.",
                "",
                "Agua",
                "Planta,Electrico",
                ""));
        listaPokemon.add(new Normal("Watchog",
                505,
                60,
                85,
                69,
                60,
                69,
                77,
                "Normal",
                "",
                "",
                "",
                "",
                "Watchog es un Pokemon originario de Teselia de tipo Normal.",
                "",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Normal("Stoutland",
                508,
                85,
                110,
                90,
                45,
                90,
                80,
                "Normal",
                "",
                "",
                "",
                "",
                "Stoutland es un Pokemon originario de Teselia de tipo Normal.",
                "",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Normal("Liepard",
                510,
                64,
                88,
                50,
                88,
                50,
                106,
                "Siniestro",
                "",
                "",
                "",
                "",
                "Liepard es un Pokemon originario de Teselia de tipo Siniestro.",
                "",
                "Siniestro",
                "Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Planta("Simisage",
                512,
                75,
                98,
                63,
                98,
                63,
                101,
                "Planta",
                "",
                "",
                "",
                "",
                "Simisage es un Pokemon originario de Teselia de tipo Planta.",
                "",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Fuego("Simisear",
                514,
                75,
                98,
                63,
                98,
                63,
                101,
                "Fuego",
                "",
                "",
                "",
                "",
                "Simisear es un Pokemon originario de Teselia de tipo Fuego.",
                "",
                "Fuego",
                "Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Agua("Simipour",
                516,
                75,
                98,
                63,
                98,
                63,
                101,
                "Agua",
                "",
                "",
                "",
                "",
                "Simipour es un Pokemon originario de Teselia de tipo Agua.",
                "",
                "Agua",
                "Planta,Electrico",
                ""));
        listaPokemon.add(new Psiquico("Musharna",
                518,
                116,
                55,
                85,
                107,
                95,
                29,
                "Psiquico",
                "",
                "",
                "",
                "",
                "Musharna es un Pokemon originario de Teselia de tipo Psiquico.",
                "",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Normal("Unfezant",
                521,
                80,
                115,
                80,
                65,
                55,
                93,
                "Normal/Volador",
                "",
                "",
                "",
                "",
                "Unfezant es un Pokemon originario de Teselia de tipo Normal/Volador.",
                "",
                "Normal,Volador",
                "Lucha,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Electrico("Zebstrika",
                523,
                75,
                100,
                63,
                80,
                63,
                116,
                "Electrico",
                "",
                "",
                "",
                "",
                "Zebstrika es un Pokemon originario de Teselia de tipo Electrico.",
                "",
                "Electrico",
                "Tierra",
                ""));
        listaPokemon.add(new Roca("Gigalith",
                526,
                85,
                135,
                130,
                60,
                80,
                25,
                "Roca",
                "",
                "",
                "",
                "",
                "Gigalith es un Pokemon originario de Teselia de tipo Roca.",
                "",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                ""));
        listaPokemon.add(new Psiquico("Swoobat",
                528,
                67,
                57,
                55,
                77,
                55,
                114,
                "Psiquico/Volador",
                "",
                "",
                "",
                "",
                "Swoobat es un Pokemon originario de Teselia de tipo Psiquico/Volador.",
                "",
                "Psiquico,Volador",
                "Bicho,Fantasma,Siniestro,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Tierra("Excadrill",
                530,
                110,
                135,
                60,
                50,
                65,
                88,
                "Tierra/Acero",
                "",
                "",
                "",
                "",
                "Excadrill es un Pokemon originario de Teselia de tipo Tierra/Acero.",
                "",
                "Tierra,Acero",
                "Agua,Planta,Hielo,Fuego,Lucha,Tierra",
                ""));
        listaPokemon.add(new Normal("Audino",
                531,
                103,
                60,
                86,
                60,
                86,
                50,
                "Normal",
                "",
                "",
                "",
                "",
                "Audino es un Pokemon originario de Teselia de tipo Normal.",
                "",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Lucha("Conkeldurr",
                534,
                105,
                140,
                95,
                55,
                65,
                45,
                "Lucha",
                "",
                "",
                "",
                "",
                "Conkeldurr es un Pokemon originario de Teselia de tipo Lucha.",
                "",
                "Lucha",
                "Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Agua("Seismitoad",
                537,
                105,
                95,
                75,
                85,
                75,
                74,
                "Agua/Tierra",
                "",
                "",
                "",
                "",
                "Seismitoad es un Pokemon originario de Teselia de tipo Agua/Tierra.",
                "",
                "Agua,Tierra",
                "Planta,Electrico,Agua,Hielo",
                ""));
        listaPokemon.add(new Lucha("Throh",
                538,
                120,
                100,
                85,
                30,
                85,
                45,
                "Lucha",
                "",
                "",
                "",
                "",
                "Throh es un Pokemon originario de Teselia de tipo Lucha.",
                "",
                "Lucha",
                "Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Lucha("Sawk",
                539,
                75,
                125,
                75,
                30,
                75,
                85,
                "Lucha",
                "",
                "",
                "",
                "",
                "Sawk es un Pokemon originario de Teselia de tipo Lucha.",
                "",
                "Lucha",
                "Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Bicho("Leavanny",
                542,
                75,
                103,
                80,
                70,
                80,
                92,
                "Bicho/Planta",
                "",
                "",
                "",
                "",
                "Leavanny es un Pokemon originario de Teselia de tipo Bicho/Planta.",
                "",
                "Bicho,Planta",
                "Fuego,Volador,Roca,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Bicho("Scolipede",
                545,
                60,
                100,
                89,
                55,
                69,
                112,
                "Bicho/Veneno",
                "",
                "",
                "",
                "",
                "Scolipede es un Pokemon originario de Teselia de tipo Bicho/Veneno.",
                "",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Tierra,Psiquico",
                ""));
        listaPokemon.add(new Planta("Whimsicott",
                547,
                60,
                67,
                85,
                77,
                75,
                116,
                "Planta/Hada",
                "",
                "",
                "",
                "",
                "Whimsicott es un Pokemon originario de Teselia de tipo Planta/Hada.",
                "",
                "Planta,Hada",
                "Fuego,Volador,Hielo,Bicho,Veneno,Acero",
                ""));
        listaPokemon.add(new Planta("Lilligant",
                549,
                70,
                60,
                75,
                110,
                75,
                90,
                "Planta",
                "",
                "",
                "",
                "",
                "Lilligant es un Pokemon originario de Teselia de tipo Planta.",
                "",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Agua("Basculin",
                550,
                70,
                92,
                65,
                80,
                55,
                98,
                "Agua",
                "",
                "",
                "",
                "",
                "Basculin es un Pokemon originario de Teselia de tipo Agua.",
                "",
                "Agua",
                "Planta,Electrico",
                ""));
        listaPokemon.add(new Tierra("Krookodile",
                553,
                95,
                117,
                80,
                65,
                70,
                92,
                "Tierra/Siniestro",
                "",
                "",
                "",
                "",
                "Krookodile es un Pokemon originario de Teselia de tipo Tierra/Siniestro.",
                "",
                "Tierra,Siniestro",
                "Agua,Planta,Hielo,Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Fuego("Darmanitan",
                555,
                105,
                140,
                55,
                30,
                55,
                95,
                "Fuego",
                "",
                "",
                "",
                "",
                "Darmanitan es un Pokemon originario de Teselia de tipo Fuego.",
                "",
                "Fuego",
                "Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Planta("Maractus",
                556,
                75,
                86,
                67,
                106,
                67,
                60,
                "Planta",
                "",
                "",
                "",
                "",
                "Maractus es un Pokemon originario de Teselia de tipo Planta.",
                "",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Bicho("Crustle",
                558,
                70,
                105,
                125,
                65,
                75,
                45,
                "Bicho/Roca",
                "",
                "",
                "",
                "",
                "Crustle es un Pokemon originario de Teselia de tipo Bicho/Roca.",
                "",
                "Bicho,Roca",
                "Fuego,Volador,Roca,Agua,Planta,Lucha,Tierra,Acero",
                ""));
        listaPokemon.add(new Normal("Scrafty",
                560,
                65,
                90,
                115,
                45,
                115,
                58,
                "Siniestro/Lucha",
                "",
                "",
                "",
                "",
                "Scrafty es un Pokemon originario de Teselia de tipo Siniestro/Lucha.",
                "",
                "Siniestro,Lucha",
                "Lucha,Bicho,Hada,Volador,Psiquico",
                ""));
        listaPokemon.add(new Psiquico("Sigilyph",
                561,
                72,
                58,
                80,
                103,
                80,
                97,
                "Psiquico/Volador",
                "",
                "",
                "",
                "",
                "Sigilyph es un Pokemon originario de Teselia de tipo Psiquico/Volador.",
                "",
                "Psiquico,Volador",
                "Bicho,Fantasma,Siniestro,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Fantasma("Cofagrigus",
                563,
                58,
                50,
                145,
                95,
                105,
                30,
                "Fantasma",
                "",
                "",
                "",
                "",
                "Cofagrigus es un Pokemon originario de Teselia de tipo Fantasma.",
                "",
                "Fantasma",
                "Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Agua("Carracosta",
                565,
                74,
                108,
                133,
                83,
                65,
                32,
                "Agua/Roca",
                "",
                "",
                "",
                "",
                "Carracosta es un Pokemon originario de Teselia de tipo Agua/Roca.",
                "",
                "Agua,Roca",
                "Planta,Electrico,Agua,Lucha,Tierra,Acero",
                ""));
        listaPokemon.add(new Roca("Archeops",
                567,
                75,
                140,
                65,
                112,
                65,
                110,
                "Roca/Volador",
                "",
                "",
                "",
                "",
                "Archeops es un Pokemon originario de Teselia de tipo Roca/Volador.",
                "",
                "Roca,Volador",
                "Agua,Planta,Lucha,Tierra,Acero,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Veneno("Garbodor",
                569,
                80,
                95,
                82,
                60,
                82,
                75,
                "Veneno",
                "",
                "",
                "",
                "",
                "Garbodor es un Pokemon originario de Teselia de tipo Veneno.",
                "",
                "Veneno",
                "Tierra,Psiquico",
                ""));
        listaPokemon.add(new Normal("Zoroark",
                571,
                60,
                105,
                60,
                120,
                60,
                105,
                "Siniestro",
                "",
                "",
                "",
                "",
                "Zoroark es un Pokemon originario de Teselia de tipo Siniestro.",
                "",
                "Siniestro",
                "Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Normal("Cinccino",
                573,
                75,
                95,
                60,
                65,
                60,
                115,
                "Normal",
                "",
                "",
                "",
                "",
                "Cinccino es un Pokemon originario de Teselia de tipo Normal.",
                "",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Psiquico("Gothitelle",
                576,
                70,
                55,
                95,
                95,
                110,
                65,
                "Psiquico",
                "",
                "",
                "",
                "",
                "Gothitelle es un Pokemon originario de Teselia de tipo Psiquico.",
                "",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Psiquico("Reuniclus",
                579,
                110,
                65,
                75,
                125,
                85,
                30,
                "Psiquico",
                "",
                "",
                "",
                "",
                "Reuniclus es un Pokemon originario de Teselia de tipo Psiquico.",
                "",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Agua("Swanna",
                581,
                75,
                87,
                63,
                87,
                63,
                98,
                "Agua/Volador",
                "",
                "",
                "",
                "",
                "Swanna es un Pokemon originario de Teselia de tipo Agua/Volador.",
                "",
                "Agua,Volador",
                "Planta,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Hielo("Vanilluxe",
                584,
                71,
                95,
                85,
                110,
                95,
                79,
                "Hielo",
                "",
                "",
                "",
                "",
                "Vanilluxe es un Pokemon originario de Teselia de tipo Hielo.",
                "",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Normal("Sawsbuck",
                586,
                80,
                100,
                70,
                60,
                70,
                95,
                "Normal/Planta",
                "",
                "",
                "",
                "",
                "Sawsbuck es un Pokemon originario de Teselia de tipo Normal/Planta.",
                "",
                "Normal,Planta",
                "Lucha,Fuego,Volador,Hielo,Bicho,Veneno",
                ""));
        listaPokemon.add(new Electrico("Emolga",
                587,
                55,
                75,
                60,
                75,
                60,
                103,
                "Electrico/Volador",
                "",
                "",
                "",
                "",
                "Emolga es un Pokemon originario de Teselia de tipo Electrico/Volador.",
                "",
                "Electrico,Volador",
                "Tierra,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Bicho("Escavalier",
                589,
                70,
                135,
                105,
                60,
                105,
                20,
                "Bicho/Acero",
                "",
                "",
                "",
                "",
                "Escavalier es un Pokemon originario de Teselia de tipo Bicho/Acero.",
                "",
                "Bicho,Acero",
                "Fuego,Volador,Roca,Lucha,Tierra",
                ""));
        listaPokemon.add(new Planta("Amoonguss",
                591,
                114,
                85,
                70,
                85,
                80,
                30,
                "Planta/Veneno",
                "",
                "",
                "",
                "",
                "Amoonguss es un Pokemon originario de Teselia de tipo Planta/Veneno.",
                "",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Bicho,Veneno,Tierra,Psiquico",
                ""));
        listaPokemon.add(new Agua("Jellicent",
                593,
                100,
                60,
                70,
                85,
                105,
                60,
                "Agua/Fantasma",
                "",
                "",
                "",
                "",
                "Jellicent es un Pokemon originario de Teselia de tipo Agua/Fantasma.",
                "",
                "Agua,Fantasma",
                "Planta,Electrico,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Agua("Alomomola",
                594,
                165,
                75,
                80,
                40,
                45,
                65,
                "Agua",
                "",
                "",
                "",
                "",
                "Alomomola es un Pokemon originario de Teselia de tipo Agua.",
                "",
                "Agua",
                "Planta,Electrico",
                ""));
        listaPokemon.add(new Bicho("Galvantula",
                596,
                70,
                77,
                60,
                97,
                60,
                108,
                "Bicho/Electrico",
                "",
                "",
                "",
                "",
                "Galvantula es un Pokemon originario de Teselia de tipo Bicho/Electrico.",
                "",
                "Bicho,Electrico",
                "Fuego,Volador,Roca,Tierra",
                ""));
        listaPokemon.add(new Planta("Ferrothorn",
                598,
                74,
                94,
                131,
                54,
                116,
                20,
                "Planta/Acero",
                "",
                "",
                "",
                "",
                "Ferrothorn es un Pokemon originario de Teselia de tipo Planta/Acero.",
                "",
                "Planta,Acero",
                "Fuego,Volador,Hielo,Bicho,Veneno,Lucha,Tierra",
                ""));
        listaPokemon.add(new Normal("Klinklang",
                601,
                60,
                100,
                115,
                70,
                85,
                90,
                "Acero",
                "",
                "",
                "",
                "",
                "Klinklang es un Pokemon originario de Teselia de tipo Acero.",
                "",
                "Acero",
                "Fuego,Lucha,Tierra",
                ""));
        listaPokemon.add(new Electrico("Eelektross",
                604,
                85,
                115,
                80,
                105,
                80,
                50,
                "Electrico",
                "",
                "",
                "",
                "",
                "Eelektross es un Pokemon originario de Teselia de tipo Electrico.",
                "",
                "Electrico",
                "Tierra",
                ""));
        listaPokemon.add(new Psiquico("Beheeyem",
                606,
                75,
                75,
                75,
                125,
                95,
                40,
                "Psiquico",
                "",
                "",
                "",
                "",
                "Beheeyem es un Pokemon originario de Teselia de tipo Psiquico.",
                "",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Fantasma("Chandelure",
                609,
                60,
                55,
                90,
                145,
                90,
                80,
                "Fantasma/Fuego",
                "",
                "",
                "",
                "",
                "Chandelure es un Pokemon originario de Teselia de tipo Fantasma/Fuego.",
                "",
                "Fantasma,Fuego",
                "Fantasma,Siniestro,Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Dragon("Haxorus",
                612,
                76,
                147,
                90,
                60,
                70,
                97,
                "Dragon",
                "",
                "",
                "",
                "",
                "Haxorus es un Pokemon originario de Teselia de tipo Dragon.",
                "",
                "Dragon",
                "Hielo,Dragon,Hada",
                ""));
        listaPokemon.add(new Hielo("Beartic",
                614,
                95,
                130,
                80,
                70,
                80,
                50,
                "Hielo",
                "",
                "",
                "",
                "",
                "Beartic es un Pokemon originario de Teselia de tipo Hielo.",
                "",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Hielo("Cryogonal",
                615,
                80,
                50,
                50,
                95,
                135,
                105,
                "Hielo",
                "",
                "",
                "",
                "",
                "Cryogonal es un Pokemon originario de Teselia de tipo Hielo.",
                "",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Bicho("Accelgor",
                617,
                80,
                70,
                40,
                100,
                60,
                145,
                "Bicho",
                "",
                "",
                "",
                "",
                "Accelgor es un Pokemon originario de Teselia de tipo Bicho.",
                "",
                "Bicho",
                "Fuego,Volador,Roca",
                ""));
        listaPokemon.add(new Tierra("Stunfisk",
                618,
                109,
                66,
                84,
                81,
                99,
                32,
                "Tierra/Electrico",
                "",
                "",
                "",
                "",
                "Stunfisk es un Pokemon originario de Teselia de tipo Tierra/Electrico.",
                "",
                "Tierra,Electrico",
                "Agua,Planta,Hielo,Tierra",
                ""));
        listaPokemon.add(new Lucha("Mienshao",
                620,
                65,
                125,
                60,
                95,
                60,
                105,
                "Lucha",
                "",
                "",
                "",
                "",
                "Mienshao es un Pokemon originario de Teselia de tipo Lucha.",
                "",
                "Lucha",
                "Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Dragon("Druddigon",
                621,
                77,
                120,
                90,
                60,
                90,
                48,
                "Dragon",
                "",
                "",
                "",
                "",
                "Druddigon es un Pokemon originario de Teselia de tipo Dragon.",
                "",
                "Dragon",
                "Hielo,Dragon,Hada",
                ""));
        listaPokemon.add(new Tierra("Golurk",
                623,
                89,
                124,
                80,
                55,
                80,
                55,
                "Tierra/Fantasma",
                "",
                "",
                "",
                "",
                "Golurk es un Pokemon originario de Teselia de tipo Tierra/Fantasma.",
                "",
                "Tierra,Fantasma",
                "Agua,Planta,Hielo,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Normal("Bisharp",
                625,
                65,
                125,
                100,
                60,
                70,
                70,
                "Siniestro/Acero",
                "",
                "",
                "",
                "",
                "Bisharp es un Pokemon originario de Teselia de tipo Siniestro/Acero.",
                "",
                "Siniestro,Acero",
                "Lucha,Bicho,Hada,Fuego,Tierra",
                ""));
        listaPokemon.add(new Normal("Bouffalant",
                626,
                95,
                110,
                95,
                40,
                95,
                55,
                "Normal",
                "",
                "",
                "",
                "",
                "Bouffalant es un Pokemon originario de Teselia de tipo Normal.",
                "",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Normal("Braviary",
                628,
                100,
                123,
                75,
                57,
                75,
                80,
                "Normal/Volador",
                "",
                "",
                "",
                "",
                "Braviary es un Pokemon originario de Teselia de tipo Normal/Volador.",
                "",
                "Normal,Volador",
                "Lucha,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Normal("Mandibuzz",
                630,
                110,
                65,
                105,
                55,
                95,
                80,
                "Siniestro/Volador",
                "",
                "",
                "",
                "",
                "Mandibuzz es un Pokemon originario de Teselia de tipo Siniestro/Volador.",
                "",
                "Siniestro,Volador",
                "Lucha,Bicho,Hada,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Fuego("Heatmor",
                631,
                85,
                97,
                66,
                105,
                66,
                65,
                "Fuego",
                "",
                "",
                "",
                "",
                "Heatmor es un Pokemon originario de Teselia de tipo Fuego.",
                "",
                "Fuego",
                "Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Bicho("Durant",
                632,
                58,
                109,
                112,
                48,
                48,
                109,
                "Bicho/Acero",
                "",
                "",
                "",
                "",
                "Durant es un Pokemon originario de Teselia de tipo Bicho/Acero.",
                "",
                "Bicho,Acero",
                "Fuego,Volador,Roca,Lucha,Tierra",
                ""));
        listaPokemon.add(new Normal("Hydreigon",
                635,
                92,
                105,
                90,
                125,
                90,
                98,
                "Siniestro/Dragon",
                "",
                "",
                "",
                "",
                "Hydreigon es un Pokemon originario de Teselia de tipo Siniestro/Dragon.",
                "",
                "Siniestro,Dragon",
                "Lucha,Bicho,Hada,Hielo,Dragon",
                ""));
        listaPokemon.add(new Bicho("Volcarona",
                637,
                85,
                60,
                65,
                135,
                105,
                100,
                "Bicho/Fuego",
                "",
                "",
                "",
                "",
                "Volcarona es un Pokemon originario de Teselia de tipo Bicho/Fuego.",
                "",
                "Bicho,Fuego",
                "Fuego,Volador,Roca,Agua,Tierra",
                ""));
        listaPokemon.add(new Normal("Cobalion",
                638,
                91,
                90,
                129,
                90,
                72,
                108,
                "Acero/Lucha",
                "",
                "",
                "",
                "",
                "Cobalion es un Pokemon originario de Teselia de tipo Acero/Lucha.",
                "",
                "Acero,Lucha",
                "Fuego,Lucha,Tierra,Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Roca("Terrakion",
                639,
                91,
                129,
                90,
                72,
                90,
                108,
                "Roca/Lucha",
                "",
                "",
                "",
                "",
                "Terrakion es un Pokemon originario de Teselia de tipo Roca/Lucha.",
                "",
                "Roca,Lucha",
                "Agua,Planta,Lucha,Tierra,Acero,Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Planta("Virizion",
                640,
                91,
                90,
                72,
                90,
                129,
                108,
                "Planta/Lucha",
                "",
                "",
                "",
                "",
                "Virizion es un Pokemon originario de Teselia de tipo Planta/Lucha.",
                "",
                "Planta,Lucha",
                "Fuego,Volador,Hielo,Bicho,Veneno,Psiquico,Hada",
                ""));
        listaPokemon.add(new Volador("Tornadus",
                641,
                79,
                115,
                70,
                125,
                80,
                111,
                "Volador",
                "",
                "",
                "",
                "",
                "Tornadus es un Pokemon originario de Teselia de tipo Volador.",
                "",
                "Volador",
                "Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Electrico("Thundurus",
                642,
                79,
                115,
                70,
                125,
                80,
                111,
                "Electrico/Volador",
                "",
                "",
                "",
                "",
                "Thundurus es un Pokemon originario de Teselia de tipo Electrico/Volador.",
                "",
                "Electrico,Volador",
                "Tierra,Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Dragon("Reshiram",
                643,
                100,
                120,
                100,
                150,
                120,
                90,
                "Dragon/Fuego",
                "",
                "",
                "",
                "",
                "Reshiram es un Pokemon originario de Teselia de tipo Dragon/Fuego.",
                "",
                "Dragon,Fuego",
                "Hielo,Dragon,Hada,Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Dragon("Zekrom",
                644,
                100,
                150,
                120,
                120,
                100,
                90,
                "Dragon/Electrico",
                "",
                "",
                "",
                "",
                "Zekrom es un Pokemon originario de Teselia de tipo Dragon/Electrico.",
                "",
                "Dragon,Electrico",
                "Hielo,Dragon,Hada,Tierra",
                ""));
        listaPokemon.add(new Tierra("Landorus",
                645,
                89,
                125,
                90,
                115,
                80,
                101,
                "Tierra/Volador",
                "",
                "",
                "",
                "",
                "Landorus es un Pokemon originario de Teselia de tipo Tierra/Volador.",
                "",
                "Tierra,Volador",
                "Agua,Planta,Hielo,Electrico,Roca",
                ""));
        listaPokemon.add(new Dragon("Kyurem",
                646,
                125,
                130,
                90,
                130,
                90,
                95,
                "Dragon/Hielo",
                "",
                "",
                "",
                "",
                "Kyurem es un Pokemon originario de Teselia de tipo Dragon/Hielo.",
                "",
                "Dragon,Hielo",
                "Hielo,Dragon,Hada,Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Agua("Keldeo",
                647,
                91,
                72,
                90,
                129,
                90,
                108,
                "Agua/Lucha",
                "",
                "",
                "",
                "",
                "Keldeo es un Pokemon originario de Teselia de tipo Agua/Lucha.",
                "",
                "Agua,Lucha",
                "Planta,Electrico,Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Normal("Meloetta",
                648,
                100,
                77,
                77,
                128,
                128,
                90,
                "Normal/Psiquico",
                "",
                "",
                "",
                "",
                "Meloetta es un Pokemon originario de Teselia de tipo Normal/Psiquico.",
                "",
                "Normal,Psiquico",
                "Lucha,Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Bicho("Genesect",
                649,
                71,
                120,
                95,
                120,
                95,
                99,
                "Bicho/Acero",
                "",
                "",
                "",
                "",
                "Genesect es un Pokemon originario de Teselia de tipo Bicho/Acero.",
                "",
                "Bicho,Acero",
                "Fuego,Volador,Roca,Lucha,Tierra",
                ""));

        return listaPokemon;
    }
}
