package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexJohtoRepository {

    public static List<Pokemon> obtenerListaPokemon(){
        List<Pokemon> listaPokemon = new ArrayList<>();

        listaPokemon.add(new Planta("Chikorita",
                152,
                45,
                49,
                65,
                49,
                65,
                45,
                "Planta",
                "0,9",
                "Hoja",
                "6,4",
                "Espesura",
                "La hoja de su cabeza desprende un agradable aroma y le permite percibir la temperatura y humedad del entorno.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\152.jpg"));
        listaPokemon.add(new Planta("Bayleef",
                153,
                60,
                62,
                80,
                63,
                80,
                60,
                "Planta",
                "1,2",
                "Hoja",
                "15,8",
                "Espesura",
                "Las hojas alrededor de su cuello desprenden un aroma que estimula y llena de energía a quienes lo perciben.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\153.jpg"));
        listaPokemon.add(new Planta("Meganium",
                154,
                80,
                82,
                100,
                83,
                100,
                80,
                "Planta",
                "1,8",
                "Hierba",
                "100,5",
                "Espesura",
                "El aroma de sus pétalos tiene un efecto tranquilizador y se dice que puede devolver vitalidad a las plantas.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\154.jpg"));
        listaPokemon.add(new Fuego("Cyndaquil",
                155,
                39,
                52,
                43,
                60,
                50,
                65,
                "Fuego",
                "0,5",
                "Ratón Fuego",
                "7,9",
                "Mar Llamas",
                "Es tímido y suele encogerse cuando se asusta, haciendo brotar llamas de su espalda para protegerse.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\155.jpg"));
        listaPokemon.add(new Fuego("Quilava",
                156,
                58,
                64,
                58,
                80,
                65,
                80,
                "Fuego",
                "0,9",
                "Volcán",
                "19,0",
                "Mar Llamas",
                "Su cuerpo es ágil y puede esquivar ataques mientras utiliza las llamas de su cabeza y espalda para combatir.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\156.jpg"));
        listaPokemon.add(new Fuego("Typhlosion",
                157,
                78,
                84,
                78,
                109,
                85,
                100,
                "Fuego",
                "1,7",
                "Volcán",
                "79,5",
                "Mar Llamas",
                "Cuando se enfurece genera un calor intenso y puede crear grandes explosiones utilizando sus poderosas llamas.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\157.jpg"));
        listaPokemon.add(new Agua("Totodile",
                158,
                50,
                65,
                64,
                44,
                48,
                43,
                "Agua",
                "0,6",
                "Fauces Grandes",
                "9,5",
                "Torrente",
                "Tiene unas mandíbulas muy fuertes y puede morder cualquier cosa que se mueva cerca de él.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\158.jpg"));
        listaPokemon.add(new Agua("Croconaw",
                159,
                65,
                80,
                80,
                59,
                63,
                58,
                "Agua",
                "1,1",
                "Fauces Grandes",
                "25,0",
                "Torrente",
                "Sus colmillos están orientados hacia atrás, haciendo muy difícil que una presa pueda escapar después de ser mordida.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\159.jpg"));
        listaPokemon.add(new Agua("Feraligatr",
                160,
                85,
                105,
                100,
                79,
                83,
                78,
                "Agua",
                "2,3",
                "Fauces Grandes",
                "88,8",
                "Torrente",
                "Intimida a sus rivales abriendo sus enormes mandíbulas y después se lanza contra ellos con gran velocidad.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\160.jpg"));
        listaPokemon.add(new Normal("Sentret",
                161,
                35,
                46,
                34,
                35,
                45,
                20,
                "Normal",
                "0,8",
                "Explorador",
                "6,0",
                "Fuga,Vista Lince",
                "Se mantiene erguido sobre su cola para observar los alrededores y avisar a sus compañeros cuando detecta peligro.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\161.jpg"));
        listaPokemon.add(new Normal("Furret",
                162,
                85,
                76,
                64,
                45,
                55,
                90,
                "Normal",
                "1,8",
                "Cuerpo Largo",
                "32,5",
                "Fuga,Vista Lince",
                "Su cuerpo largo y flexible le permite desplazarse rápidamente por estrechos túneles y perseguir a sus presas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\162.jpg"));
        listaPokemon.add(new Normal("Hoothoot",
                163,
                60,
                30,
                30,
                36,
                56,
                50,
                "Normal/Volador",
                "0,7",
                "Búho",
                "21,2",
                "Insomnio,Vista Lince",
                "Posee un sentido del tiempo extraordinario y suele emitir sus sonidos todos los días exactamente a la misma hora.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\163.jpg"));
        listaPokemon.add(new Normal("Noctowl",
                164,
                100,
                50,
                50,
                86,
                96,
                70,
                "Normal/Volador",
                "1,6",
                "Búho",
                "40,8",
                "Insomnio,Vista Lince",
                "Sus ojos están especialmente adaptados para ver en la oscuridad, permitiéndole cazar incluso durante noches sin luna.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\164.jpg"));
        listaPokemon.add(new Bicho("Ledyba",
                165,
                40,
                20,
                30,
                40,
                80,
                55,
                "Bicho/Volador",
                "1,0",
                "Cinco Estrellas",
                "10,8",
                "Enjambre,Madrugar",
                "Es muy sociable y suele reunirse en grandes grupos, comunicándose con otros mediante los fluidos que libera.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Volador,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\165.jpg"));
        listaPokemon.add(new Bicho("Ledian",
                166,
                55,
                35,
                50,
                55,
                110,
                85,
                "Bicho/Volador",
                "1,4",
                "Cinco Estrellas",
                "35,6",
                "Enjambre,Madrugar",
                "Durante las noches estrelladas vuela por el cielo y utiliza la luz de las estrellas como fuente de energía.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Volador,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\166.jpg"));
        listaPokemon.add(new Bicho("Spinarak",
                167,
                40,
                60,
                40,
                40,
                40,
                30,
                "Bicho/Veneno",
                "0,5",
                "Escupehilo",
                "8,5",
                "Enjambre,Insomnio",
                "Construye resistentes telarañas y espera pacientemente durante horas hasta que alguna presa queda atrapada.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\167.jpg"));
        listaPokemon.add(new Bicho("Ariados",
                168,
                70,
                90,
                70,
                60,
                70,
                40,
                "Bicho/Veneno",
                "1,1",
                "Pata Larga",
                "33,5",
                "Enjambre,Insomnio",
                "Puede producir hilo tanto por la boca como por el abdomen y lo utiliza para inmovilizar a sus enemigos.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\168.jpg"));
        listaPokemon.add(new Veneno("Crobat",
                169,
                85,
                90,
                80,
                70,
                80,
                130,
                "Veneno/Volador",
                "1,8",
                "Murciélago",
                "75,0",
                "Foco Interno",
                "Sus cuatro alas le permiten volar durante mucho tiempo y cambiar rápidamente de dirección sin perder velocidad.",
                "♀/♂",
                "Veneno,Volador",
                "Electrico,Hielo,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\169.jpg"));
        listaPokemon.add(new Agua("Chinchou",
                170,
                75,
                38,
                38,
                56,
                56,
                67,
                "Agua/Electrico",
                "0,5",
                "Rape",
                "12,0",
                "Absorbe Electricidad,Iluminacion",
                "Vive en las profundidades marinas y utiliza las antenas de su cabeza para producir luz y atraer a sus presas.",
                "♀/♂",
                "Agua,Electrico",
                "Planta,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\170.jpg"));
        listaPokemon.add(new Agua("Lanturn",
                171,
                125,
                58,
                58,
                76,
                76,
                67,
                "Agua/Electrico",
                "1,2",
                "Luz",
                "22,5",
                "Absorbe Electricidad,Iluminacion",
                "La intensa luz que produce puede verse desde la superficie incluso cuando nada a grandes profundidades.",
                "♀/♂",
                "Agua,Electrico",
                "Planta,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\171.jpg"));
        listaPokemon.add(new Electrico("Pichu",
                172,
                20,
                40,
                15,
                35,
                35,
                60,
                "Electrico",
                "0,3",
                "Ratoncito",
                "2,0",
                "Electricidad Estatica",
                "Todavía no controla bien la electricidad de sus mejillas y puede producir descargas cuando se emociona o se asusta.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\172.jpg"));
        listaPokemon.add(new Normal("Cleffa",
                173,
                50,
                25,
                28,
                45,
                55,
                15,
                "Hada",
                "0,3",
                "Estrella",
                "3,0",
                "Gran Encanto,Muro Magico",
                "Su silueta recuerda a una estrella y suele aparecer durante noches despejadas en lugares donde caen meteoritos.",
                "♀/♂",
                "Hada",
                "Veneno,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\173.jpg"));
        listaPokemon.add(new Normal("Igglybuff",
                174,
                90,
                30,
                15,
                40,
                20,
                15,
                "Normal/Hada",
                "0,3",
                "Globo",
                "1,0",
                "Gran Encanto,Tenacidad",
                "Su cuerpo es extremadamente suave y elástico, por lo que puede rebotar fácilmente cuando empieza a moverse.",
                "♀/♂",
                "Normal,Hada",
                "Veneno,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\174.jpg"));
        listaPokemon.add(new Normal("Togepi",
                175,
                35,
                20,
                65,
                40,
                65,
                20,
                "Hada",
                "0,3",
                "Bolita",
                "1,5",
                "Entusiasmo,Dicha",
                "Almacena sentimientos positivos dentro de su cascarón y comparte esa energía con las personas que lo tratan bien.",
                "♀/♂",
                "Hada",
                "Veneno,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\175.jpg"));
        listaPokemon.add(new Normal("Togetic",
                176,
                55,
                40,
                85,
                80,
                105,
                40,
                "Hada/Volador",
                "0,6",
                "Felicidad",
                "3,2",
                "Entusiasmo,Dicha",
                "Se dice que aparece ante personas de buen corazón para compartir con ellas felicidad y energía positiva.",
                "♀/♂",
                "Hada,Volador",
                "Electrico,Hielo,Veneno,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\176.jpg"));
        listaPokemon.add(new Psiquico("Natu",
                177,
                40,
                50,
                45,
                70,
                45,
                70,
                "Psiquico/Volador",
                "0,2",
                "Pajarito",
                "2,0",
                "Sincronia,Madrugar",
                "Aunque sus alas todavía no le permiten volar bien, puede saltar con gran habilidad para desplazarse y buscar alimento.",
                "♀/♂",
                "Psiquico,Volador",
                "Electrico,Hielo,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\177.jpg"));
        listaPokemon.add(new Psiquico("Xatu",
                178,
                65,
                75,
                70,
                95,
                70,
                95,
                "Psiquico/Volador",
                "1,5",
                "Místico",
                "15,0",
                "Sincronia,Madrugar",
                "Permanece inmóvil durante largos periodos y se dice que puede observar acontecimientos del pasado y del futuro.",
                "♀/♂",
                "Psiquico,Volador",
                "Electrico,Hielo,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\178.jpg"));
        listaPokemon.add(new Electrico("Mareep",
                179,
                55,
                40,
                40,
                65,
                45,
                35,
                "Electrico",
                "0,6",
                "Lana",
                "7,8",
                "Electricidad Estatica",
                "Su lana acumula electricidad estática y aumenta de volumen cuanto mayor es la carga eléctrica almacenada.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\179.jpg"));
        listaPokemon.add(new Electrico("Flaaffy",
                180,
                70,
                55,
                55,
                80,
                60,
                45,
                "Electrico",
                "0,8",
                "Lana",
                "13,3",
                "Electricidad Estatica",
                "Su piel puede almacenar electricidad sin sufrir daños y la esfera de su cola brilla cuando acumula suficiente energía.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\180.jpg"));
        listaPokemon.add(new Electrico("Ampharos",
                181,
                90,
                75,
                85,
                115,
                90,
                55,
                "Electrico",
                "1,4",
                "Luz",
                "61,5",
                "Electricidad Estatica",
                "La esfera de su cola produce una luz tan intensa que antiguamente se utilizaba como señal para orientar a los viajeros.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\181.jpg"));
        listaPokemon.add(new Planta("Bellossom",
                182,
                75,
                80,
                95,
                90,
                100,
                50,
                "Planta",
                "0,4",
                "Flor",
                "5,8",
                "Clorofila",
                "Cuando recibe abundante luz solar gira y baila mientras sus flores desprenden un agradable aroma.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\182.jpg"));
        listaPokemon.add(new Agua("Marill",
                183,
                70,
                20,
                50,
                20,
                50,
                40,
                "Agua/Hada",
                "0,4",
                "Ratón Agua",
                "8,5",
                "Sebo,Potencia",
                "Su cola contiene un aceite especial que funciona como flotador y le permite nadar sin dificultad.",
                "♀/♂",
                "Agua,Hada",
                "Planta,Electrico,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\183.jpg"));
        listaPokemon.add(new Agua("Azumarill",
                184,
                100,
                50,
                80,
                60,
                80,
                50,
                "Agua/Hada",
                "0,8",
                "Conejo Agua",
                "28,5",
                "Sebo,Potencia",
                "Sus grandes orejas detectan sonidos incluso bajo el agua y le ayudan a localizar movimientos a gran distancia.",
                "♀/♂",
                "Agua,Hada",
                "Planta,Electrico,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\184.jpg"));
        listaPokemon.add(new Roca("Sudowoodo",
                185,
                70,
                100,
                115,
                30,
                65,
                30,
                "Roca",
                "1,2",
                "Imitación",
                "38,0",
                "Robustez,Cabeza Roca",
                "Imita la apariencia de un árbol para evitar ataques, aunque su cuerpo rocoso no tolera demasiado bien el agua.",
                "♀/♂",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\185.jpg"));
        listaPokemon.add(new Agua("Politoed",
                186,
                90,
                75,
                75,
                90,
                100,
                70,
                "Agua",
                "1,1",
                "Rana",
                "33,9",
                "Absorbe Agua,Humedad",
                "Emite fuertes sonidos para reunir a otros Pokémon de su especie y parece actuar como líder de los grupos.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\186.jpg"));
        listaPokemon.add(new Planta("Hoppip",
                187,
                35,
                35,
                40,
                35,
                55,
                50,
                "Planta/Volador",
                "0,4",
                "Diente León",
                "0,5",
                "Clorofila,Defensa Hoja",
                "Su cuerpo es tan ligero que incluso una pequeña corriente de aire puede levantarlo y transportarlo a otro lugar.",
                "♀/♂",
                "Planta,Volador",
                "Fuego,Volador,Hielo,Veneno,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\187.jpg"));
        listaPokemon.add(new Planta("Skiploom",
                188,
                55,
                45,
                50,
                45,
                65,
                80,
                "Planta/Volador",
                "0,6",
                "Algodón",
                "1,0",
                "Clorofila,Defensa Hoja",
                "La flor de su cabeza se abre con la temperatura adecuada y utiliza las corrientes de aire para desplazarse.",
                "♀/♂",
                "Planta,Volador",
                "Fuego,Volador,Hielo,Veneno,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\188.jpg"));
        listaPokemon.add(new Planta("Jumpluff",
                189,
                75,
                55,
                70,
                55,
                95,
                110,
                "Planta/Volador",
                "0,8",
                "Algodón",
                "3,0",
                "Clorofila,Defensa Hoja",
                "Puede viajar grandes distancias transportado por el viento mientras esparce pequeñas semillas por donde pasa.",
                "♀/♂",
                "Planta,Volador",
                "Fuego,Volador,Hielo,Veneno,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\189.jpg"));
        listaPokemon.add(new Normal("Aipom",
                190,
                55,
                70,
                55,
                40,
                55,
                85,
                "Normal",
                "0,8",
                "Cola Larga",
                "11,5",
                "Fuga,Recogida",
                "Utiliza la mano de su cola con tanta frecuencia que sus brazos normales han perdido parte de su destreza.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\190.jpg"));
        listaPokemon.add(new Planta("Sunkern",
                191,
                30,
                30,
                30,
                30,
                30,
                30,
                "Planta",
                "0,3",
                "Semilla",
                "1,8",
                "Clorofila,Poder Solar",
                "Permanece casi inmóvil mientras almacena nutrientes para prepararse antes de evolucionar.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\191.jpg"));
        listaPokemon.add(new Planta("Sunflora",
                192,
                75,
                75,
                55,
                105,
                85,
                30,
                "Planta",
                "0,8",
                "Sol",
                "8,5",
                "Clorofila,Poder Solar",
                "Convierte la luz solar en energía y se vuelve especialmente activo durante las horas de mayor intensidad del sol.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\192.jpg"));
        listaPokemon.add(new Bicho("Yanma",
                193,
                65,
                65,
                45,
                75,
                45,
                95,
                "Bicho/Volador",
                "1,2",
                "Ala Clara",
                "38,0",
                "Impulso,Ojo Compuesto",
                "Puede mover sus ojos de manera independiente y observar prácticamente todas las direcciones sin mover la cabeza.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Volador,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\193.jpg"));
        listaPokemon.add(new Agua("Wooper",
                194,
                55,
                45,
                45,
                25,
                25,
                15,
                "Agua/Tierra",
                "0,4",
                "Pez Agua",
                "8,5",
                "Humedad,Absorbe Agua",
                "Cuando sale del agua cubre su cuerpo con una sustancia húmeda que evita que su piel se reseque.",
                "♀/♂",
                "Agua,Tierra",
                "Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\194.jpg"));
        listaPokemon.add(new Agua("Quagsire",
                195,
                95,
                85,
                85,
                65,
                65,
                35,
                "Agua/Tierra",
                "1,4",
                "Pez Agua",
                "75,0",
                "Humedad,Absorbe Agua",
                "Nada tranquilamente sin preocuparse demasiado por los obstáculos y suele llevar una vida relajada en ríos y lagos.",
                "♀/♂",
                "Agua,Tierra",
                "Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\195.jpg"));
        listaPokemon.add(new Psiquico("Espeon",
                196,
                65,
                65,
                60,
                130,
                95,
                110,
                "Psiquico",
                "0,9",
                "Sol",
                "26,5",
                "Sincronia",
                "Percibe pequeñas corrientes de aire con su fino pelaje y utiliza esa información para anticipar los movimientos enemigos.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\196.jpg"));
        listaPokemon.add(new Normal("Umbreon",
                197,
                95,
                65,
                110,
                60,
                130,
                65,
                "Siniestro",
                "1,0",
                "Luz Lunar",
                "27,0",
                "Sincronia",
                "Los anillos de su cuerpo brillan durante la noche y se vuelven más intensos cuando está preparado para atacar.",
                "♀/♂",
                "Siniestro",
                "Lucha,Bicho,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\197.jpg"));
        listaPokemon.add(new Normal("Murkrow",
                198,
                60,
                85,
                42,
                85,
                42,
                91,
                "Siniestro/Volador",
                "0,5",
                "Oscuridad",
                "2,1",
                "Insomnio,Afortunado",
                "Suele sentirse atraído por objetos brillantes y los recoge para esconderlos en lugares difíciles de encontrar.",
                "♀/♂",
                "Siniestro,Volador",
                "Electrico,Hielo,Roca,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\198.jpg"));
        listaPokemon.add(new Agua("Slowking",
                199,
                95,
                75,
                80,
                100,
                110,
                30,
                "Agua/Psiquico",
                "2,0",
                "Real",
                "79,5",
                "Despiste,Ritmo Propio",
                "La influencia del Shellder de su cabeza le otorgó una gran inteligencia y una extraordinaria capacidad de razonamiento.",
                "♀/♂",
                "Agua,Psiquico",
                "Planta,Electrico,Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\199.jpg"));
        listaPokemon.add(new Fantasma("Misdreavus",
                200,
                60,
                60,
                60,
                85,
                85,
                85,
                "Fantasma",
                "0,7",
                "Chirrido",
                "1,0",
                "Levitacion",
                "Disfruta sorprendiendo a las personas durante la noche y obtiene energía de las emociones que provoca con sus sustos.",
                "♀/♂",
                "Fantasma",
                "Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\200.jpg"));
        listaPokemon.add(new Psiquico("Unown",
                201,
                48,
                72,
                48,
                72,
                48,
                48,
                "Psiquico",
                "0,5",
                "Símbolo",
                "5,0",
                "Levitacion",
                "Su cuerpo tiene la forma de antiguos símbolos y su poder parece aumentar cuando varios ejemplares se reúnen.",
                "Sin genero",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\201.jpg"));
        listaPokemon.add(new Psiquico("Wobbuffet",
                202,
                190,
                33,
                58,
                33,
                58,
                33,
                "Psiquico",
                "1,3",
                "Paciente",
                "28,5",
                "Sombra Trampa",
                "Evita atacar directamente y prefiere soportar los golpes para devolverlos con una fuerza todavía mayor.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\202.jpg"));
        listaPokemon.add(new Normal("Girafarig",
                203,
                70,
                80,
                65,
                90,
                65,
                85,
                "Normal/Psiquico",
                "1,5",
                "Gran Cuello",
                "41,5",
                "Foco Interno,Madrugar",
                "La cabeza de su cola posee un pequeño cerebro propio y puede reaccionar ante amenazas incluso sin recibir órdenes.",
                "♀/♂",
                "Normal,Psiquico",
                "Bicho,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\203.jpg"));
        listaPokemon.add(new Bicho("Pineco",
                204,
                50,
                65,
                90,
                35,
                35,
                15,
                "Bicho",
                "0,6",
                "Larva",
                "7,2",
                "Robustez",
                "Se cuelga de las ramas de los árboles y añade capas de corteza a su cuerpo para protegerse.",
                "♀/♂",
                "Bicho",
                "Fuego,Volador,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\204..jpg"));
        listaPokemon.add(new Bicho("Forretress",
                205,
                75,
                90,
                140,
                60,
                60,
                40,
                "Bicho/Acero",
                "1,2",
                "Larva",
                "125,8",
                "Robustez",
                "Su cuerpo está protegido por una resistente coraza de acero que mantiene cerrada casi todo el tiempo.",
                "♀/♂",
                "Bicho,Acero",
                "Fuego",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\205.jpg"));
        listaPokemon.add(new Normal("Dunsparce",
                206,
                100,
                70,
                70,
                65,
                65,
                45,
                "Normal",
                "1,5",
                "Serpiente Tierra",
                "14,0",
                "Fuga,Dicha",
                "Utiliza su cola para excavar túneles y sus pequeñas alas para desplazarse rápidamente bajo tierra.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\206.jpg"));
        listaPokemon.add(new Tierra("Gligar",
                207,
                65,
                75,
                105,
                35,
                65,
                85,
                "Tierra/Volador",
                "1,1",
                "Escorpiala",
                "64,8",
                "Corte Fuerte,Velo Arena",
                "Planea silenciosamente utilizando las corrientes de aire y ataca a sus presas con sus grandes pinzas.",
                "♀/♂",
                "Tierra,Volador",
                "Agua,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\207.jpg"));
        listaPokemon.add(new Normal("Steelix",
                208,
                75,
                85,
                200,
                55,
                65,
                30,
                "Acero/Tierra",
                "9,2",
                "Serpiente Férrea",
                "400,0",
                "Cabeza Roca,Robustez",
                "Su cuerpo se endureció bajo tierra hasta alcanzar una resistencia superior a la de muchos metales.",
                "♀/♂",
                "Acero,Tierra",
                "Fuego,Agua,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\208.jpg"));
        listaPokemon.add(new Normal("Snubbull",
                209,
                60,
                80,
                50,
                40,
                40,
                30,
                "Hada",
                "0,6",
                "Hada",
                "7,8",
                "Intimidacion,Fuga",
                "Aunque su expresión parece amenazante, suele ser cariñoso y utiliza su aspecto para ahuyentar a posibles enemigos.",
                "♀/♂",
                "Hada",
                "Veneno,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\209.jpg"));
        listaPokemon.add(new Normal("Granbull",
                210,
                90,
                120,
                75,
                60,
                60,
                45,
                "Hada",
                "1,4",
                "Hada",
                "48,7",
                "Intimidacion,Pies Rapidos",
                "Posee enormes colmillos y una poderosa mandíbula, aunque normalmente evita combatir si no es necesario.",
                "♀/♂",
                "Hada",
                "Veneno,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\210.jpg"));
        listaPokemon.add(new Agua("Qwilfish",
                211,
                65,
                95,
                85,
                55,
                55,
                85,
                "Agua/Veneno",
                "0,5",
                "Globo",
                "3,9",
                "Punto Toxico,Nado Rapido",
                "Absorbe agua para inflar su cuerpo y después dispara sus púas venenosas contra cualquier amenaza.",
                "♀/♂",
                "Agua,Veneno",
                "Electrico,Tierra,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\211.jpg"));
        listaPokemon.add(new Bicho("Scizor",
                212,
                70,
                130,
                100,
                55,
                80,
                65,
                "Bicho/Acero",
                "1,8",
                "Tenaza",
                "118,0",
                "Enjambre,Experto",
                "Su cuerpo metálico es muy resistente y utiliza sus grandes pinzas para intimidar y atacar a sus rivales.",
                "♀/♂",
                "Bicho,Acero",
                "Fuego",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\212.jpg"));
        listaPokemon.add(new Bicho("Shuckle",
                213,
                20,
                10,
                230,
                10,
                230,
                5,
                "Bicho/Roca",
                "0,6",
                "Moho",
                "20,5",
                "Robustez,Gula",
                "Se esconde dentro de su resistente caparazón y almacena bayas en él hasta convertirlas en un líquido nutritivo.",
                "♀/♂",
                "Bicho,Roca",
                "Agua,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\213.jpg"));
        listaPokemon.add(new Bicho("Heracross",
                214,
                80,
                125,
                75,
                40,
                95,
                85,
                "Bicho/Lucha",
                "1,5",
                "Unicornio",
                "54,0",
                "Enjambre,Agallas",
                "Utiliza su enorme cuerno para levantar y lanzar objetos que pesan muchas veces más que su propio cuerpo.",
                "♀/♂",
                "Bicho,Lucha",
                "Fuego,Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\214.jpg"));
        listaPokemon.add(new Normal("Sneasel",
                215,
                55,
                95,
                55,
                35,
                75,
                115,
                "Siniestro/Hielo",
                "0,9",
                "Garra Filo",
                "28,0",
                "Foco Interno,Vista Lince",
                "Se mueve silenciosamente y utiliza sus afiladas garras para trepar árboles y sorprender a sus presas.",
                "♀/♂",
                "Siniestro,Hielo",
                "Fuego,Lucha,Bicho,Roca,Acero,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\215.jpg"));
        listaPokemon.add(new Normal("Teddiursa",
                216,
                60,
                80,
                50,
                50,
                50,
                40,
                "Normal",
                "0,6",
                "Osito",
                "8,8",
                "Recogida,Pies Rapidos",
                "Le encanta la miel y suele buscarla utilizando el sensible olfato que posee en sus pequeñas patas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\216.jpg"));
        listaPokemon.add(new Normal("Ursaring",
                217,
                90,
                130,
                75,
                75,
                75,
                55,
                "Normal",
                "1,8",
                "Hibernante",
                "125,8",
                "Agallas,Pies Rapidos",
                "Marca los árboles de su territorio y posee una gran habilidad para encontrar alimentos escondidos en los bosques.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\217.jpg"));
        listaPokemon.add(new Fuego("Slugma",
                218,
                40,
                40,
                40,
                70,
                40,
                20,
                "Fuego",
                "0,7",
                "Lava",
                "35,0",
                "Escudo Magma,Cuerpo Llama",
                "Su cuerpo está formado por magma y debe mantenerse en movimiento para evitar que se enfríe y endurezca.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\218.jpg"));
        listaPokemon.add(new Fuego("Magcargo",
                219,
                60,
                50,
                120,
                90,
                80,
                30,
                "Fuego/Roca",
                "0,8",
                "Lava",
                "55,0",
                "Escudo Magma,Cuerpo Llama",
                "La roca de su espalda se formó al enfriarse parte de su cuerpo de magma y puede romperse con fuertes impactos.",
                "♀/♂",
                "Fuego,Roca",
                "Agua,Lucha,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\219.jpg"));
        listaPokemon.add(new Hielo("Swinub",
                220,
                50,
                50,
                40,
                30,
                30,
                50,
                "Hielo/Tierra",
                "0,4",
                "Cerdo",
                "6,5",
                "Despiste,Manto Niveo",
                "Utiliza su sensible hocico para localizar comida enterrada incluso bajo gruesas capas de nieve.",
                "♀/♂",
                "Hielo,Tierra",
                "Fuego,Agua,Planta,Lucha,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\220.jpg"));
        listaPokemon.add(new Hielo("Piloswine",
                221,
                100,
                100,
                80,
                60,
                60,
                50,
                "Hielo/Tierra",
                "1,1",
                "Puerco",
                "55,8",
                "Despiste,Manto Niveo",
                "Su largo pelaje lo protege del frío extremo y avanza guiándose principalmente por su excelente sentido del olfato.",
                "♀/♂",
                "Hielo,Tierra",
                "Fuego,Agua,Planta,Lucha,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\221.jpg"));
        listaPokemon.add(new Agua("Corsola",
                222,
                65,
                55,
                95,
                65,
                95,
                35,
                "Agua/Roca",
                "0,6",
                "Coral",
                "5,0",
                "Cura Natural,Entusiasmo",
                "Habita en mares cálidos y sus ramas crecen sanas cuando vive en aguas limpias y llenas de nutrientes.",
                "♀/♂",
                "Agua,Roca",
                "Planta,Electrico,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\222.jpg"));
        listaPokemon.add(new Agua("Remoraid",
                223,
                35,
                65,
                35,
                65,
                35,
                65,
                "Agua",
                "0,6",
                "Reactor",
                "12,0",
                "Entusiasmo,Francotirador",
                "Dispara chorros de agua con gran precisión y puede acertar a objetivos que se encuentran a considerable distancia.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\223.jpg"));
        listaPokemon.add(new Agua("Octillery",
                224,
                75,
                105,
                75,
                105,
                75,
                45,
                "Agua",
                "0,9",
                "Reactor",
                "28,5",
                "Ventosas,Francotirador",
                "Se esconde entre las rocas y utiliza sus fuertes tentáculos y chorros de tinta para defender su territorio.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\224.jpg"));
        listaPokemon.add(new Hielo("Delibird",
                225,
                45,
                55,
                45,
                65,
                45,
                75,
                "Hielo/Volador",
                "0,9",
                "Reparto",
                "16,0",
                "Espiritu Vital,Entusiasmo",
                "Transporta comida en su cola y la comparte con viajeros o Pokémon que encuentra perdidos en las montañas.",
                "♀/♂",
                "Hielo,Volador",
                "Fuego,Electrico,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\225.jpg"));
        listaPokemon.add(new Agua("Mantine",
                226,
                85,
                40,
                70,
                80,
                140,
                70,
                "Agua/Volador",
                "2,1",
                "Milano",
                "220,0",
                "Nado Rapido,Absorbe Agua",
                "Nada tranquilamente por el océano y puede saltar fuera del agua para planear durante algunos instantes.",
                "♀/♂",
                "Agua,Volador",
                "Electrico,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\226.jpg"));
        listaPokemon.add(new Normal("Skarmory",
                227,
                65,
                80,
                140,
                40,
                70,
                70,
                "Acero/Volador",
                "1,7",
                "Coraza Ave",
                "50,5",
                "Vista Lince,Robustez",
                "Sus alas metálicas son ligeras y resistentes, permitiéndole volar rápidamente pese a tener el cuerpo cubierto de acero.",
                "♀/♂",
                "Acero,Volador",
                "Fuego,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\227.jpg"));
        listaPokemon.add(new Normal("Houndour",
                228,
                45,
                60,
                30,
                80,
                50,
                65,
                "Siniestro/Fuego",
                "0,6",
                "Siniestro",
                "10,8",
                "Madrugar,Absorbe Fuego",
                "Caza en grupos organizados y utiliza distintos aullidos para comunicarse con sus compañeros durante la persecución.",
                "♀/♂",
                "Siniestro,Fuego",
                "Agua,Lucha,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\228.jpg"));
        listaPokemon.add(new Normal("Houndoom",
                229,
                75,
                90,
                50,
                110,
                80,
                95,
                "Siniestro/Fuego",
                "1,4",
                "Siniestro",
                "35,0",
                "Madrugar,Absorbe Fuego",
                "Las llamas que expulsa contienen sustancias que provocan un dolor intenso y es conocido por liderar grupos de Houndour.",
                "♀/♂",
                "Siniestro,Fuego",
                "Agua,Lucha,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\229.jpg"));
        listaPokemon.add(new Agua("Kingdra",
                230,
                75,
                95,
                95,
                95,
                95,
                85,
                "Agua/Dragon",
                "1,8",
                "Dragón",
                "152,0",
                "Nado Rapido,Francotirador",
                "Habita en zonas profundas y tranquilas del océano, donde puede generar fuertes corrientes cuando se mueve.",
                "♀/♂",
                "Agua,Dragon",
                "Dragon,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\230.jpg"));
        listaPokemon.add(new Tierra("Phanpy",
                231,
                90,
                60,
                60,
                40,
                40,
                40,
                "Tierra",
                "0,5",
                "Narizotas",
                "33,5",
                "Recogida",
                "Utiliza su pequeña trompa para jugar y puede enrollar su cuerpo para desplazarse rápidamente.",
                "♀/♂",
                "Tierra",
                "Agua,Planta,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\231.jpg"));
        listaPokemon.add(new Tierra("Donphan",
                232,
                90,
                120,
                120,
                60,
                60,
                50,
                "Tierra",
                "1,1",
                "Coraza",
                "120,0",
                "Robustez",
                "Su resistente piel y grandes colmillos le permiten enrollarse y embestir a sus enemigos como una pesada rueda.",
                "♀/♂",
                "Tierra",
                "Agua,Planta,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\232.jpg"));
        listaPokemon.add(new Normal("Porygon2",
                233,
                85,
                80,
                90,
                105,
                95,
                60,
                "Normal",
                "0,6",
                "Virtual",
                "32,5",
                "Rastro,Descarga",
                "Fue mejorado mediante tecnología avanzada para explorar distintos entornos y aprender nuevos comportamientos.",
                "Sin genero",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\233.jpg"));
        listaPokemon.add(new Normal("Stantler",
                234,
                73,
                95,
                62,
                85,
                65,
                85,
                "Normal",
                "1,4",
                "Gran Cuerno",
                "71,2",
                "Intimidacion,Cacheo",
                "La forma de sus cuernos puede provocar extrañas sensaciones en quienes los observan durante demasiado tiempo.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\234.jpg"));
        listaPokemon.add(new Normal("Smeargle",
                235,
                55,
                20,
                35,
                20,
                45,
                75,
                "Normal",
                "1,2",
                "Pintor",
                "58,0",
                "Ritmo Propio,Experto",
                "Utiliza el líquido que produce su cola para pintar símbolos y marcar los lugares que considera su territorio.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\235.jpg"));
        listaPokemon.add(new Lucha("Tyrogue",
                236,
                35,
                35,
                35,
                35,
                35,
                35,
                "Lucha",
                "0,7",
                "Peleón",
                "21,0",
                "Agallas,Impasible",
                "Posee un espíritu competitivo y entrena constantemente enfrentándose a rivales cada vez más fuertes.",
                "♂",
                "Lucha",
                "Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\236.jpg"));
        listaPokemon.add(new Lucha("Hitmontop",
                237,
                50,
                95,
                95,
                35,
                110,
                70,
                "Lucha",
                "1,4",
                "Boca Abajo",
                "48,0",
                "Intimidacion,Experto",
                "Gira sobre la punta de su cabeza y utiliza la fuerza centrífuga para lanzar poderosas patadas.",
                "♂",
                "Lucha",
                "Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\237.jpg"));
        listaPokemon.add(new Hielo("Smoochum",
                238,
                45,
                30,
                15,
                85,
                65,
                65,
                "Hielo/Psiquico",
                "0,4",
                "Beso",
                "6,0",
                "Despiste,Alerta",
                "Examina los objetos utilizando sus sensibles labios y mueve constantemente la cabeza mientras explora su entorno.",
                "♀",
                "Hielo,Psiquico",
                "Fuego,Bicho,Roca,Fantasma,Siniestro,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\238.jpg"));
        listaPokemon.add(new Electrico("Elekid",
                239,
                45,
                63,
                37,
                65,
                55,
                95,
                "Electrico",
                "0,6",
                "Eléctrico",
                "23,5",
                "Electricidad Estatica",
                "Gira sus brazos para generar electricidad, aunque todavía tiene dificultades para almacenar grandes cantidades de energía.",
                "♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\239.jpg"));
        listaPokemon.add(new Fuego("Magby",
                240,
                45,
                75,
                37,
                70,
                55,
                83,
                "Fuego",
                "0,7",
                "Ascuas",
                "21,4",
                "Cuerpo Llama",
                "Su temperatura corporal es muy elevada y puede expulsar pequeñas llamas por la boca cuando se encuentra emocionado.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\240.jpg"));
        listaPokemon.add(new Normal("Miltank",
                241,
                95,
                80,
                105,
                40,
                70,
                100,
                "Normal",
                "1,2",
                "Lechera",
                "75,5",
                "Sebo,Intrepido",
                "Produce una leche muy nutritiva y su fuerte cuerpo le permite correr con sorprendente velocidad.",
                "♀",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\241.jpg"));
        listaPokemon.add(new Normal("Blissey",
                242,
                255,
                10,
                10,
                75,
                135,
                55,
                "Normal",
                "1,5",
                "Felicidad",
                "46,8",
                "Cura Natural,Dicha",
                "Es extremadamente amable y comparte sus nutritivos huevos con Pokémon o personas que se encuentran heridas.",
                "♀",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\242.jpg"));
        listaPokemon.add(new Electrico("Raikou",
                243,
                90,
                85,
                75,
                115,
                100,
                115,
                "Electrico",
                "1,9",
                "Trueno",
                "178,0",
                "Presion",
                "Representa la fuerza del rayo y recorre grandes territorios mientras produce rugidos semejantes al sonido de un trueno.",
                "Sin genero",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\243.jpg"));
        listaPokemon.add(new Fuego("Entei",
                244,
                115,
                115,
                85,
                90,
                75,
                100,
                "Fuego",
                "2,1",
                "Volcán",
                "198,0",
                "Presion",
                "Posee la fuerza del magma y se dice que sus rugidos son capaces de provocar enormes erupciones volcánicas.",
                "Sin genero",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\244.jpg"));
        listaPokemon.add(new Agua("Suicune",
                245,
                100,
                75,
                115,
                90,
                115,
                85,
                "Agua",
                "2,0",
                "Aurora",
                "187,0",
                "Presion",
                "Viaja por el mundo buscando aguas limpias y posee la capacidad de purificar fuentes contaminadas.",
                "Sin genero",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\245.jpg"));
        listaPokemon.add(new Roca("Larvitar",
                246,
                50,
                64,
                50,
                45,
                50,
                41,
                "Roca/Tierra",
                "0,6",
                "Piel Roca",
                "72,0",
                "Agallas",
                "Nace bajo tierra y necesita alimentarse de grandes cantidades de suelo antes de poder alcanzar la superficie.",
                "♀/♂",
                "Roca,Tierra",
                "Agua,Planta,Hielo,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\246.jpg"));
        listaPokemon.add(new Roca("Pupitar",
                247,
                70,
                84,
                70,
                65,
                70,
                51,
                "Roca/Tierra",
                "1,2",
                "Caparazón",
                "152,0",
                "Mudar",
                "Aunque está encerrado en una dura cubierta, puede desplazarse expulsando gases a gran presión desde su cuerpo.",
                "♀/♂",
                "Roca,Tierra",
                "Agua,Planta,Hielo,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\247.jpg"));
        listaPokemon.add(new Roca("Tyranitar",
                248,
                100,
                134,
                110,
                95,
                100,
                61,
                "Roca/Siniestro",
                "2,0",
                "Coraza",
                "202,0",
                "Chorro Arena",
                "Su enorme fuerza le permite destruir montañas y modificar el terreno mientras busca rivales suficientemente poderosos.",
                "♀/♂",
                "Roca,Siniestro",
                "Agua,Planta,Lucha,Tierra,Bicho,Acero,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\248.jpg"));
        listaPokemon.add(new Psiquico("Lugia",
                249,
                106,
                90,
                130,
                90,
                154,
                110,
                "Psiquico/Volador",
                "5,2",
                "Buceo",
                "216,0",
                "Presion",
                "Vive oculto en las profundidades del océano porque el enorme poder de sus alas puede provocar fuertes tormentas.",
                "Sin genero",
                "Psiquico,Volador",
                "Electrico,Hielo,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\249.jpg"));
        listaPokemon.add(new Fuego("Ho-Oh",
                250,
                106,
                130,
                90,
                110,
                154,
                90,
                "Fuego/Volador",
                "3,8",
                "Arcoíris",
                "199,0",
                "Presion",
                "Sus brillantes plumas reflejan distintos colores y las leyendas aseguran que aparece ante entrenadores de corazón puro.",
                "Sin genero",
                "Fuego,Volador",
                "Agua,Electrico,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\250.jpg"));
        listaPokemon.add(new Psiquico("Celebi",
                251,
                100,
                100,
                100,
                100,
                100,
                100,
                "Psiquico/Planta",
                "0,6",
                "Viajetiempo",
                "5,0",
                "Cura Natural",
                "Puede viajar a través del tiempo y suele aparecer en bosques tranquilos donde la naturaleza se encuentra saludable.",
                "Sin genero",
                "Psiquico,Planta",
                "Fuego,Hielo,Veneno,Volador,Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\JOHTO\\251.jpg"));







        return listaPokemon;
    }
}