package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexHoennRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();
        listaPokemon.add(new Planta("Sceptile",
                254,
                70,
                85,
                65,
                105,
                85,
                120,
                "Planta",
                "1,7",
                "Bosque",
                "52,2",
                "Espesura",
                "Sceptile es un Pokémon de tipo Planta originario de Hoenn. Destaca por las características propias de la categoría bosque y por su habilidad en combate.",
                "♀/♂",
                "Planta",
                "Fuego,Hielo,Veneno,Volador,Bicho",
                ""));
        listaPokemon.add(new Fuego("Blaziken",
                257,
                80,
                120,
                70,
                110,
                70,
                80,
                "Fuego/Lucha",
                "1,9",
                "Llameante",
                "52,0",
                "Mar Llamas",
                "Blaziken es un Pokémon de tipo Fuego/Lucha originario de Hoenn. Destaca por las características propias de la categoría llameante y por su habilidad en combate.",
                "♀/♂",
                "Fuego,Lucha",
                "Agua,Tierra,Volador,Psiquico",
                ""));
        listaPokemon.add(new Agua("Swampert",
                260,
                100,
                110,
                90,
                85,
                90,
                60,
                "Agua/Tierra",
                "1,5",
                "Pez Lodo",
                "81,9",
                "Torrente",
                "Swampert es un Pokémon de tipo Agua/Tierra originario de Hoenn. Destaca por las características propias de la categoría pez lodo y por su habilidad en combate.",
                "♀/♂",
                "Agua,Tierra",
                "Planta",
                ""));
        listaPokemon.add(new Normal("Mightyena",
                262,
                70,
                90,
                70,
                60,
                60,
                70,
                "Siniestro",
                "1,0",
                "Mordisco",
                "37,0",
                "Intimidación,Pies Rápidos",
                "Mightyena es un Pokémon de tipo Siniestro originario de Hoenn. Destaca por las características propias de la categoría mordisco y por su habilidad en combate.",
                "♀/♂",
                "Siniestro",
                "Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Normal("Linoone",
                264,
                78,
                70,
                61,
                50,
                61,
                100,
                "Normal",
                "0,5",
                "Lanzado",
                "32,5",
                "Recogida,Gula",
                "Linoone es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría lanzado y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Bicho("Beautifly",
                267,
                60,
                70,
                50,
                100,
                50,
                65,
                "Bicho/Volador",
                "1,0",
                "Mariposa",
                "28,4",
                "Enjambre",
                "Beautifly es un Pokémon de tipo Bicho/Volador originario de Hoenn. Destaca por las características propias de la categoría mariposa y por su habilidad en combate.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Electrico,Hielo,Volador,Roca",
                ""));
        listaPokemon.add(new Bicho("Dustox",
                269,
                60,
                50,
                70,
                50,
                90,
                65,
                "Bicho/Veneno",
                "1,2",
                "Polilla Venenosa",
                "31,6",
                "Polvo Escudo",
                "Dustox es un Pokémon de tipo Bicho/Veneno originario de Hoenn. Destaca por las características propias de la categoría polilla venenosa y por su habilidad en combate.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Psiquico,Roca",
                ""));
        listaPokemon.add(new Agua("Ludicolo",
                272,
                80,
                70,
                70,
                90,
                100,
                70,
                "Agua/Planta",
                "1,5",
                "Despreocupado",
                "55,0",
                "Nado Rápido,Cura Lluvia",
                "Ludicolo es un Pokémon de tipo Agua/Planta originario de Hoenn. Destaca por las características propias de la categoría despreocupado y por su habilidad en combate.",
                "♀/♂",
                "Agua,Planta",
                "Veneno,Volador,Bicho",
                ""));
        listaPokemon.add(new Planta("Shiftry",
                275,
                90,
                100,
                60,
                90,
                60,
                80,
                "Planta/Siniestro",
                "1,3",
                "Malvado",
                "59,6",
                "Clorofila,Madrugar",
                "Shiftry es un Pokémon de tipo Planta/Siniestro originario de Hoenn. Destaca por las características propias de la categoría malvado y por su habilidad en combate.",
                "♀/♂",
                "Planta,Siniestro",
                "Fuego,Hielo,Lucha,Veneno,Volador,Bicho,Hada",
                ""));
        listaPokemon.add(new Normal("Swellow",
                277,
                60,
                85,
                60,
                75,
                50,
                125,
                "Normal/Volador",
                "0,7",
                "Golondrina",
                "19,8",
                "Agallas",
                "Swellow es un Pokémon de tipo Normal/Volador originario de Hoenn. Destaca por las características propias de la categoría golondrina y por su habilidad en combate.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Hielo,Roca",
                ""));
        listaPokemon.add(new Agua("Pelipper",
                279,
                60,
                50,
                100,
                95,
                70,
                65,
                "Agua/Volador",
                "1,2",
                "Ave Agua",
                "28,0",
                "Vista Lince,Llovizna",
                "Pelipper es un Pokémon de tipo Agua/Volador originario de Hoenn. Destaca por las características propias de la categoría ave agua y por su habilidad en combate.",
                "♀/♂",
                "Agua,Volador",
                "Electrico,Roca",
                ""));
        listaPokemon.add(new Psiquico("Gardevoir",
                282,
                68,
                65,
                65,
                125,
                115,
                80,
                "Psiquico/Hada",
                "1,6",
                "Abrazo",
                "48,4",
                "Sincronía,Rastro",
                "Gardevoir es un Pokémon de tipo Psiquico/Hada originario de Hoenn. Destaca por las características propias de la categoría abrazo y por su habilidad en combate.",
                "♀/♂",
                "Psiquico,Hada",
                "Veneno,Fantasma,Acero",
                ""));
        listaPokemon.add(new Bicho("Masquerain",
                284,
                70,
                60,
                62,
                100,
                82,
                80,
                "Bicho/Volador",
                "0,8",
                "Ojo",
                "3,6",
                "Intimidación",
                "Masquerain es un Pokémon de tipo Bicho/Volador originario de Hoenn. Destaca por las características propias de la categoría ojo y por su habilidad en combate.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Electrico,Hielo,Volador,Roca",
                ""));
        listaPokemon.add(new Planta("Breloom",
                286,
                60,
                130,
                80,
                60,
                60,
                70,
                "Planta/Lucha",
                "1,2",
                "Hongo",
                "39,2",
                "Efecto Espora,Antídoto",
                "Breloom es un Pokémon de tipo Planta/Lucha originario de Hoenn. Destaca por las características propias de la categoría hongo y por su habilidad en combate.",
                "♀/♂",
                "Planta,Lucha",
                "Fuego,Hielo,Veneno,Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Normal("Slaking",
                289,
                150,
                160,
                100,
                95,
                65,
                100,
                "Normal",
                "2,0",
                "Holgazán",
                "130,5",
                "Ausente",
                "Slaking es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría holgazán y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Bicho("Ninjask",
                291,
                61,
                90,
                45,
                50,
                50,
                160,
                "Bicho/Volador",
                "0,8",
                "Ninja",
                "12,0",
                "Impulso",
                "Ninjask es un Pokémon de tipo Bicho/Volador originario de Hoenn. Destaca por las características propias de la categoría ninja y por su habilidad en combate.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Electrico,Hielo,Volador,Roca",
                ""));
        listaPokemon.add(new Bicho("Shedinja",
                292,
                1,
                90,
                45,
                30,
                30,
                40,
                "Bicho/Fantasma",
                "0,8",
                "Muda",
                "1,2",
                "Superguarda",
                "Shedinja es un Pokémon de tipo Bicho/Fantasma originario de Hoenn. Destaca por las características propias de la categoría muda y por su habilidad en combate.",
                "Sin genero",
                "Bicho,Fantasma",
                "Fuego,Volador,Roca,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Normal("Exploud",
                295,
                104,
                91,
                63,
                91,
                73,
                68,
                "Normal",
                "1,5",
                "Estruendo",
                "84,0",
                "Insonorizar",
                "Exploud es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría estruendo y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Lucha("Hariyama",
                297,
                144,
                120,
                60,
                40,
                60,
                50,
                "Lucha",
                "2,3",
                "Empuje",
                "253,8",
                "Sebo,Agallas",
                "Hariyama es un Pokémon de tipo Lucha originario de Hoenn. Destaca por las características propias de la categoría empuje y por su habilidad en combate.",
                "♀/♂",
                "Lucha",
                "Volador,Psiquico,Hada",
                ""));
        listaPokemon.add(new Roca("Nosepass",
                299,
                30,
                45,
                135,
                45,
                90,
                30,
                "Roca",
                "1,0",
                "Brújula",
                "97,0",
                "Robustez,Imán",
                "Nosepass es un Pokémon de tipo Roca originario de Hoenn. Destaca por las características propias de la categoría brújula y por su habilidad en combate.",
                "♀/♂",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                ""));
        listaPokemon.add(new Normal("Delcatty",
                301,
                70,
                65,
                65,
                55,
                55,
                90,
                "Normal",
                "1,1",
                "Primoroso",
                "32,6",
                "Gran Encanto,Normalidad",
                "Delcatty es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría primoroso y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Normal("Sableye",
                302,
                50,
                75,
                75,
                65,
                65,
                50,
                "Siniestro/Fantasma",
                "0,5",
                "Oscuridad",
                "11,0",
                "Vista Lince,Rezagado",
                "Sableye es un Pokémon de tipo Siniestro/Fantasma originario de Hoenn. Destaca por las características propias de la categoría oscuridad y por su habilidad en combate.",
                "♀/♂",
                "Siniestro,Fantasma",
                "Hada",
                ""));
        listaPokemon.add(new Normal("Mawile",
                303,
                50,
                85,
                85,
                55,
                55,
                50,
                "Acero/Hada",
                "0,6",
                "Tramposo",
                "11,5",
                "Corte Fuerte,Intimidación",
                "Mawile es un Pokémon de tipo Acero/Hada originario de Hoenn. Destaca por las características propias de la categoría tramposo y por su habilidad en combate.",
                "♀/♂",
                "Acero,Hada",
                "Fuego,Tierra",
                ""));
        listaPokemon.add(new Normal("Aggron",
                306,
                70,
                110,
                180,
                60,
                60,
                50,
                "Acero/Roca",
                "2,1",
                "Armadura Férrea",
                "360,0",
                "Robustez,Cabeza Roca",
                "Aggron es un Pokémon de tipo Acero/Roca originario de Hoenn. Destaca por las características propias de la categoría armadura férrea y por su habilidad en combate.",
                "♀/♂",
                "Acero,Roca",
                "Agua,Lucha,Tierra",
                ""));
        listaPokemon.add(new Lucha("Medicham",
                308,
                60,
                60,
                75,
                60,
                75,
                80,
                "Lucha/Psiquico",
                "1,3",
                "Meditación",
                "31,5",
                "Energía Pura",
                "Medicham es un Pokémon de tipo Lucha/Psiquico originario de Hoenn. Destaca por las características propias de la categoría meditación y por su habilidad en combate.",
                "♀/♂",
                "Lucha,Psiquico",
                "Volador,Fantasma,Hada",
                ""));
        listaPokemon.add(new Electrico("Manectric",
                310,
                70,
                75,
                60,
                105,
                60,
                105,
                "Electrico",
                "1,5",
                "Descarga",
                "40,2",
                "Electricidad Estática,Pararrayos",
                "Manectric es un Pokémon de tipo Electrico originario de Hoenn. Destaca por las características propias de la categoría descarga y por su habilidad en combate.",
                "♀/♂",
                "Electrico",
                "Tierra",
                ""));
        listaPokemon.add(new Electrico("Plusle",
                311,
                60,
                50,
                40,
                85,
                75,
                95,
                "Electrico",
                "0,4",
                "Ánimo",
                "4,2",
                "Más",
                "Plusle es un Pokémon de tipo Electrico originario de Hoenn. Destaca por las características propias de la categoría ánimo y por su habilidad en combate.",
                "♀/♂",
                "Electrico",
                "Tierra",
                ""));
        listaPokemon.add(new Electrico("Minun",
                312,
                60,
                40,
                50,
                75,
                85,
                95,
                "Electrico",
                "0,4",
                "Ánimo",
                "4,2",
                "Menos",
                "Minun es un Pokémon de tipo Electrico originario de Hoenn. Destaca por las características propias de la categoría ánimo y por su habilidad en combate.",
                "♀/♂",
                "Electrico",
                "Tierra",
                ""));
        listaPokemon.add(new Bicho("Volbeat",
                313,
                65,
                73,
                75,
                47,
                85,
                85,
                "Bicho",
                "0,7",
                "Luciérnaga",
                "17,7",
                "Iluminación,Enjambre",
                "Volbeat es un Pokémon de tipo Bicho originario de Hoenn. Destaca por las características propias de la categoría luciérnaga y por su habilidad en combate.",
                "♂",
                "Bicho",
                "Fuego,Volador,Roca",
                ""));
        listaPokemon.add(new Bicho("Illumise",
                314,
                65,
                47,
                75,
                73,
                85,
                85,
                "Bicho",
                "0,6",
                "Luciérnaga",
                "17,7",
                "Despiste,Cromolente",
                "Illumise es un Pokémon de tipo Bicho originario de Hoenn. Destaca por las características propias de la categoría luciérnaga y por su habilidad en combate.",
                "♀",
                "Bicho",
                "Fuego,Volador,Roca",
                ""));
        listaPokemon.add(new Planta("Roselia",
                315,
                50,
                60,
                45,
                100,
                80,
                65,
                "Planta/Veneno",
                "0,3",
                "Espina",
                "2,0",
                "Cura Natural,Punto Tóxico",
                "Roselia es un Pokémon de tipo Planta/Veneno originario de Hoenn. Destaca por las características propias de la categoría espina y por su habilidad en combate.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Hielo,Volador,Psiquico",
                ""));
        listaPokemon.add(new Veneno("Swalot",
                317,
                100,
                73,
                83,
                73,
                83,
                55,
                "Veneno",
                "1,7",
                "Bolsa Veneno",
                "80,0",
                "Lodo Líquido,Viscosidad",
                "Swalot es un Pokémon de tipo Veneno originario de Hoenn. Destaca por las características propias de la categoría bolsa veneno y por su habilidad en combate.",
                "♀/♂",
                "Veneno",
                "Tierra,Psiquico",
                ""));
        listaPokemon.add(new Agua("Sharpedo",
                319,
                70,
                120,
                40,
                95,
                40,
                95,
                "Agua/Siniestro",
                "1,8",
                "Brutal",
                "88,8",
                "Piel Tosca",
                "Sharpedo es un Pokémon de tipo Agua/Siniestro originario de Hoenn. Destaca por las características propias de la categoría brutal y por su habilidad en combate.",
                "♀/♂",
                "Agua,Siniestro",
                "Electrico,Planta,Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Agua("Wailord",
                321,
                170,
                90,
                45,
                90,
                45,
                60,
                "Agua",
                "14,5",
                "Ballena Flotante",
                "398,0",
                "Velo Agua,Despiste",
                "Wailord es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría ballena flotante y por su habilidad en combate.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Fuego("Camerupt",
                323,
                70,
                100,
                70,
                105,
                75,
                40,
                "Fuego/Tierra",
                "1,9",
                "Erupción",
                "220,0",
                "Escudo Magma,Roca Sólida",
                "Camerupt es un Pokémon de tipo Fuego/Tierra originario de Hoenn. Destaca por las características propias de la categoría erupción y por su habilidad en combate.",
                "♀/♂",
                "Fuego,Tierra",
                "Agua,Tierra",
                ""));
        listaPokemon.add(new Fuego("Torkoal",
                324,
                70,
                85,
                140,
                85,
                70,
                20,
                "Fuego",
                "0,5",
                "Carbón",
                "80,4",
                "Humo Blanco,Sequía",
                "Torkoal es un Pokémon de tipo Fuego originario de Hoenn. Destaca por las características propias de la categoría carbón y por su habilidad en combate.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                ""));
        listaPokemon.add(new Psiquico("Grumpig",
                326,
                80,
                45,
                65,
                90,
                110,
                80,
                "Psiquico",
                "0,9",
                "Manipulación",
                "71,5",
                "Sebo,Ritmo Propio",
                "Grumpig es un Pokémon de tipo Psiquico originario de Hoenn. Destaca por las características propias de la categoría manipulación y por su habilidad en combate.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Normal("Spinda",
                327,
                60,
                60,
                60,
                60,
                60,
                60,
                "Normal",
                "1,1",
                "Panda Mancha",
                "5,0",
                "Ritmo Propio,Tumbos",
                "Spinda es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría panda mancha y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Tierra("Flygon",
                330,
                80,
                100,
                80,
                80,
                80,
                100,
                "Tierra/Dragon",
                "2,0",
                "Místico",
                "82,0",
                "Levitación",
                "Flygon es un Pokémon de tipo Tierra/Dragon originario de Hoenn. Destaca por las características propias de la categoría místico y por su habilidad en combate.",
                "♀/♂",
                "Tierra,Dragon",
                "Hielo,Dragon,Hada",
                ""));
        listaPokemon.add(new Planta("Cacturne",
                332,
                70,
                115,
                60,
                115,
                60,
                55,
                "Planta/Siniestro",
                "1,3",
                "Espantapájaros",
                "77,4",
                "Velo Arena",
                "Cacturne es un Pokémon de tipo Planta/Siniestro originario de Hoenn. Destaca por las características propias de la categoría espantapájaros y por su habilidad en combate.",
                "♀/♂",
                "Planta,Siniestro",
                "Fuego,Hielo,Lucha,Veneno,Volador,Bicho,Hada",
                ""));
        listaPokemon.add(new Dragon("Altaria",
                334,
                75,
                70,
                90,
                70,
                105,
                80,
                "Dragon/Volador",
                "1,1",
                "Tarareo",
                "20,6",
                "Cura Natural",
                "Altaria es un Pokémon de tipo Dragon/Volador originario de Hoenn. Destaca por las características propias de la categoría tarareo y por su habilidad en combate.",
                "♀/♂",
                "Dragon,Volador",
                "Hielo,Roca,Dragon,Hada",
                ""));
        listaPokemon.add(new Normal("Zangoose",
                335,
                73,
                115,
                60,
                60,
                60,
                90,
                "Normal",
                "1,3",
                "Hurón Gato",
                "40,3",
                "Inmunidad",
                "Zangoose es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría hurón gato y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Veneno("Seviper",
                336,
                73,
                100,
                60,
                100,
                60,
                65,
                "Veneno",
                "2,7",
                "Colmillo Serpiente",
                "52,5",
                "Mudar",
                "Seviper es un Pokémon de tipo Veneno originario de Hoenn. Destaca por las características propias de la categoría colmillo serpiente y por su habilidad en combate.",
                "♀/♂",
                "Veneno",
                "Tierra,Psiquico",
                ""));
        listaPokemon.add(new Roca("Lunatone",
                337,
                90,
                55,
                65,
                95,
                85,
                70,
                "Roca/Psiquico",
                "1,0",
                "Meteorito",
                "168,0",
                "Levitación",
                "Lunatone es un Pokémon de tipo Roca/Psiquico originario de Hoenn. Destaca por las características propias de la categoría meteorito y por su habilidad en combate.",
                "Sin genero",
                "Roca,Psiquico",
                "Agua,Planta,Tierra,Bicho,Fantasma,Siniestro,Acero",
                ""));
        listaPokemon.add(new Roca("Solrock",
                338,
                90,
                95,
                85,
                55,
                65,
                70,
                "Roca/Psiquico",
                "1,2",
                "Meteorito",
                "154,0",
                "Levitación",
                "Solrock es un Pokémon de tipo Roca/Psiquico originario de Hoenn. Destaca por las características propias de la categoría meteorito y por su habilidad en combate.",
                "Sin genero",
                "Roca,Psiquico",
                "Agua,Planta,Tierra,Bicho,Fantasma,Siniestro,Acero",
                ""));
        listaPokemon.add(new Agua("Whiscash",
                340,
                110,
                78,
                73,
                76,
                71,
                60,
                "Agua/Tierra",
                "0,9",
                "Bigotes",
                "23,6",
                "Despiste,Anticipación",
                "Whiscash es un Pokémon de tipo Agua/Tierra originario de Hoenn. Destaca por las características propias de la categoría bigotes y por su habilidad en combate.",
                "♀/♂",
                "Agua,Tierra",
                "Planta",
                ""));
        listaPokemon.add(new Agua("Crawdaunt",
                342,
                63,
                120,
                85,
                90,
                55,
                55,
                "Agua/Siniestro",
                "1,1",
                "Pícaro",
                "32,8",
                "Corte Fuerte,Caparazón",
                "Crawdaunt es un Pokémon de tipo Agua/Siniestro originario de Hoenn. Destaca por las características propias de la categoría pícaro y por su habilidad en combate.",
                "♀/♂",
                "Agua,Siniestro",
                "Electrico,Planta,Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Tierra("Claydol",
                344,
                60,
                70,
                105,
                70,
                120,
                75,
                "Tierra/Psiquico",
                "1,5",
                "Muñeco Barro",
                "108,0",
                "Levitación",
                "Claydol es un Pokémon de tipo Tierra/Psiquico originario de Hoenn. Destaca por las características propias de la categoría muñeco barro y por su habilidad en combate.",
                "Sin genero",
                "Tierra,Psiquico",
                "Agua,Planta,Hielo,Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Roca("Cradily",
                346,
                86,
                81,
                97,
                81,
                107,
                43,
                "Roca/Planta",
                "1,5",
                "Percebe",
                "60,4",
                "Ventosas",
                "Cradily es un Pokémon de tipo Roca/Planta originario de Hoenn. Destaca por las características propias de la categoría percebe y por su habilidad en combate.",
                "♀/♂",
                "Roca,Planta",
                "Hielo,Lucha,Bicho,Acero",
                ""));
        listaPokemon.add(new Roca("Armaldo",
                348,
                75,
                125,
                100,
                70,
                80,
                45,
                "Roca/Bicho",
                "1,5",
                "Placa",
                "68,2",
                "Armadura Batalla",
                "Armaldo es un Pokémon de tipo Roca/Bicho originario de Hoenn. Destaca por las características propias de la categoría placa y por su habilidad en combate.",
                "♀/♂",
                "Roca,Bicho",
                "Agua,Roca,Acero",
                ""));
        listaPokemon.add(new Agua("Milotic",
                350,
                95,
                60,
                79,
                100,
                125,
                81,
                "Agua",
                "6,2",
                "Tierno",
                "162,0",
                "Escama Especial,Competitivo",
                "Milotic es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría tierno y por su habilidad en combate.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Normal("Castform",
                351,
                70,
                70,
                70,
                70,
                70,
                70,
                "Normal",
                "0,3",
                "Clima",
                "0,8",
                "Predicción",
                "Castform es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría clima y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Normal("Kecleon",
                352,
                60,
                90,
                70,
                60,
                120,
                40,
                "Normal",
                "1,0",
                "Cambio Color",
                "22,0",
                "Cambio Color",
                "Kecleon es un Pokémon de tipo Normal originario de Hoenn. Destaca por las características propias de la categoría cambio color y por su habilidad en combate.",
                "♀/♂",
                "Normal",
                "Lucha",
                ""));
        listaPokemon.add(new Fantasma("Banette",
                354,
                64,
                115,
                65,
                83,
                63,
                65,
                "Fantasma",
                "1,1",
                "Marioneta",
                "12,5",
                "Insomnio,Cacheo",
                "Banette es un Pokémon de tipo Fantasma originario de Hoenn. Destaca por las características propias de la categoría marioneta y por su habilidad en combate.",
                "♀/♂",
                "Fantasma",
                "Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Fantasma("Dusclops",
                356,
                40,
                70,
                130,
                60,
                130,
                25,
                "Fantasma",
                "1,6",
                "Atracción",
                "30,6",
                "Presión",
                "Dusclops es un Pokémon de tipo Fantasma originario de Hoenn. Destaca por las características propias de la categoría atracción y por su habilidad en combate.",
                "♀/♂",
                "Fantasma",
                "Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Planta("Tropius",
                357,
                99,
                68,
                83,
                72,
                87,
                51,
                "Planta/Volador",
                "2,0",
                "Fruto",
                "100,0",
                "Clorofila,Poder Solar",
                "Tropius es un Pokémon de tipo Planta/Volador originario de Hoenn. Destaca por las características propias de la categoría fruto y por su habilidad en combate.",
                "♀/♂",
                "Planta,Volador",
                "Fuego,Hielo,Veneno,Volador,Roca",
                ""));
        listaPokemon.add(new Psiquico("Chimecho",
                358,
                75,
                50,
                80,
                95,
                90,
                65,
                "Psiquico",
                "0,6",
                "Campana Viento",
                "1,0",
                "Levitación",
                "Chimecho es un Pokémon de tipo Psiquico originario de Hoenn. Destaca por las características propias de la categoría campana viento y por su habilidad en combate.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Normal("Absol",
                359,
                65,
                130,
                60,
                75,
                60,
                75,
                "Siniestro",
                "1,2",
                "Desastre",
                "47,0",
                "Presión,Afortunado",
                "Absol es un Pokémon de tipo Siniestro originario de Hoenn. Destaca por las características propias de la categoría desastre y por su habilidad en combate.",
                "♀/♂",
                "Siniestro",
                "Lucha,Bicho,Hada",
                ""));
        listaPokemon.add(new Hielo("Glalie",
                362,
                80,
                80,
                80,
                80,
                80,
                80,
                "Hielo",
                "1,5",
                "Cara",
                "256,5",
                "Foco Interno,Cuerpo Hielo",
                "Glalie es un Pokémon de tipo Hielo originario de Hoenn. Destaca por las características propias de la categoría cara y por su habilidad en combate.",
                "♀/♂",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Hielo("Walrein",
                365,
                110,
                80,
                90,
                95,
                90,
                65,
                "Hielo/Agua",
                "1,4",
                "Rompehielo",
                "150,6",
                "Sebo,Cuerpo Hielo",
                "Walrein es un Pokémon de tipo Hielo/Agua originario de Hoenn. Destaca por las características propias de la categoría rompehielo y por su habilidad en combate.",
                "♀/♂",
                "Hielo,Agua",
                "Electrico,Planta,Lucha,Roca",
                ""));
        listaPokemon.add(new Agua("Huntail",
                367,
                55,
                104,
                105,
                94,
                75,
                52,
                "Agua",
                "1,7",
                "Mar Profundo",
                "27,0",
                "Nado Rápido",
                "Huntail es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría mar profundo y por su habilidad en combate.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Agua("Gorebyss",
                368,
                55,
                84,
                105,
                114,
                75,
                52,
                "Agua",
                "1,8",
                "Mar del Sur",
                "22,6",
                "Nado Rápido",
                "Gorebyss es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría mar del sur y por su habilidad en combate.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Agua("Relicanth",
                369,
                100,
                90,
                130,
                45,
                65,
                55,
                "Agua/Roca",
                "1,0",
                "Longevidad",
                "23,4",
                "Nado Rápido,Cabeza Roca",
                "Relicanth es un Pokémon de tipo Agua/Roca originario de Hoenn. Destaca por las características propias de la categoría longevidad y por su habilidad en combate.",
                "♀/♂",
                "Agua,Roca",
                "Electrico,Planta,Lucha,Tierra",
                ""));
        listaPokemon.add(new Agua("Luvdisc",
                370,
                43,
                30,
                55,
                40,
                65,
                97,
                "Agua",
                "0,6",
                "Encuentro",
                "8,7",
                "Nado Rápido",
                "Luvdisc es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría encuentro y por su habilidad en combate.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Dragon("Salamence",
                373,
                95,
                135,
                80,
                110,
                80,
                100,
                "Dragon/Volador",
                "1,5",
                "Dragón",
                "102,6",
                "Intimidación",
                "Salamence es un Pokémon de tipo Dragon/Volador originario de Hoenn. Destaca por las características propias de la categoría dragón y por su habilidad en combate.",
                "♀/♂",
                "Dragon,Volador",
                "Hielo,Roca,Dragon,Hada",
                ""));
        listaPokemon.add(new Normal("Metagross",
                376,
                80,
                135,
                130,
                95,
                90,
                70,
                "Acero/Psiquico",
                "1,6",
                "Pata Férrea",
                "550,0",
                "Cuerpo Puro",
                "Metagross es un Pokémon de tipo Acero/Psiquico originario de Hoenn. Destaca por las características propias de la categoría pata férrea y por su habilidad en combate.",
                "Sin genero",
                "Acero,Psiquico",
                "Fuego,Tierra,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Roca("Regirock",
                377,
                80,
                100,
                200,
                50,
                100,
                50,
                "Roca",
                "1,7",
                "Pico Roca",
                "230,0",
                "Cuerpo Puro",
                "Regirock es un Pokémon de tipo Roca originario de Hoenn. Destaca por las características propias de la categoría pico roca y por su habilidad en combate.",
                "Sin genero",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                ""));
        listaPokemon.add(new Hielo("Regice",
                378,
                80,
                50,
                100,
                100,
                200,
                50,
                "Hielo",
                "1,8",
                "Iceberg",
                "175,0",
                "Cuerpo Puro",
                "Regice es un Pokémon de tipo Hielo originario de Hoenn. Destaca por las características propias de la categoría iceberg y por su habilidad en combate.",
                "Sin genero",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                ""));
        listaPokemon.add(new Normal("Registeel",
                379,
                80,
                75,
                150,
                75,
                150,
                50,
                "Acero",
                "1,9",
                "Hierro",
                "205,0",
                "Cuerpo Puro",
                "Registeel es un Pokémon de tipo Acero originario de Hoenn. Destaca por las características propias de la categoría hierro y por su habilidad en combate.",
                "Sin genero",
                "Acero",
                "Fuego,Lucha,Tierra",
                ""));
        listaPokemon.add(new Dragon("Latias",
                380,
                80,
                80,
                90,
                110,
                130,
                110,
                "Dragon/Psiquico",
                "1,4",
                "Eón",
                "40,0",
                "Levitación",
                "Latias es un Pokémon de tipo Dragon/Psiquico originario de Hoenn. Destaca por las características propias de la categoría eón y por su habilidad en combate.",
                "♀",
                "Dragon,Psiquico",
                "Hielo,Bicho,Fantasma,Dragon,Siniestro,Hada",
                ""));
        listaPokemon.add(new Dragon("Latios",
                381,
                80,
                90,
                80,
                130,
                110,
                110,
                "Dragon/Psiquico",
                "2,0",
                "Eón",
                "60,0",
                "Levitación",
                "Latios es un Pokémon de tipo Dragon/Psiquico originario de Hoenn. Destaca por las características propias de la categoría eón y por su habilidad en combate.",
                "♂",
                "Dragon,Psiquico",
                "Hielo,Bicho,Fantasma,Dragon,Siniestro,Hada",
                ""));
        listaPokemon.add(new Agua("Kyogre",
                382,
                100,
                100,
                90,
                150,
                140,
                90,
                "Agua",
                "4,5",
                "Cuenca Marina",
                "352,0",
                "Llovizna",
                "Kyogre es un Pokémon de tipo Agua originario de Hoenn. Destaca por las características propias de la categoría cuenca marina y por su habilidad en combate.",
                "Sin genero",
                "Agua",
                "Electrico,Planta",
                ""));
        listaPokemon.add(new Tierra("Groudon",
                383,
                100,
                150,
                140,
                100,
                90,
                90,
                "Tierra",
                "3,5",
                "Continente",
                "950,0",
                "Sequía",
                "Groudon es un Pokémon de tipo Tierra originario de Hoenn. Destaca por las características propias de la categoría continente y por su habilidad en combate.",
                "Sin genero",
                "Tierra",
                "Agua,Planta,Hielo",
                ""));
        listaPokemon.add(new Dragon("Rayquaza",
                384,
                105,
                150,
                90,
                150,
                90,
                95,
                "Dragon/Volador",
                "7,0",
                "Cielo",
                "206,5",
                "Bucle Aire",
                "Rayquaza es un Pokémon de tipo Dragon/Volador originario de Hoenn. Destaca por las características propias de la categoría cielo y por su habilidad en combate.",
                "Sin genero",
                "Dragon,Volador",
                "Hielo,Roca,Dragon,Hada",
                ""));
        listaPokemon.add(new Normal("Jirachi",
                385,
                100,
                100,
                100,
                100,
                100,
                100,
                "Acero/Psiquico",
                "0,3",
                "Deseo",
                "1,1",
                "Dicha",
                "Jirachi es un Pokémon de tipo Acero/Psiquico originario de Hoenn. Destaca por las características propias de la categoría deseo y por su habilidad en combate.",
                "Sin genero",
                "Acero,Psiquico",
                "Fuego,Tierra,Fantasma,Siniestro",
                ""));
        listaPokemon.add(new Psiquico("Deoxys",
                386,
                50,
                150,
                50,
                150,
                50,
                150,
                "Psiquico",
                "1,7",
                "ADN",
                "60,8",
                "Presión",
                "Deoxys es un Pokémon de tipo Psiquico originario de Hoenn. Destaca por las características propias de la categoría adn y por su habilidad en combate.",
                "Sin genero",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                ""));

        return listaPokemon;
    }
}
