package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexTeseliaRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();
        listaPokemon.add(new Psiquico("Victini",
                494,
                100,
                100,
                100,
                100,
                100,
                100,
                "Psiquico/Fuego",
                "0,4",
                "Victoria",
                "4,0",
                "Tinovictoria",
                "Se dice que este Pokémon atrae la victoria y comparte una energía inagotable con quienes establece un vínculo.",
                "Sin genero",
                "Psiquico,Fuego",
                "Agua,Tierra,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\494.jpg"));
        listaPokemon.add(new Planta("Serperior",
                497,
                75,
                75,
                95,
                75,
                95,
                113,
                "Planta",
                "3,3",
                "Realeza",
                "63,0",
                "Espesura",
                "Intimida a sus rivales con una mirada penetrante y puede amplificar la energía solar dentro de su cuerpo.",
                "♀/♂",
                "Planta",
                "Fuego,Hielo,Veneno,Volador,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\497.jpg"));
        listaPokemon.add(new Fuego("Emboar",
                500,
                110,
                123,
                65,
                100,
                65,
                65,
                "Fuego/Lucha",
                "1,6",
                "Cerdo Ígneo",
                "150,0",
                "Mar Llamas",
                "Envuelve sus puños en llamas para lanzar poderosos golpes y posee una gran fuerza física pese a su corpulencia.",
                "♀/♂",
                "Fuego,Lucha",
                "Agua,Tierra,Volador,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\500.jpg"));
        listaPokemon.add(new Agua("Samurott",
                503,
                95,
                100,
                85,
                108,
                70,
                70,
                "Agua",
                "1,5",
                "Formidable",
                "94,6",
                "Torrente",
                "Puede desenvainar y atacar con las cuchillas de sus patas delanteras en un instante, imponiéndose con gran disciplina.",
                "♀/♂",
                "Agua",
                "Electrico,Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\503.jpg"));
        listaPokemon.add(new Normal("Watchog",
                505,
                60,
                85,
                69,
                60,
                69,
                77,
                "Normal",
                "1,1",
                "Vigilancia",
                "27,0",
                "Iluminación",
                "Almacena semillas en sus mejillas y usa las marcas luminosas de su cuerpo para intimidar a los enemigos.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\505.jpg"));
        listaPokemon.add(new Normal("Stoutland",
                508,
                85,
                110,
                90,
                45,
                90,
                80,
                "Normal",
                "1,2",
                "Magnánimo",
                "61,0",
                "Intimidación",
                "Su espeso pelaje lo protege del frío y es conocido por rescatar personas perdidas en montañas y mares embravecidos.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\508.jpg"));
        listaPokemon.add(new Normal("Liepard",
                510,
                64,
                88,
                50,
                88,
                50,
                106,
                "Siniestro",
                "1,1",
                "Cruel",
                "37,5",
                "Flexibilidad",
                "Se mueve con sigilo y elegancia, atacando por sorpresa antes de que el rival pueda reaccionar.",
                "♀/♂",
                "Siniestro",
                "Lucha,Bicho,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\510.jpg"));
        listaPokemon.add(new Psiquico("Musharna",
                518,
                116,
                55,
                85,
                107,
                95,
                29,
                "Psiquico",
                "1,1",
                "Duermevela",
                "60,5",
                "Alerta",
                "El humo que expulsa contiene los sueños de personas y Pokémon, y cambia de color según su contenido.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\518.jpg"));
        listaPokemon.add(new Electrico("Zebstrika",
                523,
                75,
                100,
                63,
                80,
                63,
                116,
                "Electrico",
                "1,6",
                "Rayo",
                "79,5",
                "Pararrayos",
                "Corre a gran velocidad mientras descarga electricidad por todo el cuerpo, y puede reaccionar con violencia ante un peligro.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\523.jpg"));
        listaPokemon.add(new Roca("Gigalith",
                526,
                85,
                135,
                130,
                60,
                80,
                25,
                "Roca",
                "1,7",
                "Presurizado",
                "260,0",
                "Robustez",
                "Absorbe energía solar y la concentra en su núcleo para disparar ataques capaces de causar enormes daños.",
                "♀/♂",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\526.jpg"));
        listaPokemon.add(new Psiquico("Swoobat",
                528,
                67,
                57,
                55,
                77,
                55,
                114,
                "Psiquico/Volador",
                "0,9",
                "Galanteo",
                "10,5",
                "Ignorante",
                "Emite potentes ondas ultrasónicas por la nariz y puede utilizarlas tanto para orientarse como para atacar.",
                "♀/♂",
                "Psiquico,Volador",
                "Electrico,Hielo,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\528.jpg"));
        listaPokemon.add(new Tierra("Excadrill",
                530,
                110,
                135,
                60,
                50,
                65,
                88,
                "Tierra/Acero",
                "0,7",
                "Subterráneo",
                "40,4",
                "Ímpetu Arena",
                "Excava túneles a gran velocidad usando sus garras metálicas y puede atravesar incluso terreno muy duro.",
                "♀/♂",
                "Tierra,Acero",
                "Fuego,Agua,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\530.jpg"));
        listaPokemon.add(new Normal("Audino",
                531,
                103,
                60,
                86,
                60,
                86,
                50,
                "Normal",
                "1,1",
                "Escucha",
                "31,0",
                "Alma Cura",
                "Percibe el estado físico y emocional de otros seres mediante sus sensibles orejas, capaces de detectar sonidos mínimos.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\531.jpg"));
        listaPokemon.add(new Lucha("Conkeldurr",
                534,
                105,
                140,
                95,
                55,
                65,
                45,
                "Lucha",
                "1,4",
                "Musculoso",
                "87,0",
                "Agallas",
                "Domina técnicas de construcción y combate con grandes bloques de hormigón, que maneja con sorprendente facilidad.",
                "♀/♂",
                "Lucha",
                "Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\534.jpg"));
        listaPokemon.add(new Agua("Seismitoad",
                537,
                105,
                95,
                75,
                85,
                75,
                74,
                "Agua/Tierra",
                "1,5",
                "Vibración",
                "62,0",
                "Nado Rápido",
                "Produce fuertes vibraciones mediante los bultos de su cuerpo y puede provocar ondas capaces de partir roca.",
                "♀/♂",
                "Agua,Tierra",
                "Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\537.jpg"));
        listaPokemon.add(new Planta("Whimsicott",
                547,
                60,
                67,
                85,
                77,
                75,
                116,
                "Planta/Hada",
                "0,7",
                "Viento Veloz",
                "6,6",
                "Bromista",
                "Se deja llevar por el viento y puede colarse por pequeñas rendijas, dejando rastros de algodón a su paso.",
                "♀/♂",
                "Planta,Hada",
                "Fuego,Hielo,Veneno,Volador,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\547.jpg"));
        listaPokemon.add(new Planta("Lilligant",
                549,
                70,
                60,
                75,
                110,
                75,
                90,
                "Planta",
                "1,1",
                "Floración",
                "16,3",
                "Clorofila",
                "La flor de su cabeza desprende un aroma agradable, pero requiere muchos cuidados para mantenerse saludable.",
                "♀",
                "Planta",
                "Fuego,Hielo,Veneno,Volador,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\549.jpg"));
        listaPokemon.add(new Tierra("Krookodile",
                553,
                95,
                117,
                80,
                65,
                70,
                92,
                "Tierra/Siniestro",
                "1,5",
                "Intimidación",
                "96,3",
                "Intimidación",
                "Posee una visión excelente incluso en tormentas de arena y unas mandíbulas capaces de destrozar objetos muy resistentes.",
                "♀/♂",
                "Tierra,Siniestro",
                "Agua,Planta,Hielo,Lucha,Bicho,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\553.jpg"));
        listaPokemon.add(new Fuego("Darmanitan",
                555,
                105,
                140,
                55,
                30,
                55,
                95,
                "Fuego",
                "1,3",
                "Candente",
                "92,9",
                "Potencia Bruta",
                "Su fuego interno aumenta cuando se enfurece, permitiéndole liberar una fuerza física extraordinaria.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\555.jpg"));
        listaPokemon.add(new Normal("Scrafty",
                560,
                65,
                90,
                115,
                45,
                115,
                58,
                "Siniestro/Lucha",
                "1,1",
                "Maleante",
                "30,0",
                "Mudar",
                "Protege su territorio en grupos y utiliza la piel suelta de su cuerpo como defensa durante los combates.",
                "♀/♂",
                "Siniestro,Lucha",
                "Lucha,Volador,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\560.jpg"));
        listaPokemon.add(new Psiquico("Sigilyph",
                561,
                72,
                58,
                80,
                103,
                80,
                97,
                "Psiquico/Volador",
                "1,4",
                "Pájaroide",
                "14,0",
                "Piel Milagro",
                "Patrulla siempre las mismas rutas como si estuviera protegiendo una antigua ciudad, siguiendo un comportamiento casi invariable.",
                "♀/♂",
                "Psiquico,Volador",
                "Electrico,Hielo,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\561.jpg"));
        listaPokemon.add(new Fantasma("Cofagrigus",
                563,
                58,
                50,
                145,
                95,
                105,
                30,
                "Fantasma",
                "1,7",
                "Ataúd",
                "76,5",
                "Momia",
                "Se disfraza de sarcófago y, según antiguas historias, castiga a quienes se acercan movidos por la codicia.",
                "♀/♂",
                "Fantasma",
                "Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\563.jpg"));
        listaPokemon.add(new Agua("Carracosta",
                565,
                74,
                108,
                133,
                83,
                65,
                32,
                "Agua/Roca",
                "1,2",
                "Prototortuga",
                "81,0",
                "Roca Sólida",
                "Puede triturar roca y acero con sus poderosas mandíbulas, y se desplazaba tanto por tierra como por el mar.",
                "♀/♂",
                "Agua,Roca",
                "Electrico,Planta,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\565.jpg"));
        listaPokemon.add(new Roca("Archeops",
                567,
                75,
                140,
                65,
                112,
                65,
                110,
                "Roca/Volador",
                "1,4",
                "Primer Pájaro",
                "32,0",
                "Flaqueza",
                "Aunque puede volar, suele tomar impulso corriendo y destaca por una gran fuerza en sus patas y alas.",
                "♀/♂",
                "Roca,Volador",
                "Agua,Electrico,Hielo,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\567.jpg"));
        listaPokemon.add(new Veneno("Garbodor",
                569,
                80,
                95,
                82,
                60,
                82,
                75,
                "Veneno",
                "1,9",
                "Vertedero",
                "107,3",
                "Hedor",
                "Absorbe basura y residuos, generando gases y toxinas que puede expulsar desde sus brazos.",
                "♀/♂",
                "Veneno",
                "Tierra,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\569.jpg"));
        listaPokemon.add(new Normal("Zoroark",
                571,
                60,
                105,
                60,
                120,
                60,
                105,
                "Siniestro",
                "1,6",
                "Zorro Ilusión",
                "81,1",
                "Ilusión",
                "Crea ilusiones extremadamente realistas para engañar a sus enemigos y proteger tanto a su grupo como a su territorio.",
                "♀/♂",
                "Siniestro",
                "Lucha,Bicho,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\571.jpg"));
        listaPokemon.add(new Psiquico("Gothitelle",
                576,
                70,
                55,
                95,
                95,
                110,
                65,
                "Psiquico",
                "1,5",
                "Cuerpo Astral",
                "44,0",
                "Cacheo",
                "Observa la luz de las estrellas para predecir acontecimientos futuros y se dice que puede percibir la duración de la vida.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\576.jpg"));
        listaPokemon.add(new Psiquico("Reuniclus",
                579,
                110,
                65,
                75,
                125,
                85,
                30,
                "Psiquico",
                "1,0",
                "Multiplicación",
                "20,1",
                "Funda",
                "Sus brazos gelatinosos poseen una enorme fuerza y sus células están conectadas mediante una poderosa energía psíquica.",
                "♀/♂",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\579.jpg"));
        listaPokemon.add(new Agua("Swanna",
                581,
                75,
                87,
                63,
                87,
                63,
                98,
                "Agua/Volador",
                "1,3",
                "Ave Blanca",
                "24,2",
                "Vista Lince",
                "Vuela en grupos con movimientos elegantes y puede atacar coordinadamente mientras se desplaza sobre lagos y ríos.",
                "♀/♂",
                "Agua,Volador",
                "Electrico,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\581.jpg"));
        listaPokemon.add(new Hielo("Vanilluxe",
                584,
                71,
                95,
                85,
                110,
                95,
                79,
                "Hielo",
                "1,3",
                "Ventisca",
                "57,5",
                "Gélido",
                "Genera intensas ventiscas al expulsar aire helado y puede congelar la humedad que lo rodea.",
                "♀/♂",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\584.jpg"));
        listaPokemon.add(new Planta("Amoonguss",
                591,
                114,
                85,
                70,
                85,
                80,
                30,
                "Planta/Veneno",
                "0,6",
                "Hongo",
                "10,5",
                "Efecto Espora",
                "Imita la forma de una Poké Ball con el dibujo de su sombrero para atraer presas antes de liberar esporas.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Hielo,Volador,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\591.jpg"));
        listaPokemon.add(new Planta("Ferrothorn",
                598,
                74,
                94,
                131,
                54,
                116,
                20,
                "Planta/Acero",
                "1,0",
                "Vaina Espina",
                "110,0",
                "Punta Acero",
                "Se aferra a paredes y techos con sus extremidades y dispara púas metálicas para defenderse.",
                "♀/♂",
                "Planta,Acero",
                "Fuego,Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\598.jpg"));
        listaPokemon.add(new Normal("Klinklang",
                601,
                60,
                100,
                115,
                70,
                85,
                90,
                "Acero",
                "0,6",
                "Engranaje",
                "81,0",
                "Más",
                "Sus engranajes giran a gran velocidad para acumular energía y lanzar ataques mediante el gran engranaje central.",
                "Sin genero",
                "Acero",
                "Fuego,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\601.jpg"));
        listaPokemon.add(new Electrico("Eelektross",
                604,
                85,
                115,
                80,
                105,
                80,
                50,
                "Electrico",
                "2,1",
                "Electropez",
                "80,5",
                "Levitación",
                "Puede salir del agua y desplazarse por tierra usando sus extremidades, atacando a la presa con su boca dentada.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\604.jpg"));
        listaPokemon.add(new Fantasma("Chandelure",
                609,
                60,
                55,
                90,
                145,
                90,
                80,
                "Fantasma/Fuego",
                "1,0",
                "Señuelo",
                "34,3",
                "Absorbe Fuego",
                "Absorbe la energía vital con sus llamas y se dice que las almas afectadas pueden vagar durante mucho tiempo.",
                "♀/♂",
                "Fantasma,Fuego",
                "Agua,Tierra,Roca,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\609.jpg"));
        listaPokemon.add(new Dragon("Haxorus",
                612,
                76,
                147,
                90,
                60,
                70,
                97,
                "Dragon",
                "1,8",
                "Boca Hacha",
                "105,5",
                "Rivalidad",
                "Sus colmillos de acero son extremadamente resistentes y los utiliza para cortar objetos duros sin perder filo.",
                "♀/♂",
                "Dragon",
                "Hielo,Dragon,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\612.jpg"));
        listaPokemon.add(new Tierra("Golurk",
                623,
                89,
                124,
                80,
                55,
                80,
                55,
                "Tierra/Fantasma",
                "2,8",
                "Autómata",
                "330,0",
                "Puño Férreo",
                "Fue creado en la antigüedad para proteger personas y Pokémon, y puede volar al liberar energía desde sus extremidades.",
                "Sin genero",
                "Tierra,Fantasma",
                "Agua,Planta,Hielo,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\623.jpg"));
        listaPokemon.add(new Normal("Bisharp",
                625,
                65,
                125,
                100,
                60,
                70,
                70,
                "Siniestro/Acero",
                "1,6",
                "Filo Espada",
                "70,0",
                "Competitivo",
                "Lidera grupos de Pawniard y combate de manera implacable para mantener su posición dentro de la manada.",
                "♀/♂",
                "Siniestro,Acero",
                "Fuego,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\625.jpg"));
        listaPokemon.add(new Normal("Braviary",
                628,
                100,
                123,
                75,
                57,
                75,
                80,
                "Normal/Volador",
                "1,5",
                "Valiente",
                "41,0",
                "Vista Lince",
                "Es famoso por su valentía y lucha sin retroceder para proteger a sus compañeros, incluso frente a rivales superiores.",
                "♂",
                "Normal,Volador",
                "Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\628.jpg"));
        listaPokemon.add(new Normal("Hydreigon",
                635,
                92,
                105,
                90,
                125,
                90,
                98,
                "Siniestro/Dragon",
                "1,8",
                "Brutal",
                "160,0",
                "Levitación",
                "Ataca todo lo que se mueve con sus tres cabezas y es conocido por su naturaleza extremadamente violenta.",
                "♀/♂",
                "Siniestro,Dragon",
                "Hielo,Lucha,Bicho,Dragon,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\635.jpg"));
        listaPokemon.add(new Bicho("Volcarona",
                637,
                85,
                60,
                65,
                135,
                105,
                100,
                "Bicho/Fuego",
                "1,6",
                "Sol",
                "46,0",
                "Cuerpo Llama",
                "Esparce escamas ardientes desde sus alas y antiguamente se creía que podía sustituir al sol durante épocas oscuras.",
                "♀/♂",
                "Bicho,Fuego",
                "Agua,Volador,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\637.jpg"));
        listaPokemon.add(new Normal("Cobalion",
                638,
                91,
                90,
                129,
                90,
                72,
                108,
                "Acero/Lucha",
                "2,1",
                "Tesón Acero",
                "250,0",
                "Justiciero",
                "Posee un cuerpo y una voluntad firmes como el acero, y según las leyendas protege a otros Pokémon de los humanos.",
                "Sin genero",
                "Acero,Lucha",
                "Fuego,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\638.jpg"));
        listaPokemon.add(new Roca("Terrakion",
                639,
                91,
                129,
                90,
                72,
                90,
                108,
                "Roca/Lucha",
                "1,9",
                "Gruta",
                "260,0",
                "Justiciero",
                "Su enorme fuerza le permite atravesar murallas y antiguas historias lo describen luchando para proteger a otros Pokémon.",
                "Sin genero",
                "Roca,Lucha",
                "Agua,Planta,Lucha,Tierra,Psiquico,Acero,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\639.jpg"));
        listaPokemon.add(new Planta("Virizion",
                640,
                91,
                90,
                72,
                90,
                129,
                108,
                "Planta/Lucha",
                "2,0",
                "Pradera",
                "200,0",
                "Justiciero",
                "Se mueve con gran velocidad y utiliza los cuernos de su cabeza como cuchillas para atacar con precisión.",
                "Sin genero",
                "Planta,Lucha",
                "Fuego,Hielo,Veneno,Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\640.jpg"));
        listaPokemon.add(new Volador("Tornadus",
                641,
                79,
                115,
                70,
                125,
                80,
                111,
                "Volador",
                "1,5",
                "Torbellino",
                "63,0",
                "Bromista",
                "Genera fuertes vientos con la energía de su cola y puede provocar tormentas capaces de arrasar grandes extensiones.",
                "♂",
                "Volador",
                "Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\641.jpg"));
        listaPokemon.add(new Electrico("Thundurus",
                642,
                79,
                115,
                70,
                125,
                80,
                111,
                "Electrico/Volador",
                "1,5",
                "Centella",
                "61,0",
                "Bromista",
                "Lanza potentes rayos desde su cola y recorre los cielos causando tormentas eléctricas allí por donde pasa.",
                "♂",
                "Electrico,Volador",
                "Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\642.jpg"));
        listaPokemon.add(new Dragon("Reshiram",
                643,
                100,
                120,
                100,
                150,
                120,
                90,
                "Dragon/Fuego",
                "3,2",
                "Blanco Veraz",
                "330,0",
                "Turbollama",
                "Su cola arde como un poderoso motor y puede alterar el clima liberando enormes cantidades de calor.",
                "Sin genero",
                "Dragon,Fuego",
                "Tierra,Roca,Dragon",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\643.jpg"));
        listaPokemon.add(new Dragon("Zekrom",
                644,
                100,
                150,
                120,
                120,
                100,
                90,
                "Dragon/Electrico",
                "2,9",
                "Negro Ideal",
                "345,0",
                "Terravoltaje",
                "Produce electricidad en su cola y puede envolver su cuerpo en una intensa energía antes de lanzar devastadores ataques.",
                "Sin genero",
                "Dragon,Electrico",
                "Hielo,Tierra,Dragon,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\644.jpg"));
        listaPokemon.add(new Tierra("Landorus",
                645,
                89,
                125,
                90,
                115,
                80,
                101,
                "Tierra/Volador",
                "1,5",
                "Abundancia",
                "68,0",
                "Poder Arena",
                "Su presencia favorece las cosechas, pues la energía que libera enriquece la tierra y ayuda al crecimiento de las plantas.",
                "♂",
                "Tierra,Volador",
                "Agua,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\645.jpg"));
        listaPokemon.add(new Dragon("Kyurem",
                646,
                125,
                130,
                90,
                130,
                90,
                95,
                "Dragon/Hielo",
                "3,0",
                "Frontera",
                "325,0",
                "Presión",
                "Genera un frío extremo dentro de su cuerpo, aunque su propia estructura puede sufrir debido a las bajas temperaturas.",
                "Sin genero",
                "Dragon,Hielo",
                "Lucha,Roca,Dragon,Acero,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\646.jpg"));
        listaPokemon.add(new Agua("Keldeo",
                647,
                91,
                72,
                90,
                129,
                90,
                108,
                "Agua/Lucha",
                "1,4",
                "Potro",
                "48,5",
                "Justiciero",
                "Se desplaza sobre el agua con gran velocidad y fortalece su determinación tras entrenar junto a los espadachines legendarios.",
                "Sin genero",
                "Agua,Lucha",
                "Electrico,Planta,Volador,Psiquico,Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\647.jpg"));
        listaPokemon.add(new Normal("Meloetta",
                648,
                100,
                77,
                77,
                128,
                128,
                90,
                "Normal/Psiquico",
                "0,6",
                "Melodía",
                "6,5",
                "Dicha",
                "Sus melodías pueden influir en las emociones de quienes las escuchan y su forma de combatir cambia según la canción.",
                "Sin genero",
                "Normal,Psiquico",
                "Bicho,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\648.jpg"));
        listaPokemon.add(new Bicho("Genesect",
                649,
                71,
                120,
                95,
                120,
                95,
                99,
                "Bicho/Acero",
                "1,5",
                "Paleozoico",
                "82,5",
                "Descarga",
                "Fue modificado a partir de un Pokémon prehistórico y lleva un potente cañón instalado en su espalda.",
                "Sin genero",
                "Bicho,Acero",
                "Fuego",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\TESELIA\\649.jpg"));

        return listaPokemon;
    }
}
