package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();

        listaPokemon.add(new Planta("Bulbasaur", 1,
                45,
                49,
                49,
                65,
                65,
                45,
                "Planta/Veneno",
                "0,7",
                "Semilla",
                "6,9",
                "Espesura",
                "Tras nacer, crece alimentándose durante un tiempo de los nutrientes que contiene el bulbo de su lomo.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\bulbasaur.jpg"));
        listaPokemon.add(new Planta("Ivysaur",
                2,
                60,
                62,
                63,
                80,
                80,
                60,
                "Planta/Veneno",
                "1,0",
                "Semilla",
                "13,0",
                "Espesura",
                "Cuanta más luz solar recibe, más aumenta su fuerza y más se desarrolla el capullo que tiene en el lomo.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\ivysaur.jpg"));
        listaPokemon.add(new Planta("Venusau",
                3,
                80,
                82,
                83,
                100,
                100,
                80,
                "Planta/Veneno",
                "2,0",
                "Semilla",
                "100,0",
                "Espesura",
                "Después de un día de lluvia, el aroma de la flor que tiene en el lomo se intensifica y atrae a otros Pokémon.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\venusaur.jpg"));
        listaPokemon.add(new Fuego("Charmander",
                4,
                39,
                52,
                43,
                60,
                50,
                65,
                "Fuego",
                "0,6",
                "Lagartija",
                "8,5",
                "Mar Llamas",
                "La llama de su cola indica su fuerza vital. Si está débil, la llama arderá más tenue.",
                "♀/♂",
                "Fuego",
                "Agua,Roca,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\charmander.jpg"));
        listaPokemon.add(new Fuego("Charmeleon",
                5,
                58,
                64,
                58,
                80,
                65,
                80,
                "Fuego",
                "1,1",
                "Llama",
                "19,0",
                "Mar Llamas",
                "Al agitar su ardiente cola, eleva poco a poco la temperatura a su alrededor para sofocar a sus rivales.",
                "♀/♂",
                "Fuego",
                "Agua,Roca,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\charmeleon.jpg"));
        listaPokemon.add(new Fuego("Charizard",
                6,
                78,
                84,
                78,
                109,
                85,
                100,
                "Fuego/Volador",
                "1,7",
                "Llama",
                "90.5",
                "Mar Llamas",
                "Sus potentes alas le permiten volar a una altura de 1,400 m. Escupe llamaradas que alcanzan temperaturas muy elevadas.",
                "♀/♂",
                "Fuego,Volador",
                "Agua,Electrico,Roca X",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\charizard.jpg"));
        listaPokemon.add(new Agua("Squirtle",
                7,
                44,
                48,
                65,
                50,
                64,
                43,
                "Agua",
                "0,5",
                "Tortuguita",
                "9,0",
                "Torrente",
                "Tras nacer, se le hincha el lomo y se le forma un caparazón. Escupe poderosa espuma por la boca.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\squirtle.jpg"));
        listaPokemon.add(new Agua("Wartortle",
                8,
                59,
                63,
                80,
                65,
                80,
                58,
                "Agua",
                "1,0",
                "Tortuga",
                "22,5",
                "Torrente",
                "Tiene una cola larga y peluda que simboliza la longevidad y lo hace popular entre los mayores.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\wartortle.jpg"));
        listaPokemon.add(new Agua("Blastoise",
                9,
                79,
                83,
                100,
                85,
                105,
                78,
                "Agua",
                "1,6",
                "Armazon",
                "85,5",
                "Torrente",
                "Para vencer a su enemigo, lo aplasta con el peso de su cuerpo. En momentos de apuro, se esconde en el caparazón.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\blastoise.jpg"));
        listaPokemon.add(new Bicho("Caterpie",
                10,
                45,
                30,
                35,
                20,
                20,
                45,
                "Bicho",
                "0,3",
                "Gusano",
                "2,9",
                "Polvo Escudo",
                "Para protegerse, despide un hedor horrible por las antenas con el que repele a sus enemigos.",
                "♀/♂",
                "Bicho",
                "Fuego,Volador,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\caterpie.jpg"));
        listaPokemon.add(new Bicho("Metapod",
                11,
                50,
                20,
                55,
                25,
                25,
                30,
                "Bicho",
                "0,7",
                "Capullo",
                "9,9",
                "Mudar",
                "Como en este estado solo puede endurecer su coraza, permanece inmóvil a la espera de evolucionar.",
                "♀/♂",
                "Bicho",
                "Fuego,Volador,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\11.jpg"));
        listaPokemon.add(new Bicho("Butterfree",
                12,
                60,
                45,
                50,
                90,
                80,
                70,
                "Bicho/Volador",
                "1,1",
                "Mariposa",
                "32,0",
                "Ojo Compuesto",
                "Adora el néctar de las flores. Una pequeña cantidad de polen le basta para localizar prados floridos.",
                "♀/♂",
                "Bicho,Volador",
                "Fuego,Electrico,Volador,Roca X,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\12.jpg"));
        listaPokemon.add(new Bicho("Weedle",
                13,
                40,
                35,
                30,
                20,
                20,
                50,
                "Bicho/Veneno",
                "0,3",
                "Oruga",
                "3,2",
                "Polvo Escudo",
                "El aguijón de la cabeza es muy puntiagudo. Se alimenta de hojas oculto en la espesura de bosques y praderas.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\13.jpg"));
        listaPokemon.add(new Bicho("Kakuna",
                14,
                45,
                25,
                50,
                25,
                25,
                35,
                "Bicho/Veneno",
                "0,6",
                "Capullo",
                "10,0",
                "Mudar",
                "Aunque es casi incapaz de moverse, en caso de sentirse amenazado puede envenenar a los enemigos con su aguijón.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\14.jpg"));
        listaPokemon.add(new Bicho("Beedrill",
                15,
                65,
                90,
                40,
                45,
                80,
                75,
                "Bicho/Veneno",
                "1,0",
                "Abeja Veneno",
                "29.5",
                "Enjambre",
                "Tiene tres aguijones venenosos, dos en las patas anteriores y uno en la parte baja del abdomen, con los que ataca a sus enemigos una y otra vez.",
                "♀/♂",
                "Bicho,Veneno",
                "Fuego,Volador,Roca,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\15.jpg"));
        listaPokemon.add(new Volador("Pidgey",
                16,
                40,
                45,
                40,
                35,
                35,
                56,
                "Normal/Volador",
                "0,3",
                "Pajarito",
                "1,8",
                "Vista Lince, Tumbos",
                "Su docilidad es tal que suelen defenderse levantando arena en lugar de contraatacar.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Roca,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\16.jpg"));
        listaPokemon.add(new Volador("Pidgeotto",
                17,
                63,
                60,
                55,
                50,
                50,
                71,
                "Normal/Volador",
                "1,1",
                "Pajaro",
                "30,0",
                "Vista Lince, Tumbos",
                "Su extraordinaria vitalidad y resistencia le permiten cubrir grandes distancias del territorio que habita en busca de presas.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Roca,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\17.jpg"));
        listaPokemon.add(new Volador("Pidgeot",
                18,
                83,
                80,
                75,
                70,
                70,
                101,
                "Normal/Volador",
                "1,5",
                "Pajaro",
                "39,5",
                "Vista Lince, Tumbos",
                "Este Pokémon vuela a una velocidad de 2 mach en busca de presas. Sus grandes garras son armas muy peligrosas.",
                "♀/♂",
                "Normal,Volador",
                "Electrico,Roca,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\18.jpg"));
        listaPokemon.add(new Normal("Rattata",
                19,
                30,
                56,
                35,
                25,
                35,
                72,
                "Normal",
                "0,3",
                "Raton",
                "3,5",
                "Fuga, Agallas",
                "Es propenso a hincar los incisivos en cualquier cosa que se le ponga por delante. Si se ve alguno, seguramente haya cuarenta cerca.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\19.jpg"));
        listaPokemon.add(new Normal("Raticate",
                20,
                55,
                81,
                60,
                50,
                70,
                97,
                "Normal",
                "0,7",
                "Raton",
                "18,5",
                "Fuga, Agallas",
                "Gracias a las pequeñas membranas de las patas traseras, puede nadar por los ríos para capturar presas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\20.jpg"));
        listaPokemon.add(new Volador("Spearow",
                21,
                40,
                60,
                30,
                31,
                31,
                70,
                "Normal/Volador",
                "0,3",
                "Pajaro",
                "2,0",
                "Vista Lince, Francotirador",
                "Tiene un sentido de la orientación excepcional. Puede regresar a su nido aunque se encuentre muy lejos de él.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\21.jpg"));
        listaPokemon.add(new Volador("Fearow",
                22,
                65,
                90,
                65,
                61,
                61,
                100,
                "Normal/Volador",
                "1,2",
                "Pico",
                "38,0",
                "Vista Lince, Francotirador",
                "Puede volar a gran velocidad y recorrer grandes distancias sin descansar.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\22.jpg"));
        listaPokemon.add(new Veneno("Ekans",
                23,
                35,
                60,
                44,
                40,
                54,
                55,
                "Veneno",
                "2,0",
                "Serpiente",
                "6,9",
                "Mudar, Intimidacion, Nerviosismo",
                "Se mueve silenciosamente entre la hierba y ataca a sus presas desde una posicion inesperada.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\23.jpg"));
        listaPokemon.add(new Veneno("Arbok",
                24,
                60,
                95,
                69,
                65,
                79,
                80,
                "Veneno",
                "3,5",
                "Cobra",
                "65,0",
                "Mudar, Intimidacion, Nerviosismo",
                "El dibujo de su pecho puede cambiar y se cree que tiene un efecto intimidante sobre sus enemigos.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\24.jpg"));
        listaPokemon.add(new Electrico("Pikachu",
                25,
                35,
                55,
                40,
                50,
                50,
                90,
                "Electrico",
                "0,4",
                "Raton",
                "6,0",
                "Electricidad Estatica, Pararrayos",
                "Cuando se enfada, descarga la electricidad que almacena en las bolsas de sus mejillas.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\25.jpg"));
        listaPokemon.add(new Electrico("Raichu",
                26,
                60,
                90,
                55,
                90,
                80,
                110,
                "Electrico",
                "0,8",
                "Raton",
                "30,0",
                "Electricidad Estatica, Pararrayos",
                "Puede acumular una enorme cantidad de electricidad y descargarla a traves de su cola.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\26.jpg"));
        listaPokemon.add(new Tierra("Sandshrew",
                27,
                50,
                75,
                85,
                20,
                30,
                40,
                "Tierra",
                "0,6",
                "Raton",
                "12,0",
                "Velo Arena",
                "Se enrolla en una bola para protegerse de los ataques. Vive principalmente en zonas secas.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\27.jpg"));
        listaPokemon.add(new Tierra("Sandslash",
                28,
                75,
                100,
                110,
                45,
                55,
                65,
                "Tierra",
                "1,0",
                "Raton",
                "29,5",
                "Velo Arena",
                "Sus garras y espinas le permiten excavar rapidamente y defenderse de sus enemigos.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\28.jpg"));
        listaPokemon.add(new Veneno("Nidoran♀",
                29,
                55,
                47,
                52,
                40,
                40,
                41,
                "Veneno",
                "0,4",
                "Venenoso",
                "7,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Aunque es pequeño, puede defenderse utilizando los venenos que produce en sus grandes orejas.",
                "♀",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\29.jpg"));
        listaPokemon.add(new Veneno("Nidorina",
                30,
                70,
                62,
                67,
                55,
                55,
                56,
                "Veneno",
                "0,8",
                "Venenoso",
                "20,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Es mas calmada que Nidoran y utiliza sus garras para protegerse cuando se siente amenazada.",
                "♀",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\30.jpg"));
        listaPokemon.add(new Veneno("Nidoqueen",
                31,
                90,
                92,
                87,
                75,
                85,
                76,
                "Veneno/Tierra",
                "1,3",
                "Taladro",
                "60,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Su cuerpo esta cubierto por escamas resistentes que le permiten proteger a sus crias de los peligros.",
                "♀",
                "Veneno, Tierra",
                "Agua, Hielo, Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\31.jpg"));
        listaPokemon.add(new Veneno("Nidoran♂",
                32,
                46,
                57,
                40,
                40,
                40,
                50,
                "Veneno",
                "0,5",
                "Venenoso",
                "9,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Su cuerpo es pequeño, pero sus grandes orejas contienen veneno que utiliza para defenderse.",
                "♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\32.jpg"));
        listaPokemon.add(new Veneno("Nidorino",
                33,
                61,
                72,
                57,
                55,
                55,
                65,
                "Veneno",
                "0,9",
                "Venenoso",
                "19,5",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Tiene un cuerno muy desarrollado y puede atacar ferozmente cuando se siente amenazado.",
                "♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\33.jpg"));
        listaPokemon.add(new Veneno("Nidoking",
                34,
                81,
                102,
                77,
                85,
                75,
                85,
                "Veneno/Tierra",
                "1,4",
                "Taladro",
                "62,0",
                "Punto Veneno, Rivalidad, Entusiasmo",
                "Su poderoso cuerno puede atravesar incluso materiales resistentes y lo utiliza para atacar a sus enemigos.",
                "♂",
                "Veneno, Tierra",
                "Agua, Hielo, Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\34.jpg"));
        listaPokemon.add(new Normal("Clefairy",
                35,
                70,
                45,
                48,
                60,
                65,
                35,
                "Hada",
                "0,6",
                "Hada",
                "7,5",
                "Gran Encanto, Muro Magico, Amortiguador",
                "Es dificil de encontrar y suele aparecer bajo la luz de la luna llena.",
                "♀/♂",
                "Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\35.jpg"));
        listaPokemon.add(new Normal("Clefable",
                36,
                95,
                70,
                73,
                95,
                90,
                60,
                "Hada",
                "1,3",
                "Hada",
                "40,0",
                "Gran Encanto, Muro Magico, Amortiguador",
                "Tiene un oido extremadamente sensible y puede escuchar sonidos muy lejanos.",
                "♀/♂",
                "Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\36.jpg"));
        listaPokemon.add(new Fuego("Vulpix",
                37,
                38,
                41,
                40,
                50,
                65,
                65,
                "Fuego",
                "0,6",
                "Zorro",
                "9,9",
                "Absorbe Fuego, Sequedad",
                "Al nacer tiene una sola cola que se divide con el tiempo hasta convertirse en seis.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\37.jpg"));
        listaPokemon.add(new Fuego("Ninetales",
                38,
                73,
                76,
                75,
                81,
                100,
                100,
                "Fuego",
                "1,1",
                "Zorro",
                "19,9",
                "Absorbe Fuego, Sequedad",
                "Cuenta la leyenda que cada una de sus nueve colas posee poderes misteriosos.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\38.jpg"));
        listaPokemon.add(new Normal("Jigglypuff",
                39,
                115,
                45,
                20,
                45,
                25,
                20,
                "Normal/Hada",
                "0,5",
                "Globo",
                "5,5",
                "Gran Encanto, Tenacidad, Competitivo",
                "Canta una melodia relajante que puede hacer que quienes la escuchan se queden profundamente dormidos.",
                "♀/♂",
                "Normal, Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\39.jpg"));
        listaPokemon.add(new Normal("Wigglytuff",
                40,
                140,
                70,
                45,
                85,
                50,
                45,
                "Normal/Hada",
                "1,0",
                "Globo",
                "12,0",
                "Gran Encanto, Tenacidad, Competitivo",
                "Su cuerpo suave y elastico puede inflarse hasta alcanzar un tamaño enorme.",
                "♀/♂",
                "Normal, Hada",
                "Veneno, Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\40.jpg"));
        listaPokemon.add(new Volador("Zubat",
                41,
                40,
                45,
                35,
                30,
                40,
                55,
                "Veneno/Volador",
                "0,8",
                "Murcielago",
                "7,5",
                "Fuerza Mental, Infiltrador",
                "Vive en cuevas oscuras y utiliza ondas ultrasonicas para orientarse.",
                "♀/♂",
                "Veneno, Volador",
                "Electrico, Hielo, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\41.jpg"));
        listaPokemon.add(new Volador("Golbat",
                42,
                75,
                80,
                70,
                65,
                75,
                90,
                "Veneno/Volador",
                "1,6",
                "Murcielago",
                "55,0",
                "Fuerza Mental, Infiltrador",
                "Cuando muerde a su presa, no la suelta hasta haber absorbido una gran cantidad de sangre.",
                "♀/♂",
                "Veneno, Volador",
                "Electrico, Hielo, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\42.jpg"));
        listaPokemon.add(new Planta("Oddish",
                43,
                45,
                50,
                55,
                75,
                65,
                30,
                "Planta/Veneno",
                "0,5",
                "Hierba",
                "5,4",
                "Clorofila, Fuga",
                "Durante el dia se entierra en la tierra para evitar la luz solar y por la noche busca alimento.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\43.jpg"));
        listaPokemon.add(new Planta("Gloom",
                44,
                60,
                65,
                70,
                85,
                75,
                40,
                "Planta/Veneno",
                "0,8",
                "Hierba",
                "8,6",
                "Clorofila, Fuga",
                "De su flor desprende un olor desagradable que puede hacer que otros Pokemon se alejen.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\44.jpg"));
        listaPokemon.add(new Planta("Vileplume",
                45,
                75,
                80,
                85,
                110,
                90,
                50,
                "Planta/Veneno",
                "1,2",
                "Flor",
                "18,6",
                "Clorofila",
                "Cuanto mas grande es el polen de su flor, mas potente es el veneno que contiene.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\45.jpg"));
        listaPokemon.add(new Bicho("Paras",
                46,
                35,
                70,
                55,
                45,
                55,
                25,
                "Bicho/Planta",
                "0,3",
                "Hongo",
                "5,4",
                "Efecto Espora, Piel Seca, Humedad",
                "Los hongos que crecen sobre su espalda absorben nutrientes del cuerpo del Pokemon.",
                "♀/♂",
                "Bicho, Planta",
                "Fuego, Hielo, Veneno, Volador, Bicho, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\46.jpg"));
        listaPokemon.add(new Bicho("Parasect",
                47,
                60,
                95,
                80,
                60,
                80,
                30,
                "Bicho/Planta",
                "1,0",
                "Hongo",
                "29,5",
                "Efecto Espora, Piel Seca, Humedad",
                "El hongo ha tomado completamente el control de su cuerpo y libera esporas toxicas.",
                "♀/♂",
                "Bicho, Planta",
                "Fuego, Hielo, Veneno, Volador, Bicho, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\47.jpg"));
        listaPokemon.add(new Bicho("Venonat",
                48,
                60,
                55,
                50,
                40,
                55,
                45,
                "Bicho/Veneno",
                "1,0",
                "Insecto",
                "30,0",
                "Ojo Compuesto, Polvo Escudo, Cromolente",
                "Sus grandes ojos pueden detectar incluso pequeños movimientos en la oscuridad.",
                "♀/♂",
                "Bicho, Veneno",
                "Fuego, Volador, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\48.jpg"));
        listaPokemon.add(new Bicho("Venomoth",
                49,
                70,
                65,
                60,
                90,
                75,
                90,
                "Bicho/Veneno",
                "1,5",
                "Polilla",
                "12,5",
                "Ojo Compuesto, Polvo Escudo, Cromolente",
                "Sus alas liberan escamas venenosas que pueden causar distintos efectos a sus enemigos.",
                "♀/♂",
                "Bicho, Veneno",
                "Fuego, Volador, Psiquico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\49.jpg"));
        listaPokemon.add(new Tierra("Diglett",
                50,
                10,
                55,
                25,
                35,
                45,
                95,
                "Tierra",
                "0,2",
                "Topo",
                "0,8",
                "Velo Arena, Trampa Arena, Poder Arena",
                "Pasa la mayor parte de su vida bajo tierra y rara vez se deja ver en la superficie.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\50.jpg"));
        listaPokemon.add(new Tierra("Dugtrio",
                51,
                35,
                100,
                50,
                50,
                70,
                120,
                "Tierra",
                "0,7",
                "Topo",
                "33,3",
                "Velo Arena, Trampa Arena, Poder Arena",
                "Tres Diglett viven juntos y trabajan en equipo para excavar enormes tuneles.",
                "♀/♂",
                "Tierra",
                "Agua, Planta, Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\51.jpg"));
        listaPokemon.add(new Normal("Meowth",
                52,
                40,
                45,
                35,
                40,
                40,
                90,
                "Normal",
                "0,4",
                "Gato",
                "4,2",
                "Recogida, Experto, Nerviosismo",
                "Le encantan los objetos brillantes y suele recoger monedas que encuentra por las calles.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\52.jpg"));
        listaPokemon.add(new Normal("Persian",
                53,
                65,
                70,
                60,
                65,
                65,
                115,
                "Normal",
                "1,0",
                "Gato Fino",
                "32,0",
                "Flexibilidad, Experto, Nerviosismo",
                "Su aspecto elegante oculta un temperamento agresivo y sus garras son extremadamente afiladas.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\53.jpg"));
        listaPokemon.add(new Agua("Psyduck",
                54,
                50,
                52,
                48,
                65,
                50,
                55,
                "Agua",
                "0,8",
                "Pato",
                "19,6",
                "Humedad, Nublado, Aclimatacion",
                "Sufre constantemente de dolores de cabeza que pueden despertar sus poderes psiquicos.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\54.jpg"));
        listaPokemon.add(new Agua("Golduck",
                55,
                80,
                82,
                78,
                95,
                80,
                85,
                "Agua",
                "1,7",
                "Pato",
                "76,6",
                "Humedad, Nublado, Aclimatacion",
                "Es un excelente nadador y puede alcanzar velocidades impresionantes en el agua.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\55.jpg"));
        listaPokemon.add(new Lucha("Mankey",
                56,
                40,
                80,
                35,
                35,
                45,
                70,
                "Lucha",
                "0,5",
                "Cerdo Mono",
                "28,0",
                "Espiritu Vital, Ira Vital, Competitivo",
                "Es muy irritable y puede enfadarse rapidamente incluso por motivos insignificantes.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\56.jpg"));
        listaPokemon.add(new Lucha("Primeape",
                57,
                65,
                105,
                60,
                60,
                70,
                95,
                "Lucha",
                "1,0",
                "Mono Cerdo",
                "32,0",
                "Espiritu Vital, Ira Vital, Competitivo",
                "Su furia aumenta hasta tal punto que puede perseguir a su objetivo sin descanso.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\57.jpg"));
        listaPokemon.add(new Fuego("Growlithe",
                58,
                55,
                70,
                45,
                70,
                50,
                60,
                "Fuego",
                "0,7",
                "Cachorro",
                "19,0",
                "Intimidacion, Absorbe Fuego, Justiciero",
                "Es leal y protector. Puede aprender rapidamente a obedecer las ordenes de su entrenador.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\58.jpg"));
        listaPokemon.add(new Fuego("Arcanine",
                59,
                90,
                110,
                80,
                100,
                80,
                95,
                "Fuego",
                "1,9",
                "Legendario",
                "155,0",
                "Intimidacion, Absorbe Fuego, Justiciero",
                "Es admirado por su belleza y majestuosidad. Puede recorrer grandes distancias a gran velocidad.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\59.jpg"));
        listaPokemon.add(new Agua("Poliwag",
                60,
                40,
                50,
                40,
                40,
                40,
                90,
                "Agua",
                "0,6",
                "Renacuajo",
                "12,4",
                "Absorbe Agua, Humedad, Nado Rapido",
                "La piel de su cuerpo es tan fina que pueden verse sus organos internos.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\60.jpg"));
        listaPokemon.add(new Agua("Poliwhirl",
                61,
                65,
                65,
                65,
                50,
                50,
                90,
                "Agua",
                "1,0",
                "Renacuajo",
                "20,0",
                "Absorbe Agua, Humedad, Nado Rapido",
                "El dibujo espiral de su vientre tiene un efecto hipnotico sobre quienes lo observan.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\61.jpg"));
        listaPokemon.add(new Agua("Poliwrath",
                62,
                90,
                95,
                95,
                70,
                90,
                70,
                "Agua/Lucha",
                "1,3",
                "Renacuajo",
                "54,0",
                "Absorbe Agua, Humedad, Nado Rapido",
                "Sus poderosos musculos le permiten nadar largas distancias sin cansarse.",
                "♀/♂",
                "Agua, Lucha",
                "Electrico, Planta, Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\62.jpg"));
        listaPokemon.add(new Psiquico("Abra",
                63,
                25,
                20,
                15,
                105,
                55,
                90,
                "Psiquico",
                "0,9",
                "Psiquico",
                "19,5",
                "Sincronía, Foco Interno, Muro Magico",
                "Duerme durante la mayor parte del dia y utiliza la teletransportacion incluso mientras duerme.",
                "♀/♂",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\63.jpg"));
        listaPokemon.add(new Psiquico("Kadabra",
                64,
                40,
                35,
                30,
                120,
                70,
                105,
                "Psiquico",
                "1,3",
                "Psiquico",
                "56,5",
                "Sincronía, Foco Interno, Muro Magico",
                "Su poder psiquico aumenta cuando sostiene su cuchara y puede causar fuertes dolores de cabeza.",
                "♀/♂",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\64.jpg"));
        listaPokemon.add(new Psiquico("Alakazam",
                65,
                55,
                50,
                45,
                135,
                95,
                120,
                "Psiquico",
                "1,5",
                "Psiquico",
                "48,0",
                "Sincronía, Foco Interno, Muro Magico",
                "Posee una inteligencia extraordinaria y se dice que tiene un coeficiente intelectual de 5000.",
                "♀/♂",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\65.jpg"));
        listaPokemon.add(new Lucha("Machop",
                66,
                70,
                80,
                50,
                35,
                35,
                35,
                "Lucha",
                "0,8",
                "Superpoder",
                "19,5",
                "Agallas, Indefenso, Impasible",
                "Aunque es pequeño, tiene una fuerza extraordinaria y entrena constantemente para hacerse mas fuerte.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\66.jpg"));
        listaPokemon.add(new Lucha("Machoke",
                67,
                80,
                100,
                70,
                50,
                60,
                45,
                "Lucha",
                "1,5",
                "Superpoder",
                "70,5",
                "Agallas, Indefenso, Impasible",
                "Su enorme musculatura le proporciona una fuerza fisica impresionante.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\67.jpg"));
        listaPokemon.add(new Lucha("Machamp",
                68,
                90,
                130,
                80,
                65,
                85,
                55,
                "Lucha",
                "1,6",
                "Superpoder",
                "130,0",
                "Agallas, Indefenso, Impasible",
                "Sus cuatro brazos pueden lanzar una gran cantidad de golpes en pocos segundos.",
                "♀/♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\68.jpg"));
        listaPokemon.add(new Planta("Bellsprout",
                69,
                50,
                75,
                35,
                70,
                30,
                40,
                "Planta/Veneno",
                "0,7",
                "Flor",
                "4,0",
                "Clorofila, Gula",
                "Su cuerpo flexible le permite esquivar ataques mientras utiliza sus raices para absorber agua.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\69.jpg"));
        listaPokemon.add(new Planta("Weepinbell",
                70,
                65,
                90,
                50,
                85,
                45,
                55,
                "Planta/Veneno",
                "1,0",
                "Mosquero",
                "6,4",
                "Clorofila, Gula",
                "Su cuerpo se asemeja a una planta carnivora y utiliza liquidos digestivos para atrapar presas.",
                "♀/♂",
                "Planta, Veneno",
                "Fuego, Hielo, Volador, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\70.jpg"));
        listaPokemon.add(new Normal("Doduo",
                84,
                35,
                85,
                45,
                35,
                35,
                75,
                "Normal/Volador",
                "1,4",
                "Ave Gemela",
                "39,2",
                "Fuga, Madrugar, Intrépido",
                "Tiene dos cabezas que piensan de manera independiente y pueden correr a gran velocidad.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\84.jpg"));
        listaPokemon.add(new Normal("Dodrio",
                85,
                60,
                110,
                70,
                60,
                60,
                110,
                "Normal/Volador",
                "1,8",
                "Ave Gemela",
                "85,2",
                "Fuga, Madrugar, Intrépido",
                "Sus tres cabezas representan diferentes personalidades y pueden trabajar de forma coordinada.",
                "♀/♂",
                "Normal, Volador",
                "Electrico, Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\85.jpg"));
        listaPokemon.add(new Agua("Seel",
                86,
                65,
                45,
                55,
                45,
                70,
                45,
                "Agua",
                "1,1",
                "Leon Marino",
                "90,0",
                "Sebo, Hidratacion, Gélido",
                "Prefiere las aguas frias y utiliza su cuerno para abrirse paso entre el hielo.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\86.jpg"));
        listaPokemon.add(new Agua("Dewgong",
                87,
                90,
                70,
                80,
                70,
                95,
                70,
                "Agua/Hielo",
                "1,7",
                "Leon Marino",
                "120,0",
                "Sebo, Hidratacion, Gélido",
                "Su cuerpo esta cubierto por una gruesa capa de grasa que le permite vivir en aguas heladas.",
                "♀/♂",
                "Agua, Hielo",
                "Electrico, Planta, Lucha, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\87.jpg"));
        listaPokemon.add(new Veneno("Grimer",
                88,
                80,
                80,
                50,
                40,
                50,
                25,
                "Veneno",
                "0,9",
                "Lodo",
                "30,0",
                "Velo Liquido, Viscosidad, Toque Toxico",
                "Nace a partir del lodo contaminado y deja un rastro de sustancias toxicas por donde pasa.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\88.jpg"));
        listaPokemon.add(new Veneno("Muk",
                89,
                105,
                105,
                75,
                65,
                100,
                50,
                "Veneno",
                "1,2",
                "Lodo",
                "30,0",
                "Velo Liquido, Viscosidad, Toque Toxico",
                "Su cuerpo esta formado por sustancias toxicas y puede contaminar todo lo que toca.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\89.jpg"));
        listaPokemon.add(new Agua("Shellder",
                90,
                30,
                65,
                100,
                45,
                25,
                40,
                "Agua",
                "0,3",
                "Bivalvo",
                "4,0",
                "Caparazon, Encadenado, Funda",
                "Su caparazon es extremadamente duro y permanece cerrado para proteger su cuerpo.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\90.jpg"));
        listaPokemon.add(new Agua("Cloyster",
                91,
                50,
                95,
                180,
                85,
                45,
                70,
                "Agua/Hielo",
                "1,5",
                "Bivalvo",
                "132,5",
                "Caparazon, Encadenado, Funda",
                "Su caparazon puede soportar una fuerza enorme y sus numerosas espinas sirven para atacar.",
                "♀/♂",
                "Agua, Hielo",
                "Electrico, Planta, Lucha, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\91.jpg"));
        listaPokemon.add(new Fantasma("Gastly",
                92,
                30,
                35,
                30,
                100,
                35,
                80,
                "Fantasma/Veneno",
                "1,3",
                "Gas",
                "0,1",
                "Levitacion",
                "Su cuerpo esta compuesto principalmente por gas y puede atravesar paredes y objetos solidos.",
                "♀/♂",
                "Fantasma, Veneno",
                "Tierra, Psiquico, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\92.jpg"));
        listaPokemon.add(new Fantasma("Haunter",
                93,
                45,
                50,
                45,
                115,
                55,
                95,
                "Fantasma/Veneno",
                "1,6",
                "Gas",
                "0,1",
                "Levitacion",
                "Puede esconderse en las sombras y lamer a sus victimas para debilitarlas.",
                "♀/♂",
                "Fantasma, Veneno",
                "Tierra, Psiquico, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\93.jpg"));
        listaPokemon.add(new Fantasma("Gengar",
                94,
                60,
                65,
                60,
                130,
                75,
                110,
                "Fantasma/Veneno",
                "1,5",
                "Sombra",
                "40,5",
                "Cuerpo Maldito",
                "Se esconde en las sombras de las personas y disfruta asustando a quienes encuentra.",
                "♀/♂",
                "Fantasma, Veneno",
                "Tierra, Psiquico, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\94.jpg"));
        listaPokemon.add(new Agua("Krabby",
                98,
                30,
                105,
                90,
                25,
                25,
                50,
                "Agua",
                "0,4",
                "Cangrejo",
                "6,5",
                "Corte Fuerte, Caparazon, Potencia Bruta",
                "Sus grandes pinzas pueden romper objetos duros y tambien las utiliza para defenderse.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\98.jpg"));
        listaPokemon.add(new Agua("Kingler",
                99,
                55,
                130,
                115,
                50,
                50,
                75,
                "Agua",
                "1,3",
                "Tenaza",
                "60,0",
                "Corte Fuerte, Caparazon, Potencia Bruta",
                "Una de sus pinzas es mucho mas grande que la otra y puede ejercer una fuerza enorme.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\99.jpg"));
        listaPokemon.add(new Lucha("Hitmonlee",
                106,
                50,
                120,
                53,
                35,
                110,
                87,
                "Lucha",
                "1,5",
                "Patada",
                "49,8",
                "Flexibilidad, Audaz, Impasible",
                "Sus piernas pueden estirarse y sus patadas son extremadamente potentes.",
                "♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\106.jpg"));
        listaPokemon.add(new Lucha("Hitmonchan",
                107,
                50,
                105,
                79,
                35,
                110,
                76,
                "Lucha",
                "1,4",
                "Puñetazo",
                "50,2",
                "Vista Lince, Puño Ferreo, Impasible",
                "Sus puños se mueven tan rapidamente que pueden parecer una rafaga continua de golpes.",
                "♂",
                "Lucha",
                "Volador, Psiquico, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\107.jpg"));
        listaPokemon.add(new Normal("Lickitung",
                108,
                90,
                55,
                75,
                60,
                75,
                30,
                "Normal",
                "1,2",
                "Lametazo",
                "65,5",
                "Despiste, Ritmo Propio, Nube de Humo",
                "Su lengua es tan larga que puede extenderla hasta casi dos metros y utilizarla como una mano.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\108.jpg"));
        listaPokemon.add(new Veneno("Koffing",
                109,
                40,
                65,
                95,
                60,
                45,
                35,
                "Veneno",
                "0,6",
                "Gas Venenoso",
                "1,0",
                "Levitacion",
                "Su cuerpo contiene gases toxicos que libera constantemente a traves de sus poros.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\109.jpg"));
        listaPokemon.add(new Veneno("Weezing",
                110,
                65,
                90,
                120,
                85,
                70,
                60,
                "Veneno",
                "1,2",
                "Gas Venenoso",
                "9,5",
                "Levitacion",
                "Dos Koffing se unen y mezclan sus gases toxicos para producir una sustancia aun mas peligrosa.",
                "♀/♂",
                "Veneno",
                "Tierra, Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\110.jpg"));
        listaPokemon.add(new Normal("Chansey",
                113,
                250,
                5,
                5,
                35,
                105,
                50,
                "Normal",
                "1,1",
                "Huevo",
                "34,6",
                "Cura Natural, Dicha, Alma Cura",
                "Pone huevos muy nutritivos y suele compartirlos con personas o Pokemon heridos.",
                "♀",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\113.jpg"));
        listaPokemon.add(new Psiquico("Mr. Mime",
                122,
                40,
                45,
                65,
                100,
                120,
                90,
                "Psiquico/Hada",
                "1,3",
                "Barrera",
                "54,5",
                "Filtro, Tecnico, Insonorizar",
                "Es experto en crear barreras invisibles mediante movimientos de mimo y puede bloquear ataques.",
                "♀/♂",
                "Psiquico, Hada",
                "Veneno, Acero, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\122.jpg"));
        listaPokemon.add(new Bicho("Scyther",
                123,
                70,
                110,
                80,
                55,
                80,
                105,
                "Bicho/Volador",
                "1,5",
                "Mantis",
                "56,0",
                "Enjambre, Experto, Impasible",
                "Sus guadañas son tan afiladas que puede cortar troncos gruesos con facilidad.",
                "♀/♂",
                "Bicho, Volador",
                "Fuego, Electrico, Hielo, Volador, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\123.jpg"));
        listaPokemon.add(new Psiquico("Jynx",
                124,
                65,
                50,
                35,
                115,
                95,
                95,
                "Hielo/Psiquico",
                "1,4",
                "Humanoide",
                "40,6",
                "Despiste, Alerta, Ritmo Propio",
                "Se comunica mediante una especie de lenguaje propio basado principalmente en movimientos y sonidos.",
                "♀",
                "Hielo, Psiquico",
                "Fuego, Acero, Bicho, Roca, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\124.jpg"));
        listaPokemon.add(new Electrico("Electabuzz",
                125,
                65,
                83,
                57,
                95,
                85,
                105,
                "Electrico",
                "1,1",
                "Electrico",
                "30,0",
                "Electricidad Estatica, Espiritu Vital",
                "Absorbe electricidad de los generadores y puede provocar apagones cuando hay tormentas.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\125.jpg"));
        listaPokemon.add(new Fuego("Magmar",
                126,
                65,
                95,
                57,
                100,
                85,
                93,
                "Fuego",
                "1,3",
                "Escupefuego",
                "44,5",
                "Cuerpo Llama, Espiritu Vital",
                "Su cuerpo esta tan caliente que puede incendiar accidentalmente los lugares por donde pasa.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\126.jpg"));
        listaPokemon.add(new Normal("Eevee",
                133,
                55,
                55,
                50,
                45,
                65,
                55,
                "Normal",
                "0,3",
                "Evolucion",
                "6,5",
                "Fuga, Adaptable, Anticipacion",
                "Su estructura genetica es inestable y le permite evolucionar de diferentes maneras dependiendo del entorno.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\133.jpg"));
        listaPokemon.add(new Agua("Vaporeon",
                134,
                130,
                65,
                60,
                110,
                95,
                65,
                "Agua",
                "1,0",
                "Burbuja",
                "29,0",
                "Absorbe Agua, Hidratacion",
                "Su cuerpo esta adaptado para vivir en el agua y puede disolverse parcialmente en ella.",
                "♀/♂",
                "Agua",
                "Electrico, Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\134.jpg"));
        listaPokemon.add(new Electrico("Jolteon",
                135,
                65,
                65,
                60,
                110,
                95,
                130,
                "Electrico",
                "0,8",
                "Relampago",
                "24,5",
                "Absorbe Electricidad, Volt Absorb",
                "Tiene el pelo lleno de electricidad estatica y puede disparar miles de rayos por segundo.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\135.jpg"));
        listaPokemon.add(new Fuego("Flareon",
                136,
                65,
                130,
                60,
                95,
                110,
                65,
                "Fuego",
                "0,9",
                "Llama",
                "25,0",
                "Absorbe Fuego, Agallas",
                "Almacena aire en una bolsa interna y lo calienta hasta producir llamas extremadamente intensas.",
                "♀/♂",
                "Fuego",
                "Agua, Tierra, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\136.jpg"));
        listaPokemon.add(new Hielo("Articuno",
                144,
                90,
                85,
                100,
                95,
                125,
                85,
                "Hielo/Volador",
                "1,7",
                "Congelar",
                "55,4",
                "Presion, Manto Niveo",
                "Es un Pokemon legendario que puede congelar la humedad del aire y crear nieve y hielo.",
                "Sin genero",
                "Hielo, Volador",
                "Fuego, Electrico, Acero, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\144.jpg"));
        listaPokemon.add(new Electrico("Zapdos",
                145,
                90,
                90,
                85,
                125,
                90,
                100,
                "Electrico/Volador",
                "1,6",
                "Electrico",
                "52,6",
                "Presion, Electricidad Estatica",
                "Un Pokemon legendario que aparece durante tormentas y puede generar enormes cantidades de electricidad.",
                "Sin genero",
                "Electrico, Volador",
                "Hielo, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\145.jpg"));
        listaPokemon.add(new Fuego("Moltres",
                146,
                90,
                100,
                90,
                125,
                85,
                90,
                "Fuego/Volador",
                "2,0",
                "Llama",
                "60,0",
                "Presion, Cuerpo Llama",
                "Un Pokemon legendario cubierto de llamas que aparece en lugares donde se producen grandes cambios de clima.",
                "Sin genero",
                "Fuego, Volador",
                "Agua, Electrico, Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\146.jpg"));
        listaPokemon.add(new Dragon("Dratini",
                147,
                41,
                64,
                45,
                50,
                50,
                50,
                "Dragon",
                "1,8",
                "Dragon",
                "3,3",
                "Mudar, Escama Especial",
                "Durante mucho tiempo se creyó que era un Pokemon mitico porque pocas personas habian logrado verlo.",
                "♀/♂",
                "Dragon",
                "Hielo, Dragon, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\147.jpg"));
        listaPokemon.add(new Dragon("Dragonair",
                148,
                61,
                84,
                65,
                70,
                70,
                70,
                "Dragon",
                "4,0",
                "Dragon",
                "16,5",
                "Mudar, Escama Especial",
                "Se dice que puede cambiar el clima utilizando las misteriosas esferas que posee alrededor de su cuello.",
                "♀/♂",
                "Dragon",
                "Hielo, Dragon, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\148.jpg"));
        listaPokemon.add(new Dragon("Dragonite",
                149,
                91,
                134,
                95,
                100,
                100,
                80,
                "Dragon/Volador",
                "2,2",
                "Dragon",
                "210,0",
                "Foco Interno, Multiescamas",
                "Es extremadamente inteligente y puede volar alrededor del mundo en aproximadamente dieciseis horas.",
                "♀/♂",
                "Dragon, Volador",
                "Hielo, Roca, Dragon, Hada",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\149.jpg"));
        listaPokemon.add(new Psiquico("Mewtwo",
                150,
                106,
                110,
                90,
                154,
                90,
                130,
                "Psiquico",
                "2,0",
                "Genetico",
                "122,0",
                "Presion, Nerviosismo",
                "Fue creado mediante manipulacion genetica y posee un poder psiquico extraordinario.",
                "Sin genero",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\150.jpg"));
        listaPokemon.add(new Psiquico("Mew",
                151,
                100,
                100,
                100,
                100,
                100,
                100,
                "Psiquico",
                "0,4",
                "Nueva Especie",
                "4,0",
                "Sincronía",
                "Posee el ADN de todos los Pokemon y puede aprender cualquier movimiento.",
                "Sin genero",
                "Psiquico",
                "Bicho, Fantasma, Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\KANTO\\No\\151.jpg"));

        return listaPokemon;
    }
}