package repository;

import model.Pokemon;
import model.tipos.*;

import java.util.ArrayList;
import java.util.List;

public class PokedexSinnohRepository {

    public static List<Pokemon> obtenerListaPokemon() {
        List<Pokemon> listaPokemon = new ArrayList<>();

        listaPokemon.add(new Planta("Torterra",
                389,
                95,
                109,
                105,
                75,
                85,
                56,
                "Planta/Tierra",
                "1,9",
                "Continente",
                "310,0",
                "Espesura",
                "Torterra es un Pokemon originario de Sinnoh de tipo Planta/Tierra.",
                "♀/♂",
                "Planta,Tierra",
                "Fuego,Volador,Hielo,Bicho,Veneno,Agua,Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\389.jpg"));
        listaPokemon.add(new Fuego("Infernape",
                392,
                76,
                104,
                71,
                104,
                71,
                108,
                "Fuego/Lucha",
                "1,2",
                "Llama",
                "55,0",
                "Mar Llamas",
                "Infernape es un Pokemon originario de Sinnoh de tipo Fuego/Lucha.",
                "♀/♂",
                "Fuego,Lucha",
                "Agua,Tierra,Roca,Volador,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\392.jpg"));
        listaPokemon.add(new Agua("Empoleon",
                395,
                84,
                86,
                88,
                111,
                101,
                60,
                "Agua/Acero",
                "1,7",
                "Emperador",
                "84,5",
                "Torrente",
                "Empoleon es un Pokemon originario de Sinnoh de tipo Agua/Acero.",
                "♀/♂",
                "Agua,Acero",
                "Planta,Electrico,Fuego,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\395.jpg"));
        listaPokemon.add(new Normal("Staraptor",
                398,
                85,
                120,
                70,
                50,
                60,
                100,
                "Normal/Volador",
                "1,2",
                "Depredador",
                "24,9",
                "Intimidacion",
                "Staraptor es un Pokemon originario de Sinnoh de tipo Normal/Volador.",
                "♀/♂",
                "Normal,Volador",
                "Lucha,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\398.jpg"));
        listaPokemon.add(new Normal("Bibarel",
                400,
                79,
                85,
                60,
                55,
                60,
                71,
                "Normal/Agua",
                "1,0",
                "Castor",
                "31,5",
                "Simple,Ignorante",
                "Bibarel es un Pokemon originario de Sinnoh de tipo Normal/Agua.",
                "♀/♂",
                "Normal,Agua",
                "Lucha,Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\400.jpg"));
        listaPokemon.add(new Bicho("Kricketune",
                402,
                77,
                85,
                51,
                55,
                51,
                65,
                "Bicho",
                "1,0",
                "Grillo",
                "25,5",
                "Enjambre",
                "Kricketune es un Pokemon originario de Sinnoh de tipo Bicho.",
                "♀/♂",
                "Bicho",
                "Fuego,Volador,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\402.jpg"));
        listaPokemon.add(new Electrico("Luxray",
                405,
                80,
                120,
                79,
                95,
                79,
                70,
                "Electrico",
                "1,4",
                "Chispa",
                "42,0",
                "Rivalidad,Intimidacion",
                "Luxray es un Pokemon originario de Sinnoh de tipo Electrico.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\405.jpg"));
        listaPokemon.add(new Planta("Roserade",
                407,
                60,
                70,
                65,
                125,
                105,
                90,
                "Planta/Veneno",
                "0,9",
                "Ramillete",
                "14,5",
                "Cura Natural,Punto Toxico",
                "Roserade es un Pokemon originario de Sinnoh de tipo Planta/Veneno.",
                "♀/♂",
                "Planta,Veneno",
                "Fuego,Volador,Hielo,Bicho,Veneno,Tierra,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\407.jpg"));
        listaPokemon.add(new Roca("Rampardos",
                409,
                97,
                165,
                60,
                65,
                50,
                58,
                "Roca",
                "1,6",
                "Testarazo",
                "102,5",
                "Rompemoldes",
                "Rampardos es un Pokemon originario de Sinnoh de tipo Roca.",
                "♀/♂",
                "Roca",
                "Agua,Planta,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\409.jpg"));
        listaPokemon.add(new Roca("Bastiodon",
                411,
                60,
                52,
                168,
                47,
                138,
                30,
                "Roca/Acero",
                "1,3",
                "Escudo",
                "149,5",
                "Robustez",
                "Bastiodon es un Pokemon originario de Sinnoh de tipo Roca/Acero.",
                "♀/♂",
                "Roca,Acero",
                "Agua,Planta,Lucha,Tierra,Acero,Fuego",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\411.jpg"));
        listaPokemon.add(new Bicho("Vespiquen",
                416,
                70,
                80,
                102,
                80,
                102,
                40,
                "Bicho/Volador",
                "1,2",
                "Colmena",
                "38,5",
                "Presion",
                "Vespiquen es un Pokemon originario de Sinnoh de tipo Bicho/Volador.",
                "♀",
                "Bicho,Volador",
                "Fuego,Volador,Roca,Electrico,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\416.jpg"));
        listaPokemon.add(new Agua("Floatzel",
                419,
                85,
                105,
                55,
                85,
                50,
                115,
                "Agua",
                "1,1",
                "Nutria Mar",
                "33,5",
                "Nado Rapido",
                "Floatzel es un Pokemon originario de Sinnoh de tipo Agua.",
                "♀/♂",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\419.jpg"));
        listaPokemon.add(new Agua("Gastrodon",
                423,
                111,
                83,
                68,
                92,
                82,
                39,
                "Agua/Tierra",
                "0,9",
                "Babosa Mar",
                "29,9",
                "Viscosidad,Colector",
                "Gastrodon es un Pokemon originario de Sinnoh de tipo Agua/Tierra.",
                "♀/♂",
                "Agua,Tierra",
                "Planta,Electrico,Agua,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\423.jpg"));
        listaPokemon.add(new Fantasma("Drifblim",
                426,
                150,
                80,
                44,
                90,
                54,
                80,
                "Fantasma/Volador",
                "1,2",
                "Dirigible",
                "15,0",
                "Detonacion,Liviano",
                "Drifblim es un Pokemon originario de Sinnoh de tipo Fantasma/Volador.",
                "♀/♂",
                "Fantasma,Volador",
                "Fantasma,Siniestro,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\426.jpg"));
        listaPokemon.add(new Normal("Lopunny",
                428,
                65,
                76,
                84,
                54,
                96,
                105,
                "Normal",
                "1,2",
                "Conejo",
                "33,3",
                "Fuga,Zoquete",
                "Lopunny es un Pokemon originario de Sinnoh de tipo Normal.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\428.jpg"));
        listaPokemon.add(new Fantasma("Mismagius",
                429,
                60,
                60,
                60,
                105,
                105,
                105,
                "Fantasma",
                "0,9",
                "Magico",
                "4,4",
                "Levitacion",
                "Mismagius es un Pokemon originario de Sinnoh de tipo Fantasma.",
                "♀/♂",
                "Fantasma",
                "Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\429.jpg"));
        listaPokemon.add(new Normal("Honchkrow",
                430,
                100,
                125,
                52,
                105,
                52,
                71,
                "Siniestro/Volador",
                "0,9",
                "Gran Jefe",
                "27,3",
                "Insomnio,Afortunado",
                "Honchkrow es un Pokemon originario de Sinnoh de tipo Siniestro/Volador.",
                "♀/♂",
                "Siniestro,Volador",
                "Lucha,Bicho,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\430.jpg"));
        listaPokemon.add(new Normal("Purugly",
                432,
                71,
                82,
                64,
                64,
                59,
                112,
                "Normal",
                "1,0",
                "Gato Tigre",
                "43,8",
                "Sebo,Ritmo Propio",
                "Purugly es un Pokemon originario de Sinnoh de tipo Normal.",
                "♀/♂",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\432.jpg"));
        listaPokemon.add(new Veneno("Skuntank",
                435,
                103,
                93,
                67,
                71,
                61,
                84,
                "Veneno/Siniestro",
                "1,0",
                "Mofeta",
                "38,0",
                "Hedor,Detonacion",
                "Skuntank es un Pokemon originario de Sinnoh de tipo Veneno/Siniestro.",
                "♀/♂",
                "Veneno,Siniestro",
                "Tierra,Psiquico,Lucha,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\435.jpg"));
        listaPokemon.add(new Normal("Bronzong",
                437,
                67,
                89,
                116,
                79,
                116,
                33,
                "Acero/Psiquico",
                "1,3",
                "Campana Bronce",
                "187,0",
                "Levitacion,Ignifugo",
                "Bronzong es un Pokemon originario de Sinnoh de tipo Acero/Psiquico.",
                "Sin genero",
                "Acero,Psiquico",
                "Fuego,Lucha,Tierra,Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\437.jpg"));
        listaPokemon.add(new Fantasma("Spiritomb",
                442,
                50,
                92,
                108,
                92,
                108,
                35,
                "Fantasma/Siniestro",
                "1,0",
                "Prohibido",
                "108,0",
                "Presion",
                "Spiritomb es un Pokemon originario de Sinnoh de tipo Fantasma/Siniestro.",
                "♀/♂",
                "Fantasma,Siniestro",
                "Fantasma,Siniestro,Lucha,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\442.jpg"));
        listaPokemon.add(new Dragon("Garchomp",
                445,
                108,
                130,
                95,
                80,
                85,
                102,
                "Dragon/Tierra",
                "1,9",
                "Mach",
                "95,0",
                "Velo Arena",
                "Garchomp es un Pokemon originario de Sinnoh de tipo Dragon/Tierra.",
                "♀/♂",
                "Dragon,Tierra",
                "Hielo,Dragon,Agua,Planta",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\445.jpg"));
        listaPokemon.add(new Lucha("Lucario",
                448,
                70,
                110,
                70,
                115,
                70,
                90,
                "Lucha/Acero",
                "1,2",
                "Aura",
                "54,0",
                "Foco Interno,Impasible",
                "Lucario es un Pokemon originario de Sinnoh de tipo Lucha/Acero.",
                "♀/♂",
                "Lucha,Acero",
                "Volador,Psiquico,Fuego,Lucha,Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\448.jpg"));
        listaPokemon.add(new Tierra("Hippowdon",
                450,
                108,
                112,
                118,
                68,
                72,
                47,
                "Tierra",
                "2,0",
                "Peso Pesado",
                "300,0",
                "Chorro Arena",
                "Hippowdon es un Pokemon originario de Sinnoh de tipo Tierra.",
                "♀/♂",
                "Tierra",
                "Agua,Planta,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\450.jpg"));
        listaPokemon.add(new Veneno("Drapion",
                452,
                70,
                90,
                110,
                60,
                75,
                95,
                "Veneno/Siniestro",
                "1,3",
                "Escorpion Ogro",
                "61,5",
                "Armadura Batalla,Francotirador",
                "Drapion es un Pokemon originario de Sinnoh de tipo Veneno/Siniestro.",
                "♀/♂",
                "Veneno,Siniestro",
                "Tierra,Psiquico,Lucha,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\452.jpg"));
        listaPokemon.add(new Veneno("Toxicroak",
                454,
                83,
                106,
                65,
                86,
                65,
                85,
                "Veneno/Lucha",
                "1,3",
                "Boca Toxica",
                "44,4",
                "Anticipacion,Piel Seca",
                "Toxicroak es un Pokemon originario de Sinnoh de tipo Veneno/Lucha.",
                "♀/♂",
                "Veneno,Lucha",
                "Tierra,Psiquico,Volador",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\454.jpg"));

        listaPokemon.add(new Planta("Abomasnow",
                460,
                90,
                92,
                75,
                92,
                85,
                60,
                "Planta/Hielo",
                "2,2",
                "Arbol Nieve",
                "135,5",
                "Nevada",
                "Abomasnow es un Pokemon originario de Sinnoh de tipo Planta/Hielo.",
                "♀/♂",
                "Planta,Hielo",
                "Fuego,Volador,Hielo,Bicho,Veneno,Lucha,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\460.jpg"));
        listaPokemon.add(new Electrico("Magnezone",
                462,
                70,
                70,
                115,
                130,
                90,
                60,
                "Electrico/Acero",
                "1,2",
                "Zona Iman",
                "180,0",
                "Iman,Robustez",
                "Magnezone es un Pokemon originario de Sinnoh de tipo Electrico/Acero.",
                "Sin genero",
                "Electrico,Acero",
                "Tierra,Fuego,Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\462.jpg"));
        listaPokemon.add(new Tierra("Rhyperior",
                464,
                115,
                140,
                130,
                55,
                55,
                40,
                "Tierra/Roca",
                "2,4",
                "Taladro",
                "282,8",
                "Pararrayos,Roca Solida",
                "Rhyperior es un Pokemon originario de Sinnoh de tipo Tierra/Roca.",
                "♀/♂",
                "Tierra,Roca",
                "Agua,Planta,Hielo,Lucha,Tierra,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\464.jpg"));
        listaPokemon.add(new Electrico("Electivire",
                466,
                75,
                123,
                67,
                95,
                85,
                95,
                "Electrico",
                "1,8",
                "Rayo",
                "138,6",
                "Electromotor",
                "Electivire es un Pokemon originario de Sinnoh de tipo Electrico.",
                "♀/♂",
                "Electrico",
                "Tierra",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\466.jpg"));
        listaPokemon.add(new Fuego("Magmortar",
                467,
                75,
                95,
                67,
                125,
                95,
                83,
                "Fuego",
                "1,6",
                "Explosivo",
                "68,0",
                "Cuerpo Llama",
                "Magmortar es un Pokemon originario de Sinnoh de tipo Fuego.",
                "♀/♂",
                "Fuego",
                "Agua,Tierra,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\467.jpg"));
        listaPokemon.add(new Normal("Togekiss",
                468,
                85,
                50,
                95,
                120,
                115,
                80,
                "Normal/Volador",
                "1,5",
                "Festejo",
                "38,0",
                "Entusiasmo,Dicha",
                "Togekiss es un Pokemon originario de Sinnoh de tipo Normal/Volador.",
                "♀/♂",
                "Normal,Volador",
                "Lucha,Electrico,Hielo,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\468.jpg"));

        listaPokemon.add(new Planta("Leafeon",
                470,
                65,
                110,
                130,
                60,
                65,
                95,
                "Planta",
                "1,0",
                "Verdor",
                "25,5",
                "Defensa Hoja",
                "Leafeon es un Pokemon originario de Sinnoh de tipo Planta.",
                "♀/♂",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\470.jpg"));
        listaPokemon.add(new Hielo("Glaceon",
                471,
                65,
                60,
                110,
                130,
                95,
                65,
                "Hielo",
                "0,8",
                "Nieve Fresca",
                "25,9",
                "Manto Niveo",
                "Glaceon es un Pokemon originario de Sinnoh de tipo Hielo.",
                "♀/♂",
                "Hielo",
                "Fuego,Lucha,Roca,Acero",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\471.jpg"));
        listaPokemon.add(new Tierra("Gliscor",
                472,
                75,
                95,
                125,
                45,
                75,
                95,
                "Tierra/Volador",
                "2,0",
                "Colmillo Escorpion",
                "42,5",
                "Corte Fuerte,Velo Arena",
                "Gliscor es un Pokemon originario de Sinnoh de tipo Tierra/Volador.",
                "♀/♂",
                "Tierra,Volador",
                "Agua,Planta,Hielo,Electrico,Roca",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\472.jpg"));
        listaPokemon.add(new Hielo("Mamoswine",
                473,
                110,
                130,
                80,
                70,
                60,
                80,
                "Hielo/Tierra",
                "2,5",
                "Doscolmillos",
                "291,0",
                "Despiste,Manto Niveo",
                "Mamoswine es un Pokemon originario de Sinnoh de tipo Hielo/Tierra.",
                "♀/♂",
                "Hielo,Tierra",
                "Fuego,Lucha,Roca,Acero,Agua,Planta,Hielo",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\473.jpg"));
        listaPokemon.add(new Normal("Porygon-Z",
                474,
                85,
                80,
                70,
                135,
                75,
                90,
                "Normal",
                "0,9",
                "Virtual",
                "34,0",
                "Adaptable,Descarga",
                "Porygon-Z es un Pokemon originario de Sinnoh de tipo Normal.",
                "Sin genero",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\474.jpg"));
        listaPokemon.add(new Psiquico("Gallade",
                475,
                68,
                125,
                65,
                65,
                115,
                80,
                "Psiquico/Lucha",
                "1,6",
                "Cuchilla",
                "52,0",
                "Impasible",
                "Gallade es un Pokemon originario de Sinnoh de tipo Psiquico/Lucha.",
                "♂",
                "Psiquico,Lucha",
                "Bicho,Fantasma,Siniestro,Volador,Psiquico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\475.jpg"));
        listaPokemon.add(new Electrico("Rotom",
                479,
                50,
                50,
                77,
                95,
                77,
                91,
                "Electrico/Fantasma",
                "0,3",
                "Plasma",
                "0,3",
                "Levitacion",
                "Rotom es un Pokemon originario de Sinnoh de tipo Electrico/Fantasma.",
                "Sin genero",
                "Electrico,Fantasma",
                "Tierra,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\479.jpg"));
        listaPokemon.add(new Psiquico("Uxie",
                480,
                75,
                75,
                130,
                75,
                130,
                95,
                "Psiquico",
                "0,3",
                "Saber",
                "0,3",
                "Levitacion",
                "Uxie es un Pokemon originario de Sinnoh de tipo Psiquico.",
                "Sin genero",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\480.jpg"));
        listaPokemon.add(new Psiquico("Mesprit",
                481,
                80,
                105,
                105,
                105,
                105,
                80,
                "Psiquico",
                "0,3",
                "Emocion",
                "0,3",
                "Levitacion",
                "Mesprit es un Pokemon originario de Sinnoh de tipo Psiquico.",
                "Sin genero",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\481.jpg"));
        listaPokemon.add(new Psiquico("Azelf",
                482,
                75,
                125,
                70,
                125,
                70,
                115,
                "Psiquico",
                "0,3",
                "Voluntad",
                "0,3",
                "Levitacion",
                "Azelf es un Pokemon originario de Sinnoh de tipo Psiquico.",
                "Sin genero",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\482.jpg"));
        listaPokemon.add(new Normal("Dialga",
                483,
                100,
                120,
                120,
                150,
                100,
                90,
                "Acero/Dragon",
                "5,4",
                "Temporal",
                "683,0",
                "Presion",
                "Dialga es un Pokemon originario de Sinnoh de tipo Acero/Dragon.",
                "Sin genero",
                "Acero,Dragon",
                "Fuego,Lucha,Tierra,Hielo,Dragon",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\483.jpg"));
        listaPokemon.add(new Agua("Palkia",
                484,
                90,
                120,
                100,
                150,
                120,
                100,
                "Agua/Dragon",
                "4,2",
                "Espacial",
                "336,0",
                "Presion",
                "Palkia es un Pokemon originario de Sinnoh de tipo Agua/Dragon.",
                "Sin genero",
                "Agua,Dragon",
                "Planta,Electrico,Hielo,Dragon",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\484.jpg"));
        listaPokemon.add(new Fuego("Heatran",
                485,
                91,
                90,
                106,
                130,
                106,
                77,
                "Fuego/Acero",
                "1,7",
                "Domo Lava",
                "430,0",
                "Absorbe Fuego",
                "Heatran es un Pokemon originario de Sinnoh de tipo Fuego/Acero.",
                "♀/♂",
                "Fuego,Acero",
                "Agua,Tierra,Roca,Fuego,Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\485.jpg"));
        listaPokemon.add(new Normal("Regigigas",
                486,
                110,
                160,
                110,
                80,
                110,
                100,
                "Normal",
                "3,7",
                "Colosal",
                "420,0",
                "Inicio Lento",
                "Regigigas es un Pokemon originario de Sinnoh de tipo Normal.",
                "Sin genero",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\486.jpg"));
        listaPokemon.add(new Fantasma("Giratina",
                487,
                150,
                100,
                120,
                100,
                120,
                90,
                "Fantasma/Dragon",
                "4,5",
                "Renegado",
                "750,0",
                "Presion",
                "Giratina es un Pokemon originario de Sinnoh de tipo Fantasma/Dragon.",
                "Sin genero",
                "Fantasma,Dragon",
                "Fantasma,Siniestro,Hielo,Dragon",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\487.jpg"));
        listaPokemon.add(new Psiquico("Cresselia",
                488,
                120,
                70,
                120,
                75,
                130,
                85,
                "Psiquico",
                "1,5",
                "Lunar",
                "85,6",
                "Levitacion",
                "Cresselia es un Pokemon originario de Sinnoh de tipo Psiquico.",
                "♀",
                "Psiquico",
                "Bicho,Fantasma,Siniestro",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\488.jpg"));
        listaPokemon.add(new Agua("Phione",
                489,
                80,
                80,
                80,
                80,
                80,
                80,
                "Agua",
                "0,4",
                "Marino",
                "3,1",
                "Hidratacion",
                "Phione es un Pokemon originario de Sinnoh de tipo Agua.",
                "Sin genero",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\489.jpg"));
        listaPokemon.add(new Agua("Manaphy",
                490,
                100,
                100,
                100,
                100,
                100,
                100,
                "Agua",
                "0,3",
                "Nautico",
                "1,4",
                "Hidratacion",
                "Manaphy es un Pokemon originario de Sinnoh de tipo Agua.",
                "Sin genero",
                "Agua",
                "Planta,Electrico",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\490.jpg"));
        listaPokemon.add(new Normal("Darkrai",
                491,
                70,
                90,
                90,
                135,
                90,
                125,
                "Siniestro",
                "1,5",
                "Oscuridad",
                "50,5",
                "Mal Sueño",
                "Darkrai es un Pokemon originario de Sinnoh de tipo Siniestro.",
                "Sin genero",
                "Siniestro",
                "Lucha,Bicho",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\491.jpg"));
        listaPokemon.add(new Planta("Shaymin",
                492,
                100,
                100,
                100,
                100,
                100,
                100,
                "Planta",
                "0,2",
                "Gratitud",
                "2,1",
                "Cura Natural",
                "Shaymin es un Pokemon originario de Sinnoh de tipo Planta.",
                "Sin genero",
                "Planta",
                "Fuego,Volador,Hielo,Bicho,Veneno",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\492.jpg"));
        listaPokemon.add(new Normal("Arceus",
                493,
                120,
                120,
                120,
                120,
                120,
                120,
                "Normal",
                "3,2",
                "Alfa",
                "320,0",
                "Multitipo",
                "Arceus es un Pokemon originario de Sinnoh de tipo Normal.",
                "Sin genero",
                "Normal",
                "Lucha",
                "C:\\Users\\octub\\Desktop\\POKEDEX\\SINNOH\\493.jpg"));

        return listaPokemon;
    }
}
